-- data_20260720050901_2026-07-20-grey-noneng-audit.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-20-grey-noneng-audit.md
-- Generated:  2026-07-20T05:09:01+00:00
-- Summary:    Grey-literature audit (non-English subset): reclassify 3 peer-reviewed academic sources mis-tagged grey (REF-00032 OTIS RCT protocol, REF-00137 Zallio Elsevier study, REF-00875 Korean POE paper) grey->clinical within T3; fix 2 wrong language tags
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Non-English grey-literature audit — reclassify peer-reviewed academic sources
-- mis-tagged as grey (owner request: "check all grey literature to confirm if it
-- actually grey or if it is just foreign language academic"; scoped to the
-- non-English subset first). Of 12 non-English grey rows, 3 are peer-reviewed
-- academic (not grey); the other 9 are genuinely grey (govt portals, handbooks,
-- a trade magazine, campus pages, policy-evaluation reports) and are left as-is.
--
-- Each of the 3 was re-verified this session via a real retrieval call:
--   REF-00032  WebSearch f1000research.com/articles/10-500 — the OTIS RCT *study
--              protocol* (peer-reviewed), Cockayne/Pighills/Fairhurst, F1000Research
--              2021; multicentre NHS England. English, not Swedish. It is a protocol
--              (methodology, not outcomes) -> T3-clinical, NOT a T1 results anchor.
--   REF-00137  WebSearch sciencedirect/repository — Zallio & Clarkson, "…A study of
--              architectural design practice," Building and Environment 206:108352
--              (Elsevier, peer-reviewed), an ethnographic study of 26 professionals.
--              English, not Finnish.
--   REF-00875  WebSearch KCI/DBpia — Lee Yong-Min & Kwon Oh-Jung, POE research-trend
--              analysis, J. Korean Inst. of Interior Design 20(3):41-48 (2011),
--              peer-reviewed. Genuinely Korean-language academic (lang ok).
--
-- All three move grey (T3 '○') -> clinical (T3 '●') WITHIN Tier 3 — no tier-number
-- change, so this is a source-type correction under existing doctrine, independent
-- of the pending weighted-strength anchor-model decision. Two carried wrong language
-- tags (langdetect on English catalogue metadata) also corrected.

-- REF-00032 — OTIS RCT study protocol (peer-reviewed; English; NHS England)
UPDATE evidence_sources
   SET evidence_type = 'clinical',
       grey_flag = 0,
       grey_reason = NULL,
       lang_detected = 'en',
       jurisdiction = 'GB',
       verification_note = COALESCE(verification_note || ' ', '') ||
         '[GREY-AUDIT NON-ENGLISH 2026-07-20] Not grey and not Swedish: peer-reviewed OTIS RCT study '
         || 'protocol (F1000Research 10-500, DOI 10.12688/f1000research.52313.1), verified via WebSearch. '
         || 'evidence_type grey->clinical; lang sv->en; jurisdiction INT->GB (multicentre NHS England). '
         || 'NOTE: this is the study PROTOCOL (methodology, not outcomes) — kept at T3, not upgraded to a '
         || 'T1 results anchor. Prior grey_flag reason was "DOI required" (a provenance TODO), now resolved.',
       updated_at = '2026-07-20T06:00:00Z',
       updated_by_session = 'session_2026-07-20-grey-noneng-audit'
 WHERE ref_id = 'REF-00032' AND tier = 3 AND evidence_type = 'grey';

-- REF-00137 — Zallio & Clarkson ethnographic study (peer-reviewed; English; UK)
UPDATE evidence_sources
   SET evidence_type = 'clinical',
       grey_flag = 0,
       grey_reason = NULL,
       lang_detected = 'en',
       verification_note = COALESCE(verification_note || ' ', '') ||
         '[GREY-AUDIT NON-ENGLISH 2026-07-20] Not grey and not Finnish: peer-reviewed Elsevier article '
         || '(Building and Environment 206:108352, DOI 10.1016/j.buildenv.2021.108352, Zallio & Clarkson), '
         || 'an ethnographic study of 26 building-industry professionals; verified via WebSearch. '
         || 'evidence_type grey->clinical (T3 qualitative primary); lang fi->en (langdetect artifact on '
         || 'English catalogue metadata). Prior grey_flag reason "DOI required" resolved.',
       updated_at = '2026-07-20T06:00:00Z',
       updated_by_session = 'session_2026-07-20-grey-noneng-audit'
 WHERE ref_id = 'REF-00137' AND tier = 3 AND evidence_type = 'grey';

-- REF-00875 — Lee & Kwon POE research-trend paper (peer-reviewed; Korean, lang ok)
UPDATE evidence_sources
   SET evidence_type = 'clinical',
       verification_note = COALESCE(verification_note || ' ', '') ||
         '[GREY-AUDIT NON-ENGLISH 2026-07-20] Genuinely non-English academic, not grey: peer-reviewed '
         || 'Korean journal article (J. Korean Inst. of Interior Design 20(3):41-48, 2011, Lee Yong-Min & '
         || 'Kwon Oh-Jung), verified via WebSearch (KCI/DBpia) and previously read as primary PDF in the '
         || 'POE adversarial pass. evidence_type grey->clinical; lang ko correct (kept).',
       updated_at = '2026-07-20T06:00:00Z',
       updated_by_session = 'session_2026-07-20-grey-noneng-audit'
 WHERE ref_id = 'REF-00875' AND tier = 3 AND evidence_type = 'grey';

COMMIT;
