-- data_20260726015337_2026-07-26-energy-conservation-rest-points-seating-adversarial.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-26-energy-conservation-rest-points-seating-adversarial.md
-- Generated:  2026-07-26T01:53:37+00:00
-- Summary:    adversarial pass remediation: R1 in-band CO1-NOT-APPLICABLE, R4 substantive linkage tracing GAP-307 to its n=171 Sydney base, population placeholders replaced with read data
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Remediation of the adversarial pass's own DoD failures.
-- R1 uses the gate's designed in-band escape; R4 is remediated with a SUBSTANTIVE new linkage
-- that the pass actually earned. R7 is NOT remediated - see the reasoned waiver in the session
-- record, because inventing a candidate row to satisfy a counter is precisely the gaming the
-- hardened gate exists to prevent.

-- R1: this pass admitted NO evidence, so there was no admission for a Co-1 pass to precede.
-- The gate documents 'CO1-NOT-APPLICABLE: <reason>' for exactly this case.
UPDATE search_executions SET
  findings_note = 'CO1-NOT-APPLICABLE: this session is a verification pass over sources already admitted in batches 1-3, not an evidence-admission batch. It admitted zero new sources, so there is no admission step for the R1 lived-experience pass to precede. The Co-1 position of this slug is unchanged and remains its weakest point - ONE Co-1 source after three batches, with a second still environment-blocked (GAP-309). Recording the waiver in-band rather than letting a structurally-inapplicable rule read as a skipped one. || ' || findings_note
WHERE session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial' AND query_text LIKE 'OpenAlex + Unpaywall%';

-- R4: a real linkage this pass earned. Reading the Kothiyal papers established the actual
-- population that REF-00953's equity argument - and therefore GAP-307 - generalises from.
INSERT INTO evidence_population_match
 (match_id, source_ref, ref_id, target_population, study_population, sample_size,
  match_grade, mismatch_note, gap_id, created_at, created_by_session)
VALUES
 ('EPM-00953-B','REF-00953','REF-00953','MOB','THE ANTHROPOMETRIC BASIS, now traced: 171 people aged 65+ (M and F) in metropolitan Sydney NSW, measured for publication 2000/2001 (REF-00963/00964, one study reported twice). This is the population REF-00953 "Jean" is drawn from and therefore the population GAP-307 equity harm actually generalises from.',171,
  'PROXY','Recorded because batches 2-3 asserted the single-height equity harm without ever stating whose bodies it rests on. Graded PROXY: the base population is Australian community/aged-care elders in ONE city measured a quarter-century ago, generalised to seating provision at large. Direction of effect and secular height trends both favour the claim, so this does not refute it - but the scope was undisclosed and now is not. Distinct from EPM-00953-A, which grades REF-00953 own aged-care participants; this row grades the anthropometric layer beneath them.','GAP-312',
  '2026-07-26','session_2026-07-26-energy-conservation-rest-points-seating-adversarial');

-- Now that the four primaries have been read, replace the honest placeholders batch 3 recorded.
UPDATE evidence_population_match SET
  study_population='Elderly subjects from long-term care and rehabilitation hospital wards, Toronto; count not stated in abstract',
  mismatch_note='UPDATED 2026-07-26 after reading the abstract. Batch 3 recorded "population not established" because only Crossref metadata had been read. Now known: participants were elderly long-term-care and rehabilitation inpatients who tested four successive chair shapes on an adjustable rig. Still PROXY - institutional inpatients rather than the served demand, and the abstract gives no participant count.'
WHERE match_id='EPM-00961-A';

UPDATE evidence_population_match SET
  study_population='NONE - no participants. Design-considerations discussion paper presenting requirements for three chair types with a described typical user.',
  mismatch_note='UPDATED 2026-07-26 after reading the abstract. Batch 3 recorded "population not established"; the answer is that there is no study population at all. Per the R13 rule that a source with no participants is PROXY at best, PROXY is retained - and the source is additionally now grey-flagged so it anchors only at the weak band.'
WHERE match_id='EPM-00962-A';

UPDATE evidence_population_match SET
  study_population='171 people aged 65+ (M and F), metropolitan Sydney NSW, Australia', sample_size=171,
  mismatch_note='UPDATED 2026-07-26 after reading the abstract. Batch 3 recorded "population not established". Now known: n=171, aged 65+, Sydney. PROXY retained - a general elderly city sample, not selected for disability or for the sustained-exertion demand. NOTE: this is THE SAME STUDY as REF-00964; the two rows must not be counted as independent population evidence.'
WHERE match_id='EPM-00963-A';

UPDATE evidence_population_match SET
  study_population='171 people aged 65+ (M and F), metropolitan Sydney NSW, Australia - 22 body dimensions', sample_size=171,
  mismatch_note='UPDATED 2026-07-26 after reading the abstract. Same n=171 Sydney study as REF-00963, reported as a short data note. PROXY retained. My batch-3 speculation that this was the upstream dataset for REF-00963 was half right: it is the same data, not a source beneath it.'
WHERE match_id='EPM-00964-A';

COMMIT;
