-- data_20260725160614_2026-07-25-energy-conservation-rest-points-seating-b2.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-25-energy-conservation-rest-points-seating-b2.md
-- Generated:  2026-07-25T16:06:14+00:00
-- Summary:    batch 2: 7 sources admitted, GAP-306 CLOSED (independence confirmed across 5 groups/6 countries), GAP-304 sharpened, 3 new gaps incl. the single-height equity harm
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Batch 2 on energy-conservation-rest-points-seating.
-- Resolves GAP-306 (independence of the resting-places finding) and adds primary evidence
-- for the seat-dimension parameters that batch 1 could only anchor on Co-1 vs a T5 standard.
-- All DOIs/PMIDs pre-checked absent (R9); all re-retrieved before admission (R10).

INSERT INTO evidence_sources
 (ref_id, source_type, first_author_last, first_author_first, author_display, pub_year,
  pub_title, journal_name, volume, issue, pages_start, pages_end, article_number, pages,
  publisher, doi, pmid, pmcid, url, url_accessed, tier, evidence_type, jurisdiction,
  language, lang_detected, verification_status, doi_resolution_outcome, verified_by_tool,
  last_verified_at, metadata_quality, grey_flag, prior_expectation, search_queries_used,
  verification_note, notes, created_at, created_by_session)
VALUES
 ('REF-00953','journal_article','Blackler','Alethea','Blackler A, Brophy C, O''Reilly M, Chamorro-Koc M',2018,
  'Seating in aged care: Physical fit, independence and comfort','SAGE Open Medicine','6',NULL,NULL,NULL,'2050312117744925',NULL,
  NULL,'10.1177/2050312117744925','29326817','PMC5758957',NULL,'2026-07-25',3,'clinical','AU',
  'EN','EN','VERIFIED','RESOLVED','mcp__PubMed__get_full_text_article','2026-07-25','high',0,
  'Staged in batch 1 as a hypothesis: possibly the only primary basis for the seat-dimension figures that otherwise rest on standards. CONFIRMED and stronger than expected — it does not merely supply dimensions, it demonstrates that a single seat height CANNOT serve the population, which is the Co-1 position batch 1 could only anchor on lived experience.',
  'R2 backward-mining lead from REF-00950 reference list; resolved via PubMed (Blackler seating aged care physical fit independence comfort)',
  'Full text retrieved and read via PubMed Central 2026-07-25. Tiered T3 not T1 on the authors own limitations statement: "The study was qualitative and collected subjective opinions of participants. It did not include objective measures of strain, pressure or movement." Audit + interview + video-observation, convenience sample, single Australian region.',
  'PRIMARY EVIDENCE FOR SEAT DIMENSIONS. n=19 aged care residents (6M/13F) + 5 staff + 2 experts (OT, physiotherapist), 4 facilities, Queensland AU; chair dimension audit (2 facilities + 4 websites, 54 seats); video-recorded sit-to-stand observation. || SEAT HEIGHT: "Residents, experts and staff all preferred higher seats to allow for effective STS transfers"; audited heights 410-505mm in facilities, 423-510mm on websites. BUT observed that "many residents could not touch the floor easily once they were seated". The paper names the conflict explicitly: "The disparity between seat height required for STS and seat height required for comfort while seated". RESOLUTION IS VARIETY, NOT A COMPROMISE NUMBER: "Variable height chairs, a range of chairs of different heights in each space and footrests could all address the height problem"; "providing a better variety of seat heights in each of the various contexts". Christenson (cited within) recommends a range of 380-457mm. || ARMRESTS: "When armrests were available they were used 100% of the time regardless of the resident''s level of mobility"; "Armrests were identified as vital by all participants"; "90% of those observed during STS needed more than one attempt to stand". Research cited within finds armrests ~250mm above seat best facilitate STS; participants reported SLIMMER armrests easier to grip, contradicting the 120mm width recommendation of Holden and Fernie. || SEAT DEPTH: observed 480-530mm in facilities vs mean buttock-popliteal length 440mm; excess depth forces slumping (posterior pelvic tilt). || SAMPLING CAVEAT recorded: "The researchers were not permitted by the facilities to approach potential resident participants directly" - facility-gatekept selection.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),

 ('REF-00954','report','Transport Scotland',NULL,'Transport Scotland',NULL,
  'Inclusive Design in Town Centres and Busy Street Areas - Appendix C: Perspectives of disabled street users on inclusive physical design',NULL,NULL,NULL,NULL,NULL,NULL,'Appendix C',
  'Transport Scotland',NULL,NULL,NULL,'https://www.transport.gov.scot/publication/inclusive-design-in-town-centres-and-busy-street-areas/appendix-c-perspectives-of-disabled-street-users-on-inclusive-physical-design/','2026-07-25',5,'national_fw','GB-SCT',
  'EN','EN','VERIFIED',NULL,'WebFetch','2026-07-25','medium',0,
  'Staged in batch 1 as a hypothesis: expected to be a SECOND jurisdiction supplying an interval figure, letting 50m be compared against a Scottish number. WRONG - it states NO interval at all. That absence is more informative than a second number would have been.',
  'Transport for All disabled-led research street design seating rest points report (web)',
  'Retrieved 2026-07-25. National framework carrying a disabled-participant focus-group appendix; page states no publication date. Focus groups structured by impairment type (hearing impaired, visually impaired, deafblind, mobility impaired, learning/non-visible); participant count not stated for the seating discussions, recorded as a metadata gap rather than estimated.',
  'R15 CORRECTED FROM THE STAGED HYPOTHESIS. States NO seating interval and NO seat dimensions - only "at regular intervals where possible". A participatory national-framework appendix declining to specify a number is corroboration for GAP-304: the interval is unspecified even where disabled people were consulted directly. || NEW DEMAND-LAYER REQUIREMENT not present in REF-00949 or REF-00950: rest points must be VISIBLE AND ANTICIPATABLE IN ADVANCE. Verbatim: "Seating should, however, be positioned so that it is possible to see from a distance i.e. to allow journey planning" and "seating options needed to be clearly signposted for people who are unfamiliar with the area to allow them to know when to anticipate potential for breaks in their journey". An unseen bench does not support the decision to attempt the journey, so provision alone is insufficient. || Also: "It was noted that push up bars / handles on seating are also helpful in allowing older people and those needing to move between seats and wheelchairs to get up more easily" (converges with REF-00953 on armrests); "it was considered necessary to place seating well away from the main thoroughfare, and at regular intervals where possible".',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),

 ('REF-00955','journal_article','Nouri','Mohammadjavad','Nouri M, Chaudhury H',2025,
  'Individual and Neighborhood Characteristics of Walking Activity in People Living With Dementia: A Proof of Concept for Quantitative Spatial Analysis','Journal of Aging and Physical Activity','33','5','481','496',NULL,NULL,
  NULL,'10.1123/japa.2024-0121','40015287',NULL,NULL,'2026-07-25',3,'clinical','CA',
  'EN','EN','VERIFIED','RESOLVED','mcp__PubMed__get_article_metadata','2026-07-25','high',0,
  'Sought as a GAP-306 independence test and expected at best another self-report cohort. Instead it measures walking by GPS, so the bench association is observed against RECORDED ROUTES rather than recalled barriers - a methodologically independent line, not just a geographically independent one.',
  'benches AND neighborhood AND older adults walking (pubmed)',
  'Metadata re-retrieved from PubMed 2026-07-25; DOI and PMID confirmed.',
  'GAP-306 INDEPENDENCE EVIDENCE (Canada). n=25 people living with dementia, Metro Vancouver; GPS-recorded regular walking routes + GIS spatial analysis. "higher number of benches and intersections, and a slight street network curvature showed positive associations with RWR length and walking time to regular destination within the 20-min walkshed." Objective route measurement, not self-reported barrier perception. Authors flag it as exploratory and limited by participant numbers.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),

 ('REF-00956','journal_article','Maresova','Petra','Maresova P, Komarkova L, Horak J, Krejcar O, Kukuliac P, Vitkova L, Joukl M, Truhlarova Z, Tomsone S',2023,
  'Unveiling Seniors'' Perception of Mobility: Urbanization, Region, and Physical Activity','Patient Preference and Adherence','17',NULL,'3015','3031',NULL,NULL,
  NULL,'10.2147/PPA.S426789','38027077','PMC10675891',NULL,'2026-07-25',3,'clinical','CZ',
  'EN','EN','VERIFIED','RESOLVED','mcp__PubMed__get_article_metadata','2026-07-25','high',0,
  'Sought as a GAP-306 independence test. Did not expect a DISTRIBUTIONAL finding - that bench provision is itself unequally distributed rural vs urban - which reframes the gap as one of equity of provision, not only of adequacy.',
  'benches AND neighborhood AND older adults walking (pubmed)',
  'Metadata re-retrieved from PubMed 2026-07-25; DOI, PMID and PMCID confirmed.',
  'GAP-306 INDEPENDENCE EVIDENCE (Czech Republic; Latvian co-author). n=525, face-to-face and online questionnaire, ordinal regression. Treats benches as a named element of "urban scenes". Finding: "Substantially worse pedestrian conditions in availability of pedestrian crossings, benches, and lighting were recognized in rural municipalities versus cities." Bench provision is unequally distributed by degree of urbanisation - a distributional inequity distinct from the adequacy question.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),

 ('REF-00957','journal_article','Amaya','Valkiria','Amaya V, Moulaert T, Gwiazdzinski L, Vuillerme N',2022,
  'Assessing and Qualifying Neighborhood Walkability for Older Adults: Construction and Initial Testing of a Multivariate Spatial Accessibility Model','International Journal of Environmental Research and Public Health','19','3',NULL,NULL,'1808',NULL,
  NULL,'10.3390/ijerph19031808','35162830','PMC8834981',NULL,'2026-07-25',3,'clinical','FR',
  'EN','EN','VERIFIED','RESOLVED','mcp__PubMed__get_article_metadata','2026-07-25','high',0,
  'Sought as a GAP-306 independence test. Notable that public benches are one of only FOUR variables the model uses - a stronger status than "amenity" and consistent with the batch-1 position that rest provision is infrastructure, not decoration.',
  'benches AND neighborhood AND older adults walking (pubmed)',
  'Metadata re-retrieved from PubMed 2026-07-25; DOI, PMID and PMCID confirmed.',
  'GAP-306 INDEPENDENCE EVIDENCE (France, Grenoble conurbation). Multivariate spatial accessibility model built on FOUR independent variables, of which one is "public benches" (with pedestrian network; facilities and shops; slopes and gradients). Modelled across three older-adult profiles including "an older adult with reduced mobility". Exploratory model, two suburban neighbourhoods; no interval figure derived.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),

 ('REF-00958','journal_article','Leung','Ka-Man','Leung KM, Ou KL, Chung PK, Thogersen-Ntoumani C',2021,
  'Older Adults'' Perceptions toward Walking: A Qualitative Study Using a Social-Ecological Model','International Journal of Environmental Research and Public Health','18','14',NULL,NULL,'7686',NULL,
  NULL,'10.3390/ijerph18147686','34300136','PMC8303868',NULL,'2026-07-25',3,'clinical','HK',
  'EN','EN','VERIFIED','RESOLVED','mcp__PubMed__get_article_metadata','2026-07-25','high',0,
  'Sought as a GAP-306 independence test outside Europe and North America. Benches surface unprompted within a social-ecological framework, which is what a genuinely recurring demand should do.',
  'benches AND neighborhood AND older adults walking (pubmed)',
  'Metadata re-retrieved from PubMed 2026-07-25; DOI, PMID and PMCID confirmed.',
  'GAP-306 INDEPENDENCE EVIDENCE (Hong Kong). n=38 (19 women), mean age 72.8 (SD 7.4), semi-structured interviews, thematic coding in NVivo, social-ecological model. Benches named at the physical-environment level under "pedestrian facilities (benches, quality of walking paths and sidewalks, and aesthetics)". Qualitative; no interval figure.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),

 ('REF-00959','journal_article','Sallis','James','Sallis JF, Cain KL, Conway TL, Gavand KA, Millstein RA, Geremia CM, Frank LD, Saelens BE, Glanz K, King AC',2015,
  'Is Your Neighborhood Designed to Support Physical Activity? A Brief Streetscape Audit Tool','Preventing Chronic Disease','12',NULL,NULL,NULL,'E141',NULL,
  NULL,'10.5888/pcd12.150098','26334713','PMC4561538',NULL,'2026-07-25',3,'clinical','US',
  'EN','EN','VERIFIED','RESOLVED','mcp__PubMed__get_article_metadata','2026-07-25','high',0,
  'Sought as a GAP-306 independence test. The strongest form the evidence could take short of an interval trial: benches SURVIVED empirical item-selection into a validated 15-item instrument, across the largest sample in the batch. Still supplies no spacing figure, which sharpens rather than closes GAP-304.',
  'benches AND neighborhood AND older adults walking (pubmed)',
  'Metadata re-retrieved from PubMed 2026-07-25; DOI, PMID and PMCID confirmed.',
  'GAP-306 INDEPENDENCE EVIDENCE (US, multicenter). n=3,677 across four age groups (758 children, 897 adolescents, 1,655 younger adults, 367 older adults); MAPS-Mini distilled from the 120-item Microscale Audit of Pedestrian Streetscapes, correlating r=.85 with the full instrument; accelerometer plus survey outcomes. Benches were RETAINED through item selection on the basis of association with physical activity: "Items related to active transport in 3 age groups were presence of sidewalks, curb cuts, street lights, benches, and buffer between street and sidewalk." Presence only - the instrument records whether benches exist, not their spacing.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2');

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note) VALUES
 ('REF-00953','energy-conservation-rest-points-seating','ECR-09','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','Primary evidence that a single seat height cannot serve the population; armrests used 100% of the time when present.'),
 ('REF-00954','energy-conservation-rest-points-seating','ECR-10','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','Participatory national framework stating no interval; adds the visibility/anticipation requirement.'),
 ('REF-00955','energy-conservation-rest-points-seating','ECR-11','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','GPS-objective association between bench count and walking distance (Canada).'),
 ('REF-00956','energy-conservation-rest-points-seating','ECR-12','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','Rural municipalities substantially worse for bench availability (Czech Republic).'),
 ('REF-00957','energy-conservation-rest-points-seating','ECR-13','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','Public benches as one of four variables in a walkability accessibility model (France).'),
 ('REF-00958','energy-conservation-rest-points-seating','ECR-14','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','Benches named as pedestrian facility in a social-ecological qualitative study (Hong Kong).'),
 ('REF-00959','energy-conservation-rest-points-seating','ECR-15','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','Benches retained in a validated 15-item streetscape audit instrument, n=3,677 (US).');

-- ---------- search_executions (R8: verbatim, empties retained) ----------
INSERT INTO search_executions
 (slug, jurisdiction, language, target_tier, target_evidence_type, target_scope, query_text,
  engine, depth_method, mining_direction, results_found, results_screened, results_admitted,
  saturation_signal, admitted_ref_ids, deferred_reason, backfill, session, executed_at,
  findings_note, harm_finding)
VALUES
 ('energy-conservation-rest-points-seating','GB','EN',1,'co1','national',
  'Transport for All Are We There Yet 2023 highlights PDF - direct retrieval',
  'web','systematic','none',1,1,0,'none',NULL,NULL,0,'session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25',
  'R1 Co-1 pass, batch 2. LOCATOR BLOCKED, NOT ADMITTED. Three distinct retrieval routes were tried per the R10 ladder and ALL returned HTTP 403: the highlights PDF, the full report PDF (NATS_Full_PDF.pdf), and the HTML news page. transportforall.org.uk blocks this fetcher. A web-search summary asserted the organisation is disabled-led, but that is search-engine prose, not the source speaking, and batch 1 set the standard of verifying org status from the organisation own material (as was done for REF-00950). NOT admitted on secondary description. Candidate retained with the block documented so a later session with a different retrieval path can finish it rather than repeat the three failures.',0),

 ('energy-conservation-rest-points-seating','GB-SCT','EN',5,'national_fw','national',
  'Transport Scotland Inclusive Design in Town Centres Appendix C perspectives of disabled street users seating',
  'web','systematic','none',1,1,1,'saturated','["REF-00954"]',NULL,0,'session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25',
  'Resolved batch-1 candidate. KEY NEGATIVE: states NO interval and NO seat dimensions despite being participatory work with disabled street users - corroborates GAP-304. Also yielded a demand-layer requirement absent from both REF-00949 and REF-00950: seating must be visible from a distance and signposted so people can anticipate breaks and plan the journey.',0),

 ('energy-conservation-rest-points-seating','AU','EN',3,'clinical','lower_control',
  'Blackler seating aged care physical fit independence comfort',
  'pubmed','systematic','backward',1,1,1,'saturated','["REF-00953"]',NULL,0,'session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25',
  'R2 backward-mining lead from REF-00950 resolved. Highest-value single admission of the batch: supplies the primary evidence base for seat dimensions that batch 1 could only anchor on Co-1 against a T5 standard, and independently reaches the same plural-height conclusion. Contains the equity/harm finding recorded separately.',1),

 ('energy-conservation-rest-points-seating',NULL,'EN',3,'clinical','lower_control',
  'benches AND neighborhood AND older adults walking',
  'pubmed','systematic','forward',19,15,5,'partial','["REF-00955","REF-00956","REF-00957","REF-00958","REF-00959"]',NULL,0,'session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25',
  'THE GAP-306 INDEPENDENCE TEST, and it resolves the gap. Well-formed three-concept query (contrast with the 7-8 concept AND-chains that returned zero in batch 1). 19 records, 15 screened, 5 admitted from FIVE separate research groups in SIX countries - Canada, Czech Republic (Latvian co-author), France, Hong Kong, United States - none Finnish and none sharing authors with the Jyvaskyla cluster. Methods are also independent of each other: GPS route measurement, population survey with ordinal regression, formal spatial accessibility model, qualitative social-ecological interviews, and a validated audit instrument at n=3,677. The resting-places association is therefore NOT an artefact of one group or one cohort. Remaining 4 records unscreened, available to batch 3.',0),

 ('energy-conservation-rest-points-seating',NULL,'EN',3,'clinical','lower_control',
  'Inclusive Streetscapes Ulahannan disabled people lived experience street accessibility - direct retrieval',
  'web','scoping','none',1,1,0,'none',NULL,NULL,0,'session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25',
  'LOCATOR BLOCKED, NOT ADMITTED. sciencedirect.com returned HTTP 403 to this fetcher. Candidate retained as PENDING-VERIFICATION with the block recorded. Its batch-1 description remains an unconfirmed hypothesis: whether it addresses seating specifically is still NOT established, and must not be assumed from its title.',0),

 ('energy-conservation-rest-points-seating',NULL,'DE',NULL,NULL,NULL,
  'DEFERRED - no query executed',
  'manual','scoping',NULL,0,0,0,NULL,NULL,
  'Still deliberately not searched. term_aliases for this slug remain unbuilt, so a non-EN query would be back-translation (R11). Batch 2 spent its budget on resolving GAP-306 and the staged candidates; vocabulary build is queued for batch 3. Deferral, not absence.',0,
  'session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25',NULL,0);

-- ---------- R13 population grades on every tier-1..3 admission ----------
INSERT INTO evidence_population_match
 (match_id, source_ref, ref_id, target_population, study_population, sample_size,
  match_grade, mismatch_note, gap_id, created_at, created_by_session)
VALUES
 ('EPM-00953-A','REF-00953','REF-00953','MOB','19 residential aged-care residents (6M/13F) plus 5 staff and 2 clinicians, Queensland Australia; selected BY facility staff, researchers not permitted to approach residents directly',19,
  'PARTIAL','Study population is institutional aged-care residents, not disabled people as such, so PARTIAL not EXACT. It is closer than a general older cohort because the observed task - sit-to-stand transfer - IS the served demand. Two caveats recorded rather than smoothed: facility-gatekept selection, and the authors note the sample is not representative of aged care generally in anthropometrics, abilities or attitudes.',NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),
 ('EPM-00955-A','REF-00955','REF-00955','DEM','25 people living with dementia, Metro Vancouver',25,
  'PARTIAL','Population of study is people living with dementia; the bench finding is about sustained-exertion demand, which this cohort has alongside orientation demand. PARTIAL - the association is credible for the served demand but was not measured on it in isolation.',NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),
 ('EPM-00956-A','REF-00956','REF-00956','MOB','525 community-dwelling seniors, Czech Republic, urban and rural',525,
  'PROXY','General senior population, not selected for disability or mobility limitation. PROXY. The finding used from this source is DISTRIBUTIONAL (rural areas have substantially worse bench availability), which transfers across populations more readily than an effect estimate would.',NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),
 ('EPM-00957-A','REF-00957','REF-00957','MOB','Modelled profiles, not enrolled participants: three older-adult profiles including one with reduced mobility, two suburban Grenoble neighbourhoods',NULL,
  'PROXY','No participants - a spatial model. Graded PROXY per the rule that a source with no participants is PROXY at best. It does explicitly model "an older adult with reduced mobility", so the served demand is represented in the model even though nobody was studied.',NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),
 ('EPM-00958-A','REF-00958','REF-00958','MOB','38 older adults (19 women), mean age 72.8 (SD 7.4), Hong Kong; 47% recruited from private elderly centres',38,
  'PROXY','General older-adult cohort not selected for disability. PROXY. Value is corroborative and geographic (non-Western setting), not parameter-setting.',NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2'),
 ('EPM-00959-A','REF-00959','REF-00959','ALL','3,677 across four age groups (758 children, 897 adolescents, 1,655 younger adults, 367 older adults), US multicenter',3677,
  'PROXY','General-population instrument-validation sample spanning children to older adults, NOT a disabled cohort - PROXY per the rule that general-population and child samples are PROXY. Target recorded as ALL rather than a specific code because the instrument is population-agnostic. Its evidential weight here is that benches survived empirical item selection, not that it measures the served population.',NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2');

-- ---------- R15: resolved candidates re-described FROM THE SOURCE ----------
UPDATE search_candidates SET
  disposition='ADMITTED', locator_status='RESOLVED', tier_guess=3,
  locator='10.1177/2050312117744925',
  notes='RESOLVED 2026-07-25 and RE-DESCRIBED FROM THE SOURCE (R15). Batch-1 hypothesis was "may be the only primary basis for the seat-dimension figures". That was RIGHT but UNDER-claimed: it does not merely supply dimensions, it demonstrates the dimensions cannot be single-valued. Admitted as REF-00953.',
  why_not_admitted=NULL, session='session_2026-07-25-energy-conservation-rest-points-seating-b2'
WHERE candidate_id=17;

UPDATE search_candidates SET
  disposition='ADMITTED', locator_status='RESOLVED',
  notes='RESOLVED 2026-07-25 and RE-DESCRIBED FROM THE SOURCE (R15). Batch-1 hypothesis said the snippet "suggests it recommends regular rest locations with a variety of seating options" and asked whether it states an interval. CORRECTION: it states NO interval and NO dimensions. My staged description also implied a richer specification than the source carries. What it does add, which I did not anticipate, is the visibility/anticipation requirement. Admitted as REF-00954.',
  why_not_admitted=NULL, session='session_2026-07-25-energy-conservation-rest-points-seating-b2'
WHERE candidate_id=16;

UPDATE search_candidates SET
  locator_status='DEAD',
  why_not_admitted='R10 ladder exhausted this batch: three distinct routes (highlights PDF, full NATS_Full_PDF.pdf, HTML news page) ALL returned HTTP 403 from transportforall.org.uk. Not admitted on secondary description - a search-engine summary calling the org disabled-led is not the source speaking.',
  notes='STILL A HYPOTHESIS (R15) - do not let the batch-1 guess harden. Whether this report addresses seating or rest points at all remains UNKNOWN. locator_status set DEAD to record the block, not to close the lead: a session with a different retrieval path should retry. Its Co-1 status must be verified from Transport for All own material before any tier is assigned, as was done for REF-00950.',
  session='session_2026-07-25-energy-conservation-rest-points-seating-b2'
WHERE candidate_id=15;

UPDATE search_candidates SET
  locator_status='DEAD',
  why_not_admitted='sciencedirect.com returned HTTP 403 to this fetcher on direct retrieval. No DOI was available from the Consensus record that surfaced it, so the locator ladder has no next rung from here without a DOI.',
  notes='STILL A HYPOTHESIS (R15). Batch-1 description (26 UK interviews on streetscape barriers) came from a Consensus abstract, not the source. Whether it addresses SEATING specifically is still NOT established and must not be inferred from the title. Next step for a later batch: resolve a DOI via Crossref, then re-attempt.',
  session='session_2026-07-25-energy-conservation-rest-points-seating-b2'
WHERE candidate_id=13;

-- ---------- GAP-306 CLOSED; GAP-304 sharpened; new gaps ----------
UPDATE gaps SET
  status='CLOSED-RESOLVED',
  description=description || ' || CLOSED 2026-07-25 (batch 2). Independence CONFIRMED, gap does not hold. Five independent groups in six countries associate rest/bench provision with walking outcomes, none Finnish and none sharing authors with the Jyvaskyla cluster: REF-00955 (CA, GPS-measured routes), REF-00956 (CZ, n=525 survey), REF-00957 (FR, spatial accessibility model), REF-00958 (HK, qualitative), REF-00959 (US, n=3,677, benches retained through empirical item selection into a validated instrument). The methods are independent of one another as well as the authors, so this is not one finding echoed five times.',
  updated_at='2026-07-25', updated_by_session='session_2026-07-25-energy-conservation-rest-points-seating-b2'
WHERE gap_id='GAP-306';

UPDATE gaps SET
  description=description || ' || SHARPENED 2026-07-25 (batch 2), still OPEN and now better evidenced as a real hole. Six further sources were read (REF-00953..00959) including a participatory national framework (REF-00954) and a validated US instrument at n=3,677 (REF-00959). NOT ONE states a spacing figure. REF-00954 declines to give a number even though disabled street users were consulted directly; REF-00959 records bench PRESENCE only. So bench presence is repeatedly and independently associated with walking outcomes, while the INTERVAL remains unmeasured by anyone. The 50m figure is not merely under-evidenced - the entire literature that supports rest provision is silent on spacing.',
  updated_at='2026-07-25', updated_by_session='session_2026-07-25-energy-conservation-rest-points-seating-b2'
WHERE gap_id='GAP-304';

INSERT INTO gaps (gap_id, category, priority, status, skill, section, description,
                  falsification_condition, created_at, created_by_session,
                  updated_at, updated_by_session, mining_addressability)
VALUES
 ('GAP-307','EG','P1','OPEN','item-specification-writer','energy-conservation-rest-points-seating',
  'SINGLE-HEIGHT SEATING IS AN EQUITY HARM AND THE STANDARD ENCODES IT. REF-00953 audited 410-505mm seat heights across facilities and 423-510mm across suppliers and found NONE would fit a 5th-percentile older Australian female (popliteal height 330mm vs population mean 379mm). The consequence is not discomfort alone: "shorter residents are being disadvantaged compared with taller ones, suffering discomfort and possible musculoskeletal damage while sitting and being put at risk of deep venous thrombosis (DVT) due to the seating design", and the harm is GENDERED because women are 69% of permanent aged care in Australia and are likelier to be shorter. UK DfT Inclusive Mobility p.102 specifies a single 470-480mm band for the majority of seats, which sits inside the range REF-00953 found excludes short users. The Co-1 source REF-00950 independently specifies plural heights (380/480/580mm). Best practice for this slug should therefore be a RANGE of heights per location, not a single value.',
  'Falsified if a study finds a single seat height that accommodates sit-to-stand for low-strength users AND seated comfort for 5th-percentile stature simultaneously, or if the DVT/musculoskeletal harm attributed to over-high seating fails to replicate.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','ADDRESSABLE'),

 ('GAP-308','EG','P2','OPEN','multilingual-research','energy-conservation-rest-points-seating',
  'REST POINTS MUST BE ANTICIPATABLE, AND NO SPECIFICATION CAPTURES THIS. REF-00954 records disabled street users requiring that seating "be positioned so that it is possible to see from a distance i.e. to allow journey planning" and be "clearly signposted ... to allow them to know when to anticipate potential for breaks in their journey". Neither REF-00949 (DfT) nor REF-00950 (Wheels for Wellbeing) specifies visibility, sightline or signage of rest points; both specify only provision and setback. A rest point that cannot be seen or anticipated does not support the decision to ATTEMPT the journey, so provision alone under-specifies the demand. No parameter exists anywhere in the corpus for rest-point visibility or wayfinding.',
  'Falsified if a standard or primary study is found specifying sightline, visibility distance or signage requirements for rest points.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','ADDRESSABLE'),

 ('GAP-309','RP','P3','OPEN','citation-verifier','energy-conservation-rest-points-seating',
  'TWO SLUG-RELEVANT SOURCES ARE LOCATOR-BLOCKED TO THIS TOOLCHAIN. Transport for All "Are We There Yet?" (2023) returned HTTP 403 on all three routes tried (highlights PDF, full PDF, HTML news page); Ulahannan et al. "Inclusive Streetscapes" returned HTTP 403 from sciencedirect.com and has no DOI recorded from the engine that surfaced it. Both are potentially Co-1 or Co-1-adjacent UK lived-experience sources, i.e. exactly the evidence class this slug is thinnest in - the slug currently holds ONE Co-1 source. Neither may be admitted on secondary description.',
  'Falsified when either source is retrieved through any working route and re-described from the source itself.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','ADDRESSABLE');

-- ---------- R2 citation mining register ----------
UPDATE citation_mining SET
  forward=1, connections_produced=5, deferred_reason=NULL,
  notes='FORWARD MINING EXECUTED 2026-07-25 (batch 2) - this was batch 1 highest-value deferred target and it resolved GAP-306. Rather than walking citations one by one, the independence question was attacked directly with a well-formed topical query designed to surface groups OTHER than the Finnish cluster. 5 connections produced (REF-00955..00959) across six countries and five distinct methods. Deliberate design point: an adversarial construction was preferred to a citation walk precisely because a citation walk from a Finnish-cluster paper tends to return the same cluster. Supersedes the batch-1 deferral on this row.',
  updated_at='2026-07-25', updated_by_session='session_2026-07-25-energy-conservation-rest-points-seating-b2'
WHERE slug='energy-conservation-rest-points-seating' AND local_ref_id='ECR-03';

INSERT INTO citation_mining
 (slug, local_ref_id, global_ref_id, doi, backward, forward, connections_produced, notes,
  created_at, created_by_session, updated_at, updated_by_session, deferred_reason)
VALUES
 ('energy-conservation-rest-points-seating','ECR-09','REF-00953','10.1177/2050312117744925',1,0,0,
  'BACKWARD MINING PARTIAL. Its literature review was read closely and yields named further anchors - Christenson (380-457mm variety recommendation), Holden and Fernie (armrest 730mm from floor, 250mm above seat, 120mm width), Kothiyal and Tettey (seat depth 376mm), Scarborough et al. (chair-rise strategies), and the Australian Standard for fixed-height chairs (380-480mm effective seat depth). NONE resolved to a locator this batch, so 0 connections produced rather than counting them as found. These are the batch-3 backward queue and are the likeliest route to a primary derivation for the dimensional figures.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2',NULL),
 ('energy-conservation-rest-points-seating','ECR-15','REF-00959',NULL,0,0,0,NULL,
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2',
  'DEFERRED WITH REASON. REF-00959 (MAPS-Mini) is highly cited and its forward graph is large, but it is an instrument-validation paper: forward citations will mostly be studies USING the instrument rather than studies measuring rest-point spacing. Mining it would produce volume without addressing GAP-304. Queued behind the REF-00953 backward leads, which bear directly on the open dimensional question.'),
 ('energy-conservation-rest-points-seating','ECR-10','REF-00954',NULL,1,0,0,NULL,
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating-b2',
  'DEFERRED WITH REASON. Appendix C is one appendix of a larger Transport Scotland publication; the parent report and its other appendices were not enumerated this batch. Worth a targeted pass in batch 3 since the parent may carry the specification detail the appendix omits - including, possibly, the interval figure the appendix declines to state.');


-- Closing a research gap requires the full protocol field set, not just a falsification
-- condition (research_protocol_audit CHECK 1). Recording what would shift the conclusion and
-- who could reasonably dissent is the point of closing a gap rather than deleting it.
UPDATE gaps SET
  confidence_interval='80-90%',
  shift_conditions='The 80-90% is confidence that the association is not an artefact of ONE research group; it is NOT a claim about effect magnitude, which none of these sources was designed to estimate and which this closure does not assert. Would reopen if the independent sources were found to share an unrecognised common origin (e.g. all deriving their bench variable from one prior instrument), or if a well-powered study found no association between rest provision and walking outcomes in a population with elevated sustained-exertion demand.',
  named_dissenter='No source located disputes the association. The honest counterweight is internal: REF-00955 is n=25 and self-described as exploratory, REF-00958 is n=38 qualitative, and REF-00957 enrolled no participants at all - so breadth of replication is doing the work here, not depth of any single study. A reviewer could fairly argue that five weak-to-moderate studies agreeing is weaker than it looks; the response is that they agree across methods that fail in different directions.',
  updated_at='2026-07-25', updated_by_session='$S'
WHERE gap_id='GAP-306';

INSERT INTO evidence_population_match
 (match_id, source_ref, ref_id, target_population, study_population, sample_size,
  match_grade, mismatch_note, gap_id, created_at, created_by_session)
VALUES
 ('EPM-00954-A','REF-00954','REF-00954','MOB','Focus groups of disabled street users structured by impairment type (hearing impaired, visually impaired, deafblind, mobility impaired, learning/non-visible); participant count NOT STATED in the source',NULL,
  'PARTIAL','Participants are disabled people consulted directly, so the served population is well represented in kind. Graded PARTIAL rather than EXACT for two reasons recorded rather than smoothed: the source does not state how many people took part, and the groups span impairment types well beyond the sustained-exertion demand this slug serves.',NULL,
  '2026-07-25','$S');

COMMIT;
