-- data_20260720012443_2026-07-20-poe-global-multilingual-research.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-20-poe-global-multilingual-research.md
-- Generated:  2026-07-20T01:24:43+00:00
-- Summary:    WS2: first evidence pass for empty slice post-occupancy-evaluation-global — 10 sources across 7+ jurisdictions/authorship-homes (CY, UK, AU, IT, BR x2, US, KR, INT-Africa11), including a native-Korean-language source, verified via WebSearch/PubMed cross-corroboration
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- WS2 (evidentiary-base-research-plan-2026-07-19): first evidence pass for the
-- genuinely un-started, empty slice post-occupancy-evaluation-global (STUB/NOT-RUN,
-- 0 source_slug_links, bpc_metadata.jurisdictions_searched=0 prior to this migration).
-- Multilingual/multi-jurisdictional research pass: searched DE/NL/JA/FR/NO-SE/KO/PT
-- native-language terms plus English-language academic databases (Consensus/PubMed).
-- 10 sources ingested, each verified via a real tool call (WebSearch title/DOI
-- cross-corroboration; Lolli et al. additionally confirmed via PubMed
-- get_article_metadata, PMID 36287906). No source ingested without independent
-- re-retrieval confirming title+venue+author. Spans 6 jurisdictions/authorship homes
-- (CY, UK, AU, IT, BR, KR, US) plus 2 multi-country syntheses (INT/Brazil-inclusive
-- SLR; INT/11-country pan-African SLR) — deliberately diluting the corpus's existing
-- English/Anglophone concentration per WS3. One source (Lee & Kwon 2011) is natively
-- Korean-language, disclosed as lang_detected='ko'; DE/JA/KO leads surfaced during
-- search (nullbarriere.de, ecomo.or.jp barrier-free evaluation manual, KCI/AURIC POE
-- literature, KAKEN "Japanese-style POE" grant project) could not be independently
-- confirmed to primary-document level this session (WebFetch returned garbled/binary
-- content for the two PDFs attempted) and are recorded as follow-up leads in
-- working/evidence-migration/, not ingested — per the anti-fabrication gate.

INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete, first_author_last, first_author_first,
    is_corporate_primary, author_display, pub_year, pub_title, journal_name, volume, issue, pages_start, pages_end,
    language, lang_detected, lang_detection_method, tier, evidence_type, jurisdiction, doi, pmid, pmcid, url,
    metadata_quality, verification_status, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
) VALUES

('REF-00867', 'journal_article', 2, 1, 'Güvenbaş', 'Gizem', 0, 'Güvenbaş G, Polay M',
 2020, 'Post-occupancy evaluation: A diagnostic tool to establish and sustain inclusive access in Kyrenia Town Centre',
 'Indoor and Built Environment', '30', '9', '1620', '1642',
 'en', 'en', 'native_english', 3, 'clinical', 'CY', '10.1177/1420326X20951244', NULL, NULL, 'https://doi.org/10.1177/1420326X20951244',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via 2 independent WebSearch corroborations (Consensus.app abstract + SAGE journals listing journals.sagepub.com/doi/10.1177/1420326X20951244) — title, authors, journal, DOI, and pagination all cross-confirmed. Not independently WebFetched (SAGE paywall). Survey (n=383) + systematic behavioural-mapping observation (n=1620) of physical/social barriers for disabled and non-disabled users in Kyrenia Town Centre, Northern Cyprus/Turkish-administered Cyprus — new jurisdiction for this corpus.',
 'Consensus.app search "post-occupancy evaluation accessibility built environment disability users" -> WebSearch DOI corroboration.',
 'First source for post-occupancy-evaluation-global. Applies POE methodology (survey + behavioural mapping) specifically to test inclusive-access outcomes in an urban town-centre retrofit; jurisdiction note: Kyrenia is in the Turkish Republic of Northern Cyprus (TRNC), a jurisdiction not internationally recognised outside Turkey — tagged CY per the paper''s own "Northern Cyprus" framing, flagged here for any downstream jurisdiction-count work.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00868', 'journal_article', 2, 1, 'Zallio', 'Matteo', 0, 'Zallio M, Clarkson PJ',
 2022, 'The Inclusion, Diversity, Equity and Accessibility audit. A post-occupancy evaluation method to help design the buildings of tomorrow',
 'Building and Environment', '217', NULL, '109058', NULL,
 'en', 'en', 'native_english', 3, 'clinical', 'UK', '10.1016/j.buildenv.2022.109058', NULL, NULL, 'https://doi.org/10.1016/j.buildenv.2022.109058',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via WebSearch cross-corroboration (ScienceDirect pii S0360132322002979, University of Cambridge repository record, ResearchGate) — title, authors, journal, volume, article number all match. Multi-round Delphi study (University of Cambridge Engineering Design Centre) co-designing the "IDEA audit," a named POE instrument for inclusion/diversity/equity/accessibility feedback. Tiered T3 (primary consensus-method-development research), not T2, since it is a Delphi study establishing a new tool rather than a systematic review or a named-organisation standard per governance/tier-system.md §1.',
 'WebSearch "Zallio Clarkson IDEA audit post-occupancy evaluation Building and Environment 2022 doi".',
 'Names and operationalises a POE method specific to accessibility/inclusion (the IDEA audit) — directly on-topic for this slice''s methodology scope.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00869', 'journal_article', 2, 1, 'Zallio', 'Matteo', 0, 'Zallio M, Clarkson PJ',
 2021, 'Inclusion, diversity, equity and accessibility in the built environment: A study of architectural design practice',
 'Building and Environment', '206', NULL, '107496', NULL,
 'en', 'en', 'native_english', 3, 'clinical', 'UK', '10.1016/j.buildenv.2021.107496', NULL, NULL, 'https://doi.org/10.1016/j.buildenv.2021.107496',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via WebSearch cross-corroboration (ScienceDirect pii S0360132321007496 matches DOI). Ethnographic study of 26 building-industry professionals on Inclusive Design adoption; identifies POE user-feedback collection as a named strategy professionals underuse.',
 'WebSearch DOI corroboration alongside REF-00868 (same author pair, companion paper).',
 'Companion/precursor paper to REF-00868 (IDEA audit); provides the practice-adoption context (why POE-for-accessibility is under-used) that motivates the IDEA audit method.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00870', 'journal_article', 3, 1, 'Newton', 'Sidney', 0, 'Newton S, Carnemolla P, Darcy S',
 2023, 'Building information modelling and related technologies applied to the post occupancy evaluation of accessible bathrooms for people with disability',
 'Smart and Sustainable Built Environment', '14', '1', '237', '253',
 'en', 'en', 'native_english', 3, 'clinical', 'AU', '10.1108/SASBE-04-2023-0075', NULL, NULL, 'https://doi.org/10.1108/SASBE-04-2023-0075',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via WebSearch cross-corroboration (Emerald abstract page, ResearchGate preprint) — title, authors, journal, volume/issue/pages match; ahead-of-print 2023, formally issued in vol 14 no 1 (2025). Field study evaluating 21 accessible bathrooms across 3 Sydney university buildings using a BIM-integrated POE checklist; identifies specific high-risk recurring failures (toilet-roll placement, entrance door hardware/security, approach hazards).',
 'WebSearch "Newton post occupancy evaluation accessible bathrooms disability Smart and Sustainable Built Environment doi".',
 'Concrete, instrumented POE methodology applied specifically to an accessible-design element (bathrooms); gives the slice a T3 primary-empirical anchor distinct from the UK/Delphi-method sources.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00871', 'journal_article', 2, 1, 'Fu', 'Elisabeth Yang Nan', 0, 'Fu EYN, Ornstein S',
 2021, 'Accessibility, ergonomics and functionality of museum environments: a systematic literature review considering integrated evaluation processes',
 'Architecture, Structures and Construction', NULL, NULL, NULL, NULL,
 'en', 'en', 'native_english', 2, 'sr_meta', 'BR', '10.1007/s44150-021-00013-w', NULL, NULL, 'https://doi.org/10.1007/s44150-021-00013-w',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via WebSearch cross-corroboration (Springer article page confirms DOI; authors Elisabeth Yang Nan Fu and Sheila Ornstein, University of São Paulo, confirmed via independent WebSearch). Systematic literature review of POE + Ergonomic Methodology of the Built Environment (EMBE) studies in museum settings, illustrated via the Museu da Imagem e do Som (MIS), São Paulo. Tiered T2 per governance/tier-system.md §1-2 (systematic review of primary POE/accessibility studies).',
 'WebSearch "Fu Accessibility ergonomics functionality museum environments systematic literature review doi" + author-confirmation follow-up search.',
 'First T2 (sr_meta) anchor for this slice — a genuine systematic review of POE-accessibility methodology, authored from a Brazilian institution (USP), diluting the corpus''s Anglophone concentration per WS3.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00872', 'journal_article', 4, 1, 'Lolli', 'Francesco', 0, 'Lolli F, Marinello S, Coruzzolo AM, Butturi MA',
 2022, 'Post-Occupancy Evaluation''s (POE) Applications for Improving Indoor Environment Quality (IEQ)',
 'Toxics', '10', '10', '626', NULL,
 'en', 'en', 'native_english', 2, 'sr_meta', 'IT', '10.3390/toxics10100626', '36287906', 'PMC9607023', 'https://doi.org/10.3390/toxics10100626',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via PubMed get_article_metadata (PMID 36287906, PMC9607023, DOI 10.3390/toxics10100626): article_types = Journal Article + Review; authors and University of Modena and Reggio Emilia (Italy) affiliation confirmed directly from PubMed metadata, not just WebSearch. Review of 234 POE articles (2006-2022) on indoor environmental quality methodology; general-POE (not disability-specific) but the corpus''s primary current review of POE-methodology breadth/practice, useful as a methodology cross-reference for the slice.',
 'PubMed PMID 36287906 -> get_article_metadata; tier per governance/tier-system.md (review = T2 sr_meta).',
 'General (not disability-specific) POE-methodology review; cite for methodology/practice context only, not as a disability-specific best-practice anchor on its own — flagged so downstream synthesis does not overstate its applicability.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00873', 'journal_article', 2, 1, 'Zimring', 'Craig', 0, 'Zimring CM, Reizenstein JE',
 1980, 'Post-Occupancy Evaluation: An Overview',
 'Environment and Behavior', '12', '4', '429', '450',
 'en', 'en', 'native_english', 3, 'clinical', 'US', NULL, NULL, NULL, NULL,
 'PARTIAL', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via 2 independent WebSearch corroborations (ProQuest openview listing + multiple secondary citations giving identical volume/issue/pages). No DOI located — the article predates DOI assignment convention for this era of Sage journals; this is disclosed, not fabricated. Foundational definitional/framework paper establishing POE as a field (not disability-specific).',
 'WebSearch "Zimring Reizenstein Post-occupancy evaluation An overview Environment and Behavior 1980 doi".',
 'Foundational/definitional citation only — establishes what POE is and the three dimensions (generality, breadth, applicability) used to classify POE studies; not disability-specific, so flagged as framework/supporting evidence, not a best-practice anchor on its own.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00874', 'conference_paper', 10, 1, 'Vizioli', 'Simone Helena Tanoue', 0,
 'Vizioli SHT, Merighi JV, Fortes RM, Uddin W, Azevedo MC, Bruna GC, Ricci E, Rodrigues Filho S, Pisani MAJ, Pisani A',
 2003, 'Indicative Post-Occupancy Evaluation (POE) Focusing the Wheelchair Disabled User: A Case Study — The Airports of Congonhas (Sao Paulo) and Cumbica (Guarulhos)',
 'Conferência Internacional 2003 — Aeroportos: Planejamento, Infra-estrutura e Meio Ambiente (International Conference — Airports: Planning, Infrastructure and Environment)', NULL, NULL, NULL, NULL,
 'en', 'en', 'native_english', 3, 'clinical', 'BR', NULL, NULL, NULL, NULL,
 'PARTIAL', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via WebSearch cross-corroboration (Consensus.app abstract; author biography pages for Vizioli and Merighi confirming institutional affiliation and the paper''s existence within this 2003 conference). No DOI/persistent URL located for this pre-DOI-era Brazilian conference proceedings paper — disclosed, not fabricated. Full 10-author list assembled from a secondary WebSearch pass; author_count_is_complete=1 reflects that the assembled list matches across 2 independent sources but the original programme/proceedings itself was not directly opened.',
 'WebSearch "Indicative Post-Occupancy Evaluation wheelchair Congonhas Cumbica airport 2003 conference proceedings" + follow-up author-list search.',
 'Early (2003) wheelchair-user-focused POE case study of two major Brazilian international airports; walkthrough + behavioural-mapping + interview methodology. Genuinely Global-South-originated primary evidence, not a relink of an existing English-Anglophone source.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00875', 'journal_article', 2, 1, 'Lee', 'Yong-Min', 0, '이용민 (Lee Yong-Min), 권오정 (Kwon Oh-Jung)',
 2011, '국내 거주 후 평가(POE) 연구동향분석과 발전방안 연구',
 '한국실내디자인학회 논문집 (Journal of the Korean Institute of Interior Design)', '20', '3', '41', '48',
 'ko', 'ko', 'native_korean', 3, 'grey', 'KR', NULL, NULL, NULL, NULL,
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via WebSearch cross-corroboration (AURIC, DBpia, KCI, and koreascience.kr all independently list matching title/authors/journal/volume/issue/pages). Direct WebFetch of the KCI record returned HTTP 503 this session; not independently rendered. Trend-analysis review of 55 Korean POE studies published 1990-2010, tracing the historical development and methodological gaps of domestic (Korean) POE research in architecture/interior-design fields. Not disability-specific.',
 'WebSearch "국내 거주 후 평가 POE 연구동향분석 저자 발행연도 학회지" — native-Korean-script query per multilingual-research protocol Step 1.',
 'The slice''s first native-Korean-language source (lang_detected=ko, not a back-translated or re-tagged English source) — a genuine non-English-language methodology reference per WS3''s equity mandate. General-POE trend review, not disability-specific; cite for KR-native methodology terminology/practice context, not as a best-practice anchor.',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research'),

('REF-00876', 'journal_article', 3, 1, 'Attakora-Amaniampong', 'Emmanuel', 0, 'Attakora-Amaniampong E, Appau MW, Anugwo IC',
 2026, 'Institutionalizing post-occupancy evaluation in African universities: a framework for student-centered housing governance',
 'Facilities', '44', '1-2', '27', '43',
 'en', 'en', 'native_english', 2, 'sr_meta', 'INT', '10.1108/F-03-2025-0055', NULL, NULL, 'https://doi.org/10.1108/F-03-2025-0055',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-20-poe-global-multilingual-research] Verified via WebSearch cross-corroboration (Emerald Publishing article page confirms title, authors, journal, volume/issue/pages, DOI). Systematic review of 25 empirical POE studies published 2020-2024 spanning 11 African countries; finds POE in African university student housing is fragmented, largely academic, and not institutionalised into governance/decision-making. Tiered T2 (systematic review).',
 'WebSearch "Institutionalizing post-occupancy evaluation in African universities student-centered housing governance Facilities Emerald authors doi".',
 'The slice''s first Global-South-region systematic-review anchor (11-country pan-African synthesis, published 2026) — directly addresses this project''s own equity mandate (WS3) by sourcing a genuine non-Anglophone-region synthesis rather than relying on Global-North POE literature alone. Jurisdiction tagged INT (multi-country synthesis, not a single national regime) per the corpus''s existing convention for multi-national syntheses (e.g. REF-00039, REF-00040).',
 '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research');

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note) VALUES
('REF-00867', 'post-occupancy-evaluation-global', 'POE-1', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'POE methodology (survey + behavioural mapping) applied to inclusive-access outcomes; Northern Cyprus.'),
('REF-00868', 'post-occupancy-evaluation-global', 'POE-2', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'Names and operationalises the IDEA audit, a POE instrument specific to inclusion/diversity/equity/accessibility.'),
('REF-00869', 'post-occupancy-evaluation-global', 'POE-3', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'Practice-adoption context motivating POE-for-accessibility (companion to REF-00868).'),
('REF-00870', 'post-occupancy-evaluation-global', 'POE-4', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'BIM-instrumented POE field study of 21 accessible bathrooms; Australia.'),
('REF-00871', 'post-occupancy-evaluation-global', 'POE-5', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'First T2 systematic-review anchor; Brazilian-authored (USP), museum-setting POE/accessibility SLR.'),
('REF-00872', 'post-occupancy-evaluation-global', 'POE-6', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'Broad POE-methodology review (234 articles); Italy-authored; general, not disability-specific — methodology cross-reference only.'),
('REF-00873', 'post-occupancy-evaluation-global', 'POE-7', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'Foundational/definitional POE framework paper; not disability-specific — framework citation only.'),
('REF-00874', 'post-occupancy-evaluation-global', 'POE-8', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'Wheelchair-user POE case study, 2 major Brazilian airports (2003) — Global-South primary evidence.'),
('REF-00875', 'post-occupancy-evaluation-global', 'POE-9', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', 'Native-Korean-language POE research-trend review — genuine non-English-language source (lang_detected=ko).'),
('REF-00876', 'post-occupancy-evaluation-global', 'POE-10', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '2026-07-20T01:23:11Z', 'session_2026-07-20-poe-global-multilingual-research', '11-country pan-African systematic review of student-housing POE — Global-South synthesis anchor.');

COMMIT;
