-- data_20260812051219_2026-08-12-commit-91-review-and-corridor-walk.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-12-commit-91-review-and-corridor-walk.md
-- Generated:  2026-08-12T05:12:19+00:00
-- Summary:    clear all evidence-stage data; schema and connectivity preserved for repopulation
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Clear all evidence-stage data. Owner ruling 2026-08-12: starting fresh for
-- research content. SCHEMA AND CONNECTIVITY ARE PRESERVED — these tables will be
-- repopulated by the pipeline, so every column, FK and constraint stays.
-- All statements are guarded, so re-application is a no-op.

-- 1. Synthesis output: per-(item x population) prose variants.
--    3 rows (E-12, G-08, G-09; all MOB; all evidence_ref_id NULL), carrying
--    determinations such as "~1700mm vs 1500mm". This is the class the
--    2026-08-06 clean-room reset existed to clear, and it survived.
DELETE FROM item_population_elaborations;

-- 2. Evidence-stage operational ledgers. Their counters report 225 resolved DOIs
--    and 410 verified URLs against evidence_sources, which now holds 0 rows.
DELETE FROM pipeline_runs;
DELETE FROM url_verification_runs;

-- 3. Progressive Measurement Protocol walk residue on the frame table (A-02,
--    A-08, B-01, A-18). Columns retained: the protocol will run again.
UPDATE items
   SET pmp_delta_min = NULL, pmp_direction = NULL, pmp_last_walk_at = NULL,
       pmp_empirical_ceiling = NULL, pmp_gap_signed = NULL
 WHERE pmp_delta_min IS NOT NULL OR pmp_direction IS NOT NULL
    OR pmp_last_walk_at IS NOT NULL OR pmp_empirical_ceiling IS NOT NULL
    OR pmp_gap_signed IS NOT NULL;

-- 4. jurisdictional_values retired to reference-only (owner ruling 2026-08-12):
--    the sourcing triple (item_code, jurisdiction, standard_name) is retained to
--    support search terminology and document sourcing. Every claimed value is
--    cleared. These 109 rows were a machine parse of
--    parts/v10/appendix-a-jurisdiction-comparison.md -- a file that no longer
--    exists -- with created_by_session NULL on all 109, zero evidence links, and
--    a verification checklist that was never ticked. source_section held A.1-A.20,
--    the project's own appendix numbers, not clause locators into any standard.
--    NOTE: evidence_tier is INTEGER NOT NULL DEFAULT 6 and cannot be nulled; it
--    is left at its default and carries no meaning after this clear.
UPDATE jurisdictional_values
   SET value_text = NULL, value_numeric = NULL, unit = NULL,
       is_code_minimum = NULL, source_section = NULL, notes = NULL, spec_id = NULL
 WHERE value_text IS NOT NULL OR value_numeric IS NOT NULL OR unit IS NOT NULL
    OR is_code_minimum IS NOT NULL OR source_section IS NOT NULL
    OR notes IS NOT NULL OR spec_id IS NOT NULL;

-- 5. Evidence content stored on a frame table: item_axis_links row E-08/AX-BAL
--    carried a 1,093-character evidence synthesis (fall rate 0.81 CI 0.68-0.97;
--    900-1000 mm height, 32-51 mm section; REF-00911/00912/00913/00792/00883/
--    00921) and asserted "registered as GAP-300 (P2, OPEN), with GAP-301" while
--    the gaps table holds 0 rows.
UPDATE item_axis_links
   SET mechanism_note = NULL
 WHERE item_code = 'E-08' AND axis_code = 'AX-BAL'
   AND mechanism_note IS NOT NULL AND length(mechanism_note) > 500;

-- 6. AUTOINCREMENT high-water marks left behind by the reset (author rows 1273,
--    extractions 8, elaborations 7). A true fresh start restarts the counters.
DELETE FROM sqlite_sequence
 WHERE name IN ('evidence_source_authors','source_value_extractions',
                'item_population_elaborations');

COMMIT;
