-- data_20260719192523_2026-07-19-non-english-research-recovery-batch8.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-non-english-research-recovery-batch8.md
-- Generated:  2026-07-19T19:25:23+00:00
-- Summary:    Fix 3 Chinese-mislabeled-as-Japanese lang_detected rows + 1 jurisdiction typo; relink 4 already-verified sources onto the 2 untouched Tier-2 stub-notes slugs (cognitive-wayfinding-design, accessible-circulation-geometry)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- =====================================================================
-- Part A: lang_detected / jurisdiction hygiene fixes, found while
-- researching cognitive-wayfinding-design (the same unicode_block
-- Chinese-hanzi-misread-as-Japanese bug documented and fixed in earlier
-- batches -- these 3 rows were missed because they sit outside the
-- slugs those earlier sweeps checked).
-- =====================================================================

-- REF-00502: title is Chinese hanzi ("老年住宅" = Elderly Housing), author
-- 周燕珉 (Zhou Yanmin, a Chinese name), publisher China Architecture &
-- Building Press, jurisdiction already CN. Unambiguously Chinese.
UPDATE evidence_sources
SET lang_detected = 'zh',
    lang_detection_method = 'manual_native_language_verification',
    updated_at = '2026-07-19T20:30:00Z',
    updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch8'
WHERE ref_id = 'REF-00502';

-- REF-00195, REF-00196: both titled in Chinese hanzi, both authored by
-- PRC ministries (Ministry of Education, MOHURD, NDRC), jurisdiction
-- already ZH. Unambiguously Chinese, not Japanese.
UPDATE evidence_sources
SET lang_detected = 'zh',
    lang_detection_method = 'manual_native_language_verification',
    updated_at = '2026-07-19T20:30:00Z',
    updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch8'
WHERE ref_id IN ('REF-00195', 'REF-00196');

-- REF-00198: jurisdiction is the sole 'JA' value in the whole corpus
-- (every other Japanese row uses 'JP') -- a plain jurisdiction-code typo
-- (conflated with the language code). The source itself (MEXT special-
-- support-school facilities guidance) is genuinely Japanese; only the
-- jurisdiction field is wrong.
UPDATE evidence_sources
SET jurisdiction = 'JP',
    updated_at = '2026-07-19T20:30:00Z',
    updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch8'
WHERE ref_id = 'REF-00198';

-- =====================================================================
-- Part B: relink existing, already-verified DB rows onto the 2 Tier-2
-- stub-notes slugs that were flagged in equity-dashboard.md as
-- "not started" (cognitive-wayfinding-design, accessible-circulation-
-- geometry both have PRE-REMEDIATION search_languages.notes with zero
-- named instruments, so the notes-extraction pipeline doesn't apply --
-- but each slug already has genuinely on-topic, real-retrieval-verified
-- non-English sources ELSEWHERE in the corpus that were never linked
-- here). Zero new fabrication surface: these are pure relinks of rows
-- already verified in prior sessions/batches.
-- =====================================================================

-- cognitive-wayfinding-design: Sweden (new jurisdiction for this slug).
-- REF-00754 already established (batch 2) for its small-scale-housing
-- recommendation -- directly matches this slug's own documented
-- consensus finding ("Small-group residential scale (<=9) supports DEM
-- wayfinding and autonomy"). Cited for that specific recommendation,
-- not its broader clinical content.
INSERT INTO source_slug_links (
  ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note
) VALUES (
  'REF-00754', 'cognitive-wayfinding-design', 'CWD-23',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  'Sweden''s national dementia-care guideline recommends small-scale specialized housing (smaskaligt sarskilt boende) for moderate-to-severe dementia -- home-like conditions, smaller staff group -- directly matching this slug''s own documented small-group-residential-scale consensus finding. Cited for that housing-unit-scale recommendation specifically, per REF-00754''s own scope note, not its broader clinical-protocol content.'
);

-- cognitive-wayfinding-design: Denmark (new jurisdiction for this slug).
-- REF-00747 already established (batch 2) as a formal dementia-care-home
-- labelling scheme with 3 organizational scope levels, explicitly
-- physical/building framework only -- matches the same small-scale-
-- housing consensus finding as the Swedish and German (KDA) sources
-- already in this slug.
INSERT INTO source_slug_links (
  ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note
) VALUES (
  'REF-00747', 'cognitive-wayfinding-design', 'CWD-24',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  'Denmark''s formal ministerial labelling scheme for dementia-suitable care homes assesses individual housing/living-group scale as one of 3 organizational levels, physical/building framework only (per REF-00747''s own scope note) -- matches this slug''s small-group-residential-scale consensus finding, alongside the German (KDA) and now Swedish sources already present.'
);

-- accessible-circulation-geometry: Netherlands (new jurisdiction for this
-- slug). REF-00071 (NEN 9120:2025) is the Dutch national accessibility
-- standard, already verified elsewhere in the corpus -- same category as
-- DIN 18040-1 already linked here for Germany.
INSERT INTO source_slug_links (
  ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note
) VALUES (
  'REF-00071', 'accessible-circulation-geometry', 'ACG-13',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  'General Dutch national accessibility standard (Toegankelijkheid van gebouwen), comparable in kind and scope to DIN 18040-1 already cited here for Germany. Specific circulation-geometry numeric provisions (lift/corridor dimensions) not independently confirmed this session -- REF-00071''s own verification_note records NEN''s catalog page as an unreachable SPA/paywall -- cited for the general Dutch national baseline by analogy to its established scope in sibling slugs, not for confirmed specific values.'
);

-- accessible-circulation-geometry: Japan (new jurisdiction for this
-- slug). REF-00065 is Japan's comprehensive accessible-building-design
-- standard, already linked to mobility-built-environment (turning
-- circles) and luminance-contrast-and-pattern (signage/lighting) --
-- same comprehensive-national-standard category as DIN 18040-1/
-- BS 8300/NEN 9120.
INSERT INTO source_slug_links (
  ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note
) VALUES (
  'REF-00065', 'accessible-circulation-geometry', 'ACG-14',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  '2026-07-19T20:30:00Z', 'session_2026-07-19-non-english-research-recovery-batch8',
  'Japan''s national architectural design standard for accessibility, already established in sibling slugs (mobility-built-environment for turning circles; luminance-contrast-and-pattern for signage/lighting) as a comprehensive accessibility standard of the same category as DIN 18040-1/BS 8300/NEN 9120. Specific circulation-geometry values not independently re-confirmed this session; cited for the general Japanese national baseline by analogy to its established scope in sibling slugs.'
);

COMMIT;