-- data_20260516172800_correct_ref_00561_bettarello_2021_metadata.sql
-- Data migration: correct REF-00561 metadata (Bettarello 2021).
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.
--
-- ============================================================================
-- BACKGROUND
-- ============================================================================
--
-- REF-00561 was identified during Phase E.1 pilot Pass-1 authoring
-- (session_2026-05-15a fifth addendum, 2026-05-16). The record's CrossRef
-- backfill (session_2026-05-12j-phase-b-verification, verification_note
-- "CrossRef DOI backfill: Jaccard=0.50") matched the wrong target:
--
--   Stored DOI:         10.3403/30081120u   (British Standards Institution)
--   Stored publisher:   BSI British Standards
--   Stored title:       Room acoustic parameters and accessibility
--
-- Web verification (search of MDPI catalog 2026-05-16) confirms the actual
-- paper is:
--
--   Bettarello, F.; Caniato, M.; Scavuzzo, G.; Gasparella, A. (2021)
--   "Indoor Acoustic Requirements for Autism-Friendly Spaces"
--   Applied Sciences 11(9):3942
--   DOI: 10.3390/app11093942
--   Published: 27 April 2021 by MDPI
--   Special Issue: Human-Centred Design of the Built Environments
--   URL: https://www.mdpi.com/2076-3417/11/9/3942
--
-- The Jaccard=0.50 score should have failed the backfill confidence threshold;
-- the record was marked VERIFIED with a 0.50 score that is below typical
-- match-confidence cutoffs (commonly ≥0.7). This is a methodology-level
-- finding flagged for citation-miner skill review separately.
--
-- The author_count=1 / author_count_is_complete=0 in the existing record
-- also under-represents the real authorship (4 authors). Corrected here.
--
-- This is the first concrete example of the rule #10 sub-rule 2 anti-pattern
-- DR-2026-05-13 was authored to catch: VERIFIED confirms a target resolved,
-- not that the cited content matches. The pilot's "open every cited source
-- at the cited section" discipline surfaced it before any reasoning_doc_citations
-- row was created against the wrong target.
--
-- ============================================================================
-- CORRECTION
-- ============================================================================
--
-- Fields corrected:
--   pub_title:     'Room acoustic parameters and accessibility'
--               -> 'Indoor Acoustic Requirements for Autism-Friendly Spaces'
--   doi:           '10.3403/30081120u' -> '10.3390/app11093942'
--   publisher:     'BSI British Standards' -> 'MDPI'
--   journal_name:  NULL -> 'Applied Sciences'
--   journal_name_en: NULL -> 'Applied Sciences'
--   author_count:  1 -> 4
--   author_count_is_complete: 0 -> 1
--   author_display: 'Bettarello, F.' -> 'Bettarello, F.; Caniato, M.; Scavuzzo, G.; Gasparella, A.'
--   subtype:       'standard' -> 'research_article'
--   verification_note: 'CrossRef DOI backfill: Jaccard=0.50'
--                  -> 'Web-verified 2026-05-16 from MDPI catalog; previous CrossRef Jaccard=0.50 backfill mis-matched to BSI standard; corrected per session_2026-05-15a pilot Pass-1 surfaced anomaly'
--   verified_by_tool: 'crossref-doi-backfill' -> 'manual-web-verification'
--   last_verified_at: '2026-05-12 19:24' -> '2026-05-16 17:28'
--   verification_attempt_count: 1 -> 2
--
-- Volume (11), issue (9), pages_start (3942) were already correct.
-- pub_year (2021), first_author_last (Bettarello), first_author_first (F.),
-- source_type (journal_article), lang_detected (en), tier (3), evidence_type
-- (clinical), jurisdiction (INT), metadata_quality (COMPLETE), verification_status
-- (VERIFIED), doi_resolution_outcome (RESOLVED) all remain correct.
--
-- ============================================================================
-- VERIFICATION
-- ============================================================================
--
-- Post-migration:
--   SELECT doi FROM evidence_sources WHERE ref_id='REF-00561' = '10.3390/app11093942'
--   SELECT pub_title FROM evidence_sources WHERE ref_id='REF-00561'
--     = 'Indoor Acoustic Requirements for Autism-Friendly Spaces'
--   SELECT publisher FROM evidence_sources WHERE ref_id='REF-00561' = 'MDPI'
--   FK integrity: zero violations (no FK constraints on this column set)

-- ============================================================================
-- UPDATE STATEMENT
-- ============================================================================

UPDATE evidence_sources
SET pub_title                  = 'Indoor Acoustic Requirements for Autism-Friendly Spaces',
    doi                        = '10.3390/app11093942',
    publisher                  = 'MDPI',
    journal_name               = 'Applied Sciences',
    journal_name_en            = 'Applied Sciences',
    author_count               = 4,
    author_count_is_complete   = 1,
    author_display             = 'Bettarello, F.; Caniato, M.; Scavuzzo, G.; Gasparella, A.',
    subtype                    = 'research_article',
    verification_note          = 'Web-verified 2026-05-16 from MDPI catalog; previous CrossRef Jaccard=0.50 backfill mis-matched to BSI standard; corrected per session_2026-05-15a pilot Pass-1 surfaced anomaly',
    verified_by_tool           = 'manual-web-verification',
    last_verified_at           = '2026-05-16 17:28',
    verification_attempt_count = 2,
    updated_at                 = '2026-05-16 17:28',
    updated_by_session         = 'session_2026-05-15a-governance-reconciliation-and-pilot'
WHERE ref_id = 'REF-00561';

-- ============================================================================
-- Register this migration in data_migrations
-- ============================================================================

INSERT INTO data_migrations (migration_id, applied_at, content_sha, applied_by_session, notes)
VALUES (
    'correct_ref_00561_bettarello_2021_metadata',
    '2026-05-16 17:28:00',
    'update_ref_00561_doi_title_publisher_journal_author_authorship',
    'session_2026-05-15a-governance-reconciliation-and-pilot',
    'Correct REF-00561 (Bettarello 2021) metadata: prior CrossRef DOI backfill (Jaccard=0.50) mis-matched the paper to a British Standards Institution standard (10.3403/30081120u, BSI publisher). Correct paper: Bettarello, Caniato, Scavuzzo, Gasparella (2021), "Indoor Acoustic Requirements for Autism-Friendly Spaces," Appl. Sci. 11(9):3942, DOI 10.3390/app11093942, MDPI. Surfaced by Phase E.1 pilot Pass-1 of room-acoustic-performance reasoning doc. First concrete instance of rule #10 sub-rule 2 catching a wrong-content VERIFIED record before reasoning_doc_citations row creation.'
);
