-- data_20260516032500_fix_slugs_sl_path_2026-05-15a.sql
-- Data migration: correct slugs.sl_path values to point at the canonical
-- search-log location instead of the BPC location.
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.
--
-- ============================================================================
-- BACKGROUND
-- ============================================================================
--
-- session_2026-05-15a-governance-reconciliation found that all 81 ACTIVE rows
-- in the slugs table have `sl_path == bpc_path`. The repository actually
-- maintains separate search-log files at references/search-log/{topic}/{slug}.md
-- distinct from the BPC files at references/bpc/{topic}/{slug}.md (per the
-- 2026-03-26 search-log split migration, commits 27d0fbb1 + e1dea9a7).
--
-- The slugs table was never updated to reflect the split — sl_path continued
-- to point at the BPC path. This is silent drift: any tool that relied on
-- slugs.sl_path to locate the search-log would either fail to find one or
-- collide with the BPC content depending on read semantics. The drift
-- persisted because:
--   - filesystem-walking validators (e.g., validate_cross_refs.py) glob the
--     directory and don't consult slugs.sl_path
--   - research-log-manager skill writes the search-log via deterministic
--     path construction (slug + topic_directory), bypassing slugs.sl_path
--
-- Effect: any future code that DOES consult slugs.sl_path would receive a
-- silently-wrong location. The mitigation is to align sl_path with the
-- filesystem reality before any new tooling depends on it.
--
-- ============================================================================
-- CORRECTION
-- ============================================================================
--
-- For every ACTIVE row in slugs where sl_path == bpc_path:
--   - new sl_path = 'references/search-log/' || topic_directory || '/' || slug || '.md'
--
-- bpc_path is preserved (it correctly points at references/bpc/{topic}/{slug}.md).
--
-- This is a path-correction migration only. No data is created or destroyed.
-- The search-log files themselves already exist at the corrected paths
-- (77 of 81 confirmed at session_2026-05-15a third addendum, plus
-- ot-cpg-built-environment authored in this same session, plus the 2 economics
-- index BPCs and 1 STUB which are out of scope for this fix — they need a
-- bpc_type protocol amendment per session_2026-05-15a fourth addendum, not a
-- path correction).
--
-- ============================================================================
-- VERIFICATION
-- ============================================================================
--
-- Post-migration invariants:
--   - SELECT COUNT(*) FROM slugs WHERE sl_path = bpc_path AND status='ACTIVE' = 0
--     (was 81 before this migration)
--   - SELECT COUNT(*) FROM slugs WHERE sl_path LIKE 'references/search-log/%'
--     AND status='ACTIVE' = 81
--   - For every ACTIVE row: sl_path = 'references/search-log/' || topic_directory || '/' || slug || '.md'

-- ============================================================================
-- UPDATE STATEMENT
-- ============================================================================

UPDATE slugs
SET sl_path = 'references/search-log/' || topic_directory || '/' || slug || '.md',
    updated_at = '2026-05-16 03:25:00',
    updated_by_session = 'session_2026-05-15a-governance-reconciliation'
WHERE status = 'ACTIVE'
  AND sl_path = bpc_path;

-- ============================================================================
-- Register this migration in data_migrations
-- ============================================================================

INSERT INTO data_migrations (migration_id, applied_at, content_sha, applied_by_session, notes)
VALUES (
    'fix_slugs_sl_path_2026-05-15a',
    '2026-05-16 03:25:00',
    'update_81_active_slugs_sl_path_to_references_search_log_topic_slug_md',
    'session_2026-05-15a-governance-reconciliation',
    'Correct slugs.sl_path for all 81 ACTIVE rows from sl_path==bpc_path (incorrect; silent drift since 2026-03-26 search-log split migration) to sl_path = references/search-log/{topic}/{slug}.md (correct; matches filesystem reality). Path-correction only; no data created or destroyed. Surfaced in session_2026-05-15a third addendum.'
);
