-- data_20260724051510_2026-07-24-vestibular-phase-b.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-vestibular-phase-b
-- Generated:  2026-07-24T05:15:10+00:00
-- Summary:    Reconcile verification_status with Phase-B content read (8 anchors → VERIFIED; audit finding 1a)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Adversarial-review fix (2026-07-24): reconcile source verification_status with the Phase-B
-- content read. The judgment migration's comment claimed "full-text verification complete" while
-- these 8 anchors still sat at UNVERIFIED-1 — a narrative/DB-state mismatch (doctrine-audit finding
-- 1a). They WERE content-verified via PubMed abstracts (which is where the cited pooled estimates,
-- sample sizes, and study types live). Advance to VERIFIED; the two carrying earlier author
-- corrections (REF-00911, REF-00912) → VERIFIED-WITH-CORRECTION. verified_by_tool records the
-- depth honestly (abstract-level, not full-PDF page extraction). This also makes the VES cells'
-- has_unverified_sources=0 consistent with the source records.
UPDATE evidence_sources SET verification_status='VERIFIED',
  last_verified_at='2026-07-24T05:15:00Z', verified_by_tool='pubmed-abstract-phase-b'
  WHERE ref_id IN ('REF-00903','REF-00905','REF-00906','REF-00907','REF-00908','REF-00913')
    AND verification_status='UNVERIFIED-1';
UPDATE evidence_sources SET verification_status='VERIFIED-WITH-CORRECTION',
  last_verified_at='2026-07-24T05:15:00Z', verified_by_tool='pubmed-abstract-phase-b'
  WHERE ref_id IN ('REF-00911','REF-00912')
    AND verification_status='UNVERIFIED-1';
UPDATE evidence_sources SET
  last_verified_at='2026-07-24T05:15:00Z', verified_by_tool='pubmed-abstract-phase-b'
  WHERE ref_id='REF-00792' AND last_verified_at IS NULL;

COMMIT;
