-- data_20260804190706_2026-08-04-derivation-sha-backfill.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-04-derivation-sha-backfill
-- Generated:  2026-08-04T19:07:06+00:00
-- Summary:    stamp derivation_sha on the 8 unattested determinations; label 9014/9015's rule_version from their provenance migration
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Stamp derivation_sha on the 8 determinations that carried none, so that K01
-- watches all 15 instead of 7.
--
-- WHY STAMP AT ALL
-- The restamp migration data_20260804185632 settled the semantics this repo
-- operates under: derivation_sha is a FINGERPRINT OF THE ROW'S INPUTS, and
-- rule_version is the sole record of what produced the determination. Under
-- that division, hashing a hand-derived row under its own recorded batch label
-- asserts nothing false. It binds the fingerprint to the label, so that a later
-- silent edit to the item, the population, the governing set OR the label
-- becomes detectable.
--
-- The protection is not hypothetical. Both rows that failed K01 were
-- hand-maintained rows moved by ordinary maintenance -- a population rename
-- (9007) and a governing-set narrowing (9003). These 8 are exposed to exactly
-- that: 9014 and 9015 have already had a post-insert correction pass over them
-- (data_20260724050932 narrowed a REF-00907 attribution), and 9012/9013 carry
-- updated_by_session from a later session than the one that created them.
-- Unstamped, they are invisible to the only mechanical drift detector the repo
-- has. "Honestly unattested" was the right description of their past; going
-- forward it just means unwatchable.
--
-- RULE_VERSION FOR 9014/9015
-- These two carried NULL rule_version, so there was no label to hash against.
-- The label is not invented here, it is READ OFF the migration record: both
-- rows were inserted by session_2026-07-24-vestibular-phase-b in
-- data_20260724045840, and corrected by the same session in
-- data_20260724050932. 'vestibular-phase-b-2026-07-24' follows the naming of
-- the two existing hand-batch labels ('phase-e-pilot-2026-07',
-- 'batch1-2026-07-19'). The migration file is the receipt.
--
-- WHAT THIS COSTS, STATED PLAINLY
-- After this, a derivation_sha no longer distinguishes an engine-derived row
-- from a hand-derived one -- every row has one. That distinction now lives
-- entirely in rule_version, whose values separate engine versions ('pilot-2')
-- from hand batches. That is where the owner's ruling put it. Nobody should
-- read a sha as evidence that assess_cell.py ran.
--
-- Payload is assess_cell.sha() exactly: item_code|population_code|
-- sorted(governing_refs) joined by '|', then '::' and rule_version.

UPDATE evidence_cell_state SET rule_version = 'vestibular-phase-b-2026-07-24',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill'
 WHERE cell_id IN (9014, 9015);

UPDATE evidence_cell_state SET derivation_sha = '82cb8ea90acd1988547ea0cfbbad6812dd9508d4576819e2c460a50f2d195f0a',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9008;
UPDATE evidence_cell_state SET derivation_sha = 'fca1c87e7baabc862973232bd4f870faf607eb9103fc9b3830265d5ab01cca66',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9009;
UPDATE evidence_cell_state SET derivation_sha = '2138adc1f67135d75f08910ce6ba8bd94395f6e566067c8cb8cbd8fd8f7e9245',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9010;
UPDATE evidence_cell_state SET derivation_sha = '0f66fe325e6628473b4a040a1deb2dd6f6888dd2bc1871df7132a857b944a1fc',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9011;
UPDATE evidence_cell_state SET derivation_sha = '7b9c7974e10435cc33b517a7127837849b4f98c39f9b349e01d3e30f9b180a22',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9012;
UPDATE evidence_cell_state SET derivation_sha = '15adf5957f133e67061a3e02943378dfd6eb73f4de23f9b03b2d332e474b89e9',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9013;
UPDATE evidence_cell_state SET derivation_sha = '42f2348127e28721baf27a7d59e5d4a4acfa77e56005d7b49fe28cc71ff91a75',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9014;
UPDATE evidence_cell_state SET derivation_sha = '41c57aff112694b2fe9326e4d76641d8ed96170379a264771989075652618b0f',
       updated_at = '2026-08-04 19:20', updated_by_session = 'session_2026-08-04-derivation-sha-backfill' WHERE cell_id = 9015;

COMMIT;
