-- data_20260725034017_2026-07-24-research-matrix-completion.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-research-matrix-completion
-- Generated:  2026-07-25T03:40:17+00:00
-- Summary:    resolve Amos backward-mining lead: admit REF-00944 (Amos 2019) w/ PROXY population grade + self-correct the over-claimed candidate; log zero-yield query
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Resolve the highest-value backward-mining lead (Amos et al.) from REF-00943's reference list.
-- OUTCOME INCLUDES A SELF-CORRECTION: the staged candidate described this as "sensory input as a
-- barrier to autistic adults engaging in public and occupational SPACES — the direct
-- built-environment claim". Resolving it shows that was OVER-CLAIMED. The paper is a structural-
-- equation-modelling questionnaire study in the GENERAL POPULATION testing whether sensory
-- over-responsivity and stress mediate autistic traits -> anxiety. It is not a built-environment
-- study, its participants are not diagnosed autistic adults, and it supplies no design parameter.
-- Admitted for what it actually is; the mischaracterisation is corrected in the record.
INSERT INTO evidence_sources (ref_id,source_type,first_author_last,first_author_first,author_count,
 author_count_is_complete,is_corporate_primary,pub_year,pub_title,journal_name,volume,issue,
 pages_start,pages_end,doi,pmid,url,jurisdiction,language,lang_detected,tier,evidence_type,scope,
 verification_status,metadata_quality,doi_resolution_outcome,url_resolution_outcome,verified_by_tool,
 last_verified_at,prior_expectation,search_queries_used,notes,created_at,created_by_session,
 updated_at,updated_by_session)
VALUES ('REF-00944','journal_article','Amos','Georgina A',4,1,0,2019,
 'Autism Traits, Sensory Over-Responsivity, Anxiety, and Stress: A Test of Explanatory Models',
 'Journal of Autism and Developmental Disorders','49','1','98','112',
 '10.1007/s10803-018-3695-6','30043351','https://doi.org/10.1007/s10803-018-3695-6',
 'AU','en','en',3,'clinical','lower_control','VERIFIED','COMPLETE','RESOLVED','RESOLVED',
 'pubmed+doi.org','2026-07-25T04:05:00+00:00',
 'Backward-mined from REF-00943; expected (per the citing paper''s framing) a study of autistic adults facing sensory barriers in public and occupational SPACES, i.e. a built-environment source. Tested that expectation by resolving the actual paper.',
 'PubMed: "Amos autistic adults sensory environment barrier public occupational spaces" (0 results, over-conjunctive); PubMed: Amos[Author] AND autism (9 results); resolved PMID 30043351 + doi.org 302',
 'MECHANISM evidence, NOT a design-parameter source. SEM/questionnaire study; the model in which sensory over-responsivity (SOR) and stress MEDIATE the autistic-traits -> anxiety relationship best explained the variance. Authors conclude "sensory neutral environments should be considered for the prevention and management of anxiety and stress symptoms" — a DIRECTIONAL recommendation with no specified value, threshold or parameter. IMPORTANT POPULATION CAVEAT: participants were a GENERAL-POPULATION adult sample scored for autistic TRAITS, not diagnosed autistic people. CORRECTION: this session''s staged candidate over-claimed it as "the direct built-environment claim"; it is not. Its value is that it supplies the causal mechanism (sensory load -> stress -> anxiety) that justifies WHY sensory design matters, without telling you what to build.',
 '2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion',
 '2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion');

INSERT INTO evidence_source_authors (ref_id,position,last_name,first_name,is_corporate,created_at,created_by_session) VALUES
 ('REF-00944',1,'Amos','Georgina A',0,'2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion'),
 ('REF-00944',2,'Byrne','Graeme',0,'2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion'),
 ('REF-00944',3,'Chouinard','Philippe A',0,'2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion'),
 ('REF-00944',4,'Godber','Timothy',0,'2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion');

INSERT INTO source_slug_links (ref_id,slug,local_ref_id,created_at,created_by_session,updated_at,updated_by_session,relevance_note) VALUES
 ('REF-00944','ndv-aut-built-environment-quantified-thresholds','NAT-09','2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion','2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion',
  'Mechanism source (SOR + stress mediate autistic traits -> anxiety). Supports WHY sensory thresholds matter; supplies NO threshold value. General-population trait sample, not diagnosed autistic adults.');

-- R4: honest PROXY grade — the population studied is not the population the slug serves.
INSERT INTO evidence_population_match (source_ref,target_population,study_population,sample_size,
 match_grade,mismatch_note,ref_id,created_at,created_by_session) VALUES
('Amos, Byrne, Chouinard & Godber 2019 — Autism Traits, Sensory Over-Responsivity, Anxiety and Stress: A Test of Explanatory Models',
 'AUT','General-population adults scored for autistic TRAITS (not clinically diagnosed autistic people)',NULL,'PROXY',
 'PROXY, flagged: trait-level general-population sample. Findings about autistic traits in the general population do not transfer unmodified to diagnosed autistic adults, who differ in support needs and co-occurring conditions. Use for mechanism, never as evidence about autistic people''s environmental thresholds.',
 'REF-00944','2026-07-25T04:05:00+00:00','session_2026-07-24-research-matrix-completion');

-- R8: log BOTH searches, including the zero-yield one.
INSERT INTO search_executions (slug,jurisdiction,language,target_tier,target_evidence_type,target_scope,
 query_text,engine,depth_method,mining_direction,results_found,results_screened,results_admitted,
 saturation_signal,admitted_ref_ids,deferred_reason,findings_note,harm_finding,backfill,session,executed_at) VALUES
('ndv-aut-built-environment-quantified-thresholds',NULL,'en',3,'clinical','lower_control',
 'Amos autistic adults sensory environment barrier public occupational spaces','pubmed','scoping','backward',
 0,0,0,'none',NULL,NULL,
 'ZERO YIELD, kept. Over-conjunctive PubMed query — the same failure mode logged earlier this session. Recorded because the failed formulation is itself the finding: PubMed AND-chains every term, so descriptive multi-concept phrasings return nothing.',0,0,
 'session_2026-07-24-research-matrix-completion','2026-07-25T04:05:00+00:00'),
('ndv-aut-built-environment-quantified-thresholds',NULL,'en',3,'clinical','lower_control',
 'Amos[Author] AND autism','pubmed','scoping','backward',9,9,1,'partial','["REF-00944"]',NULL,
 'BACKWARD-MINING RESOLUTION of the Amos lead from REF-00943. Author-field search succeeded where the descriptive query returned 0. Resolved to Amos 2019 (J Autism Dev Disord 49:98-112). KEY CORRECTION: the lead was staged as "the direct built-environment claim" and is NOT — it is an SEM mechanism study in a general-population trait sample. Mining therefore both produced a source AND corrected an over-claim I had recorded.',0,0,
 'session_2026-07-24-research-matrix-completion','2026-07-25T04:05:00+00:00');

-- R2: the mining register now records what this mining actually produced.
UPDATE citation_mining
   SET connections_produced = '["REF-00944"]',
       notes = notes || ' RESOLVED 2026-07-25: the Amos lead resolved to Amos et al. 2019 (DOI 10.1007/s10803-018-3695-6, PMID 30043351), admitted as REF-00944 — a mechanism study, NOT the built-environment source the citing paper''s phrasing implied.',
       updated_at = '2026-07-25T04:05:00+00:00', updated_by_session='session_2026-07-24-research-matrix-completion'
 WHERE global_ref_id = 'REF-00943';

-- Close the candidate honestly, preserving the correction.
UPDATE search_candidates
   SET disposition = 'ADMITTED',
       locator = 'https://doi.org/10.1007/s10803-018-3695-6',
       locator_status = 'RESOLVED',
       notes = notes || ' | RESOLVED to REF-00944. SELF-CORRECTION: this candidate''s title/description over-claimed the source as a direct built-environment claim about autistic adults in public and occupational spaces. It is an SEM mechanism study in a general-population autistic-traits sample and supplies no design parameter. Harm flag retained only insofar as it evidences sensory load -> stress -> anxiety, not environmental exclusion.'
 WHERE title LIKE 'Amos et al.%';

COMMIT;
