-- data_20260719060557_2026-07-19-non-english-research-recovery-batch5.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-non-english-research-recovery-batch5.md
-- Generated:  2026-07-19T06:05:57+00:00
-- Summary:    adversarial-review corrections: 1 factual error, 6 tier/evidence_type doctrine violations, 1 lang_detected over-correction reverted, 1 verification_note honesty fix
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- data migration — batch 5: adversarial-review corrections
-- Summary: an independent, guilty-until-proven-innocent review of batches 1-4 (3 web-verification
-- agents + 1 DB-integrity/doctrine agent) found 1 factual error, 1 likely lang_detected
-- over-correction, 1 misleading verification_note, and 6 tier/evidence_type doctrine violations
-- (governance/tier-system.md). This migration is the compensating correction -- per this repo's
-- own rule, past migrations are forward-only/immutable; corrections land as a new migration, not
-- an edit. "The correction is the point" (README.md) -- this is that discipline working as
-- designed, now applied reflexively to this session's own output.

BEGIN TRANSACTION;

-- ────────────────────────────────────────────────────────────────────────
-- FIX 1 — REF-00751 (MHLW Ordinance No. 34, Japan): factual error. Adversarial re-verification
-- found the ordinance's current standing text (post-2021-04-01 revision) sets unit count at 1-3
-- units (max 27 residents), NOT "max 2 units (18 residents)" as ingested. The "strictest small-
-- scale mandate among 14 jurisdictions" superlative in derivation_chain rested partly on this
-- wrong figure and is removed/softened.
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET notes = 'Chapter 5 (Articles 89-108) sets mandatory facility standards for 認知症対応型共同生活介護 (Dementia-Adapted Communal Living Care / Group Homes) under Japan''s Long-Term Care Insurance system: unit size 5-9 residents (basic care group), max 3 units (up to 27 residents, post-2021-04-01 revision -- CORRECTED 2026-07-19; originally ingested as "max 2 units/18 residents", a factual error caught by adversarial re-verification) per facility, individual private rooms, minimum room area ~7.43 m².',
       derivation_chain = 'Recovered per research-handoff-non-english.md Tier-1 (wayfinding-dementia-spatial-design, JA, 9 non-EN hits) -- batch 2. [2026-07-19 batch5 correction] The "strictest mandatory small-scale requirement among 14 jurisdictions" comparison is REMOVED -- it rested on the incorrect 18-resident cap; the corrected 27-resident cap is no longer clearly the strictest in the comparison set and this claim is not re-asserted without re-checking every other jurisdiction''s current figure.',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction] Independent re-verification found the unit-count cap was wrong: current standing text (post-2021-04-01 revision) is 1-3 units (max 27 residents), not "max 2 units/18 residents" as originally ingested. notes and derivation_chain corrected; the cross-jurisdiction "strictest" superlative is withdrawn pending a proper re-comparison.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00751';

-- ────────────────────────────────────────────────────────────────────────
-- FIX 2 — REF-00744 (GB/T 46401-2025, China): tier doctrine violation. governance/tier-system.md
-- defines T6 as "Statutory code -- legally enforceable." The row's own notes already admitted
-- "GB/T is technically non-mandatory-recommended rather than fully statutory" but it was
-- committed at tier=6 anyway. Corrected to tier=5 ("National beyond-code frameworks -- best-
-- practice guidance issued by national bodies but not legally enforced"), which is the doctrine-
-- correct placement for a non-mandatory national recommended standard.
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET tier = 5,
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction] tier corrected 6->5 per governance/tier-system.md: T6 requires legally-enforceable statutory status; GB/T is a non-mandatory recommended national standard (this row''s own notes already said so) and belongs at T5 (national beyond-code framework), not T6.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00744';

-- ────────────────────────────────────────────────────────────────────────
-- FIX 3 — REF-00743, REF-00749, REF-00754: evidence_type doctrine violation. These are formal
-- national/regional clinical-practice-guideline-catalogue documents (Helsedirektoratet retningslinje,
-- GuiaSalud GPC 484, Socialstyrelsen nationella riktlinjer) -- the doctrine's "named-organisation
-- evidence-based standards" category at T2, evidence_type=standard_eb (every pre-existing T2 row
-- in the DB uses standard_eb/sr_meta/co2; 'clinical' has zero T2 precedent and per tier-system.md
-- is reserved for T1/T3 primary research). Tier=2 is kept (these ARE formal named-body consensus
-- documents, the correct rank) -- only evidence_type is corrected.
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET evidence_type = 'standard_eb',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction] evidence_type corrected clinical->standard_eb per governance/tier-system.md: this is a formal named-organisation clinical-guideline-catalogue document (T2''s "named-organisation evidence-based standards" category), not primary clinical research (which is what evidence_type=clinical denotes, reserved for T1/T3). Tier=2 is unchanged -- it is the correct rank for this document type.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id IN ('REF-00743', 'REF-00749', 'REF-00754');

-- ────────────────────────────────────────────────────────────────────────
-- FIX 4 — REF-00745 (Ympäristöopas 2018, Finland): tier + evidence_type doctrine violation.
-- Adversarial review correctly identified this is a Ministry-of-Environment HOUSING DESIGN GUIDE,
-- not a clinical document at all -- tier=2/evidence_type=clinical granted it best-practice-
-- anchoring CPG status it does not have. Corrected to tier=5 ("National beyond-code frameworks --
-- best-practice guidance issued by national bodies but not legally enforced"), evidence_type=
-- national_fw -- the doctrine-correct placement for a non-binding government design guide.
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET tier = 5,
       evidence_type = 'national_fw',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction] tier corrected 2->5, evidence_type corrected clinical->national_fw per governance/tier-system.md: this is a Ministry-of-Environment housing/design guidance document, not a clinical-guideline-catalogue document or primary clinical research -- it does not carry the best-practice-anchoring status T2 grants, and belongs at T5 (national beyond-code framework, non-legally-enforced government guidance).',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00745';

-- ────────────────────────────────────────────────────────────────────────
-- FIX 5 — REF-00221 (Japan deafblind communication booklet): tier + evidence_type doctrine
-- violation. This row's OWN notes already say "Content is general disability-welfare/
-- communication-modality documentation, not an architectural/built-environment design standard."
-- It should never have been placed at T2/clinical (best-practice-anchoring CPG status). Corrected
-- to tier=3/evidence_type=grey, consistent with how this session tiered directly-comparable
-- institutional/informational sources elsewhere (REF-00755 Wegweiser Demenz, REF-00763 DAB
-- article, REF-00764 Tsukuba campus page all correctly landed at T3/grey).
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET tier = 3,
       evidence_type = 'grey',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction] tier corrected 2->3, evidence_type corrected clinical->grey per governance/tier-system.md: this row''s own notes already state it is welfare/communication-modality documentation, not a design standard or clinical-guideline-catalogue document -- T2 wrongly granted it best-practice-anchoring status. T3/grey matches how this session tiered directly comparable institutional/informational sources (REF-00755, REF-00763, REF-00764).',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00221';

-- ────────────────────────────────────────────────────────────────────────
-- FIX 6 — REF-00765 (Metote Lab, Japan): Co-1 encoding violation. This row was deliberately
-- ingested AS Co-1 lived-experience evidence (co1_provenance/co1_source_type were set, and its
-- own notes/relevance_note repeatedly call it Co-1 evidence) -- but it was placed at tier=3/
-- evidence_type=grey, NOT the DB's established Co-1 convention (tier=1/evidence_type=co1; 29 of
-- 30 pre-existing co1 rows use this pairing). This silently defeated the batch's own stated goal
-- (a non-English, non-US/UK Co-1 counterweight -- README.md documents this track as thin and
-- US/UK-skewed) -- anything querying by evidence_type='co1' or tier=1 would never see it.
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET tier = 1,
       evidence_type = 'co1',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction] tier corrected 3->1, evidence_type corrected grey->co1 per this DB''s established Co-1 convention (29/30 pre-existing co1 rows use tier=1/evidence_type=co1). This row was always intended as Co-1 lived-experience evidence (co1_provenance/co1_source_type were already set) -- the original tier=3/grey placement silently defeated that purpose by making it invisible to any query keyed on evidence_type=co1 or tier=1.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00765';

-- ────────────────────────────────────────────────────────────────────────
-- FIX 7 — REF-00310 (Lund University PhD dissertation, Sweden): likely batch-1 lang_detected
-- over-correction. Adversarial review found Lund University's own LUP publications catalogue
-- carries an ENGLISH title for this dissertation ("Universal Design as Guiding, Striving and
-- Unifying: A Qualitative Study..."), and Nordic medical-faculty dissertations are frequently
-- published in English -- contradicting the batch-1 call of lang_detected='sv'. Reverted to 'en'
-- as the more defensible position given this conflicting primary-catalogue evidence; the
-- dissertation's DB-stored title happens to carry a Swedish subtitle, which is not, on its own,
-- sufficient to override the institution's own English cataloguing (the exact kind of ambiguous
-- case batch 1 correctly left uncorrected for 5 OTHER rows on the same reasoning).
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET lang_detected = 'en',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction] lang_detected REVERTED sv->en. The batch-1 correction to ''sv'' is not defensible: Lund University''s own LUP publications catalogue lists this dissertation under an ENGLISH title ("Universal Design as Guiding, Striving and Unifying: A Qualitative Study..."), and Nordic medical-faculty dissertations are commonly published in English despite a Swedish-language subtitle appearing in secondary citations. This is the same category of ambiguous case batch 1 correctly left uncorrected for 5 other rows (REF-00085/239/287/461/599) -- it should have been left alone rather than flipped.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00310';

-- ────────────────────────────────────────────────────────────────────────
-- FIX 8 — REF-00299 (Norwegian Government Action Plan for Universal Design): verification_note
-- honesty correction. Adversarial review confirmed the DATA VALUE (lang_detected='no') is correct
-- (the plan has no English edition) but the batch-1 verification_note's stated justification
-- ("verified from standard_number/pub_title native-language text") is FALSE -- both fields are
-- 100% English text ("Norwegian Government Action Plan for Universal Design 2015-2019..."). The
-- actual basis was jurisdiction-inference + external confirmation of no-English-edition, not
-- native-language text in the row itself. Corrected for audit-trail honesty; the language value
-- itself is NOT changed.
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 batch5 adversarial-review correction, audit-trail honesty only -- lang_detected value UNCHANGED, confirmed correct] The original correction''s stated justification ("verified from standard_number/pub_title native-language text") was FALSE -- both fields are entirely English text; there is no native-language text in this row to have verified from. The actual, defensible basis is jurisdiction-inference (Norwegian government policy documents of this type are published Norwegian-only) confirmed by external check that no English edition of this action plan exists. Recorded honestly here per this project''s own transparency discipline -- a right answer with a false stated method is still a documentation defect.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00299';

-- ────────────────────────────────────────────────────────────────────────
-- FIX 9 — REF-00462 -> luminance-contrast-and-pattern relink (LCP-13): relevance_note precision
-- correction. This GB 50763-2012 row's own pub_title is "无障碍出入口" (accessible entrances); the
-- relink to luminance-contrast-and-pattern was justified by stair tread/riser color-contrast
-- language that lives in a different section of GB 50763 than this row's excerpt. Not a
-- topical mismatch or fabrication (the same standard number does contain that provision
-- elsewhere), but section-level imprecision -- corrected for precision.
-- ────────────────────────────────────────────────────────────────────────
UPDATE source_slug_links
   SET relevance_note = relevance_note || ' [2026-07-19 batch5 correction: this row''s own excerpt/pub_title ("无障碍出入口", accessible entrances) is a different GB 50763-2012 section than the stair tread/riser contrast provision (踏面和踢面的颜色宜有区分和对比) this link cites -- both provisions are real and in the same standard, but a section-specific GB 50763 row (if one exists for the stair/tactile-guidance chapter) would be the more precise target. Flagged for a future precision pass, not fabricated.]',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch5'
 WHERE ref_id = 'REF-00462' AND slug = 'luminance-contrast-and-pattern';

COMMIT;