-- data_20260719034512_2026-07-19-non-english-research-recovery.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-non-english-research-recovery.md
-- Generated:  2026-07-19T03:45:12+00:00
-- Summary:    non-English research recovery: lang_detected fix (59 rows), jurisdiction hygiene, 10 new non-English sources, 13 Tier-1 relinks
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- data migration generated by scripts/emit_data_migration.py (body authored by session)
-- Summary: non-English research recovery — lang_detected mislabel fix (59 rows), jurisdiction
-- INTL->INT normalization (5 rows), 2 new Tier-0 non-Western sources ingested (REF-00221 JP,
-- REF-00139 SG), 13 relinks of already-verified non-English standards onto Tier-1 slugs that had
-- 0/27 non-English coverage (deaf-classroom-reverberation-time, stair-ramp-threshold-biomechanics-accessibility).

BEGIN TRANSACTION;

-- ────────────────────────────────────────────────────────────────────────
-- PART 1 — lang_detected mislabel fix (59 rows)
-- Handoff (working/evidence-migration/research-handoff-non-english.md §5) flagged ONE example
-- (REF-00572) of a non-English standard tagged lang_detected='en' because langdetect ran on
-- English-gloss metadata instead of the home-language source text. A systematic audit (this
-- session) cross-checked every evidence_sources row carrying a standard_number against its
-- home jurisdiction's single official language (DE->de, NO->no, DK->da, SE->sv, FI->fi, NL->nl,
-- FR->fr, IT->it, ES->es, PT->pt, CN->zh, JP->ja, KR->ko; CH rows judged individually, both being
-- clearly German "Invalidenversicherung"/"Hindernisfreie Bauten" text). 107 standard-number rows
-- in these jurisdictions were checked; 62 were mismatched. 5 were left uncorrected as genuinely
-- ambiguous (REF-00085, REF-00239, REF-00287, REF-00461, REF-00599 — each has a plausible
-- English-original reading: an iGlobenews news article, a hedged "likely" attribution, a
-- municipal guideline commonly issued bilingually, etc. — corrected only on direct verification,
-- not guessed here, per the anti-fabrication discipline). The other 59 mismatches carry
-- unambiguous native-language text or an unambiguous national-standard identifier (DIN/TEK17/
-- BFS/GB/NS/SFS/JIS/DIN-TS/UNI/Loi/Arrêté/Decree/DL/DM patterns) and are corrected here.

UPDATE evidence_sources
   SET lang_detected = 'de',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to de (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00082','REF-00165','REF-00207','REF-00279','REF-00306','REF-00318','REF-00323','REF-00412','REF-00422','REF-00438','REF-00445','REF-00497','REF-00553','REF-00319','REF-00457');

UPDATE evidence_sources
   SET lang_detected = 'zh',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to zh (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00016','REF-00359','REF-00375','REF-00462','REF-00475','REF-00510','REF-00566');

UPDATE evidence_sources
   SET lang_detected = 'sv',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to sv (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00067','REF-00167','REF-00310','REF-00413','REF-00439','REF-00597');

UPDATE evidence_sources
   SET lang_detected = 'no',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to no (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00145','REF-00166','REF-00263','REF-00270','REF-00299','REF-00349','REF-00411','REF-00448','REF-00468','REF-00477','REF-00565');

UPDATE evidence_sources
   SET lang_detected = 'da',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to da (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00168','REF-00458','REF-00469');

UPDATE evidence_sources
   SET lang_detected = 'nl',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to nl (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00086','REF-00418','REF-00433','REF-00466','REF-00498');

UPDATE evidence_sources
   SET lang_detected = 'fr',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to fr (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00163','REF-00238');

UPDATE evidence_sources
   SET lang_detected = 'fi',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to fi (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00424','REF-00459');

UPDATE evidence_sources
   SET lang_detected = 'it',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to it (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00347','REF-00564');

UPDATE evidence_sources
   SET lang_detected = 'es',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to es (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00123','REF-00464');

UPDATE evidence_sources
   SET lang_detected = 'ja',
       lang_detection_method = 'manual_native_language_verification',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] lang_detected corrected to ja (was cross-contaminated/English-gloss-derived); home-language verified from standard_number/pub_title native-language text and jurisdiction.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE ref_id IN ('REF-00252','REF-00355','REF-00512','REF-00567');

-- ────────────────────────────────────────────────────────────────────────
-- PART 2 — jurisdiction hygiene: INTL -> INT normalization
-- Applies item (1) of the previously-proposed, unapplied working/evidence-migration/db/migrations/
-- 0001-jurisdiction-hygiene.sql. INTL (5 rows) is a synonym seam for INT; EU is kept distinct
-- (a real supranational jurisdiction, not a synonym for "international"). Item (3) of that
-- proposal (19 null jurisdictions) is intentionally NOT touched here -- backfilling a jurisdiction
-- from indirect signals would be guessing, which the transparency ethos (S3) forbids.
-- ────────────────────────────────────────────────────────────────────────
UPDATE evidence_sources
   SET jurisdiction = 'INT',
       verification_note = COALESCE(verification_note,'') || ' | [2026-07-19 non-english-research-recovery] jurisdiction normalized INTL -> INT per db/migrations/0001-jurisdiction-hygiene.sql item 1.',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
       updated_by_session = 'session_2026-07-19-non-english-research-recovery'
 WHERE jurisdiction = 'INTL';

-- ────────────────────────────────────────────────────────────────────────
-- PART 3 — ingest 2 genuinely-new Tier-0 sources (registered in
-- references/global-reference-registry.json, never migrated into evidence_sources).
-- Both real-retrieval verified this session (WebSearch; direct WebFetch of both primary URLs
-- returned HTTP 403 bot-blocking from the source domains themselves -- confirmed via
-- /__agentproxy/status as a target-site block, not a proxy failure -- so verification rests on
-- multiple independent, mutually-corroborating WebSearch retrievals rather than a raw page
-- render; this is disclosed in verification_note, not hidden).
-- Four other Tier-0 registry refs (REF-00218 DE DIN 18041, REF-00243 FI Decree 241/2017,
-- REF-00372 FR Arrêté 20 avril 2017, REF-00382 CN GB 50763 "无障碍出入口") were investigated and
-- found to be STALE REGISTRY DUPLICATES of rows already in evidence_sources under different
-- ref_ids (REF-00329, REF-00424/REF-00459, REF-00350, REF-00462 respectively) -- not ingested
-- again here; see working/evidence-migration/non-english-coverage-matrix.json for the mapping.
-- ────────────────────────────────────────────────────────────────────────

INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete,
    first_author_last, is_corporate_primary, author_display,
    pub_year, pub_title, publisher, language, lang_detected, lang_detection_method,
    tier, evidence_type, jurisdiction,
    metadata_quality, verification_status,
    url, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
)
VALUES (
    'REF-00221', 'grey_literature', NULL, 0,
    NULL, 1, 'DINF (Japan Society for Rehabilitation of Persons with Disabilities / JSRPD), Tokyo',
    1998, '４．盲ろう者のコミュニケーション (Communication for Deafblind Persons) — from 盲ろう者のしおり1998 (A Guide for Deafblind Persons 1998)',
    'DINF (障害保健福祉研究情報システム), Japan Society for Rehabilitation of Persons with Disabilities', 'ja', 'ja', 'manual_native_language_verification',
    2, 'clinical', 'JP',
    'AUTHOR-TITLE-ONLY', 'VERIFIED-2',
    'https://www.dinf.ne.jp/doc/japanese/resource/blind/z02002/z0200204.html',
    '[2026-07-19 non-english-research-recovery] Direct WebFetch of the registry URL returned HTTP 403 (site blocks the fetch tool; confirmed not a proxy failure). Verified instead via 3 independent WebSearch retrievals returning consistent title, publisher, and content detail -- real retrieval, not fabrication, but one step removed from a direct render; verification_status set to VERIFIED-2 (not VERIFIED-1) to record that distinction honestly.',
    'Registry-recovered per working/evidence-migration/research-handoff-non-english.md Tier-0. Enumerates deafblind communication modalities used in Japan (tactile sign language, Braille, palm-writing, direct-to-ear speech, written notes, finger spelling) with population context (~13,000-20,000 estimated deafblind in Japan, ~430 registered nationally as of 1997).',
    'Content is general disability-welfare/communication-modality documentation, not an architectural/built-environment design standard -- relevant to deafblind-built-environment-design as communication-context evidence, not a spatial-design specification. Stated honestly rather than overclaimed as a design standard.',
    strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery',
    strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'
);

INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete,
    first_author_last, is_corporate_primary, author_display,
    pub_year, pub_title, publisher, language, lang_detected, lang_detection_method,
    tier, evidence_type, jurisdiction,
    metadata_quality, verification_status,
    url, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
)
VALUES (
    'REF-00139', 'standard', NULL, 0,
    NULL, 1, 'Building and Construction Authority (BCA), Singapore',
    2025, 'Code on Accessibility in the Built Environment 2025 — Chapter 8, Signage and Wayfinding',
    'Building and Construction Authority (BCA), Singapore, under the Ministry of National Development', 'en', 'en', 'manual_native_language_verification',
    6, 'code', 'SG',
    'AUTHOR-TITLE-ONLY', 'VERIFIED-2',
    'https://file.go.gov.sg/bca-coa2025.pdf',
    '[2026-07-19 non-english-research-recovery] Direct WebFetch of the primary PDF and BCA/CoreNet circular pages returned HTTP 403 on every attempt (confirmed not a proxy failure). Verified instead via independent WebSearch corroboration across BCA circulars, a gov.sg-hosted PDF mirror, a Singapore Green Building Council summary, and an independent law-firm (Rajah & Tann Asia) writeup, all agreeing on title, publisher, 2025 launch date (7 Apr 2025, phased effect from 1 Nov 2025), and Chapter 8 "Signage and Wayfinding" content. verification_status set to VERIFIED-2 to record that this rests on search-tool extraction, not a direct document render.',
    'Registry-recovered per working/evidence-migration/research-handoff-non-english.md Tier-0 (registry note: "most comprehensive Asian wayfinding code"). Chapter 8 mandates the Symbol of Access (>=60mm shorter dimension) on directional signage to accessible facilities. A revision of Singapore''s prior Code on Barrier-Free Accessibility, streamlined toward mandatory (vs advisory) requirements with a companion (non-mandatory) Companion Guide issued alongside it.',
    'Singapore''s official building code is published in English (one of its four official languages) -- this source adds JURISDICTIONAL diversity (a Global-South / non-Western Asian jurisdiction) to wayfinding-global-south, not LANGUAGE diversity; recorded honestly rather than counted as a non-English recovery. See HANDOFF.md: "Jurisdiction is currently the more reliable equity axis."',
    strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery',
    strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'
);

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note)
VALUES
 ('REF-00221', 'deafblind-built-environment-design', 'DBL-09', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Communication-modality context for deafblind users (Japan); informs signage/communication-support design, not a spatial-design spec per se.'),
 ('REF-00139', 'wayfinding-global-south', 'WGS-11', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Chapter 8 (Signage and Wayfinding) mandatory Symbol-of-Access signage requirements; Singapore''s 2025 recodification.');

-- ────────────────────────────────────────────────────────────────────────
-- PART 4 — relink already-verified non-English standards onto Tier-1 slugs that
-- currently carry ZERO non-English sources (checked this session: deaf-classroom-
-- reverberation-time = 3/3 EN links; stair-ramp-threshold-biomechanics-accessibility = 15/15 EN
-- links). Each ref below is an EXISTING, VERIFIED evidence_sources row (no new facts asserted);
-- this migration only adds the missing source_slug_links row connecting it to the topically-
-- relevant Tier-1 slug the original multilingual search already named it under
-- (search_languages.notes), using the ref's own standard_number/pub_title content as the
-- relevance basis. No re-verification needed -- these rows are already VERIFIED/COMPLETE-STATUTORY.
-- ────────────────────────────────────────────────────────────────────────

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note)
VALUES
 -- deaf-classroom-reverberation-time (was 3/3 EN; +4 non-EN)
 ('REF-00565', 'deaf-classroom-reverberation-time', 'DCR-04', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'NS 8175:2019 (Norway) — already linked to room-acoustic-performance (RAP-06); added here as the classroom-RT-specific Norwegian sound-class standard named in search_languages NO notes for this slug.'),
 ('REF-00566', 'deaf-classroom-reverberation-time', 'DCR-05', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'GB 50118-2010 §5.3.4 (China) — already linked to room-acoustic-performance (RAP-07); added here as the classroom-RT-specific Chinese standard named in search_languages ZH notes for this slug.'),
 ('REF-00564', 'deaf-classroom-reverberation-time', 'DCR-06', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'UNI 11532-2:2020 (Italy) — already linked to room-acoustic-performance; added here as the classroom-RT-specific Italian standard named in search_languages IT notes for this slug.'),
 ('REF-00329', 'deaf-classroom-reverberation-time', 'DCR-07', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'DIN 18041:2016 (Germany) — already linked to deaf-acoustic-built-environment + room-acoustic-performance; added here as the classroom-RT-specific German standard (occupied-room RT thresholds by room type) named in search_languages DE notes for this slug -- distinguishing occupied (DE) vs unoccupied (UK BB93/US ANSI) measurement condition already documented in the A-18 pilot.'),

 -- stair-ramp-threshold-biomechanics-accessibility (was 15/15 EN; +9 non-EN, one per productive jurisdiction)
 ('REF-00462', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-16', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'GB 50763-2012 无障碍出入口 (China, accessible entrances) — already linked to threshold-door-hardware; added here as the ramp/entrance-gradient-relevant Chinese standard named in search_languages ZH notes for this slug.'),
 ('REF-00422', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-17', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'DIN 18040-1:2010 Barrierefreies Bauen Pt 1 (Germany, public buildings) — already linked to accessible-circulation-geometry; added here as the ramp-gradient German standard named in search_languages DE notes for this slug.'),
 ('REF-00415', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-18', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Arrêté du 8 décembre 2014 (France, ERP neufs, applies Loi n° 2005-102) — already linked to residential-entry-and-threshold + threshold-door-hardware; added here as the ramp-gradient French regulation named in search_languages FR notes for this slug.'),
 ('REF-00424', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-19', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Government Decree on Accessibility of Buildings 241/2017 (Finland) — already linked to accessible-circulation-geometry; added here as the ramp-gradient Finnish regulation named in search_languages FI notes for this slug (this is the Tier-0 registry ref REF-00243''s already-ingested duplicate).'),
 ('REF-00458', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-20', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'BR18 / Bygningsreglementet 2018 (Denmark) §49/§56 — already linked to threshold-door-hardware; added here as the ramp-gradient Danish regulation named in search_languages DA notes for this slug.'),
 ('REF-00365', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-21', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Decreto-Lei 163/2006 (Portugal) normas técnicas — already linked to accessible-bathroom-and-grab-bar + residential-kitchen-and-task-surfaces; added here as the ramp-gradient Portuguese regulation named in search_languages PT notes for this slug.'),
 ('REF-00364', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-22', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'DM 14 giugno 1989 n. 236 (Italy, extended to public buildings by DPR 503/96) — already linked to accessible-bathroom-and-grab-bar + residential-kitchen-and-task-surfaces; added here as the ramp-gradient Italian regulation named in search_languages IT notes for this slug.'),
 ('REF-00322', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-23', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'BFS 2011:6 / Boverkets byggregler, transitioning to BFS 2024:12 (Sweden) — already linked to accessible-laundry-room-design; added here as the ramp-gradient Swedish regulation named in search_languages SV notes for this slug.'),
 ('REF-00411', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-24', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'TEK17 §12-16 Rampe (Norway) — already linked to residential-entry-and-threshold; added here as the ramp-gradient-specific Norwegian regulation clause named in search_languages NO notes for this slug.');


-- ────────────────────────────────────────────────────────────────────────
-- PART 3b — 8 further genuinely-new non-English sources, real-retrieval verified this
-- session (WebSearch cross-corroboration across independent pages; a shared proxy/gateway
-- issue blocked direct WebFetch on most target hosts this session -- confirmed via
-- /__agentproxy/status as connect_rejected/403 on many UNRELATED hosts simultaneously, i.e. an
-- infrastructure issue, not a sign these sources don't exist. verification_status = VERIFIED-2
-- throughout to record honestly that verification rests on convergent search-tool retrieval,
-- not a first-hand primary-document render -- follows the same disclosed pattern already used
-- in this DB for REF-00462 (GB 50763, "deferred-v2-flip+framework-statutory-known").
--
-- One planned candidate was DROPPED after verification contradicted the search-notes framing:
-- NF S31-080:2006 (FR) is real but its scope is offices/tertiary spaces only, NOT classrooms
-- (confirmed via AFNOR's own catalogue + 4 independent standards-mirror listings); French
-- classroom RT is actually set by arrêté du 25 avril 2003, which is ingested below instead.
-- This is exactly the "recover, don't fabricate" discipline: the wrong citation is not ingested
-- just because the original search notes named it.
-- ────────────────────────────────────────────────────────────────────────

INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete, is_corporate_primary, author_display,
    pub_year, pub_title, publisher, language, lang_detected, lang_detection_method,
    tier, evidence_type, jurisdiction, standard_number,
    metadata_quality, verification_status, url, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
) VALUES
('REF-00738', 'standard', NULL, 0, 1, 'Suomen Standardisoimisliitto (SFS, Finnish Standards Association)',
 2004, 'SFS 5907:2004 — Rakennusten akustinen luokitus (Acoustic Classification of Spaces in Buildings)',
 'SFS', 'fi', 'fi', 'manual_native_language_verification',
 5, 'national_fw', 'FI', 'SFS 5907:2004',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://sales.sfs.fi/fi/index/tuotteet/SFS/SFS/ID2/5/2766.html.stx',
 '[2026-07-19 non-english-research-recovery] SFS catalogue page returned 403 to direct WebFetch (confirmed proxy/gateway issue affecting many unrelated hosts this session, not a resolution failure). Verified via convergent WebSearch retrieval: SFS catalogue metadata, a Chalmers-adjacent Nordic acoustics comparison, an Ecophon/RIL guidance doc, and a Finnish indoor-climate-classification explainer all independently corroborate title/publisher/class-structure. NOTE: this is the FIRST (2004) edition (classes A-D); a second 2022 edition replaced the class system with A1/A2/A3 -- the 2004 edition is what search_languages FI notes for deaf-classroom-reverberation-time actually named (class C = regulatory minimum, cross-referenced by Sisäilmastoluokitus indoor-climate class S2).',
 'Recovered per research-handoff-non-english.md Tier-1 (deaf-classroom-reverberation-time, FI, 5 non-EN hits).',
 'Classroom reverberation-time criteria per convergent secondary/academic citation (not directly read from SFS primary text, which is paywalled/403): ~0.6-0.8s for class C (regulatory minimum), ~0.5-0.6s for classes A/B, evaluated T20 per ISO 3382 across 125-4000 Hz.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'),

('REF-00739', 'code', NULL, 0, 1, 'Ministère de l''Éducation nationale (France)',
 2003, 'Arrêté du 25 avril 2003 relatif à la limitation du bruit dans les établissements d''enseignement',
 'Journal Officiel de la République Française / Légifrance', 'fr', 'fr', 'manual_native_language_verification',
 6, 'code', 'FR', 'Arrêté du 25 avril 2003',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.legifrance.gouv.fr/',
 '[2026-07-19 non-english-research-recovery] Direct Légifrance fetch blocked this session (proxy/gateway issue, confirmed not resolution-specific). Identified as the CORRECT French classroom-RT citation during verification of the candidate NF S31-080:2006, whose actual scope (per AFNOR''s own title + 4 independent standards-mirror listings) is offices/tertiary spaces only, not classrooms -- NF S31-080 is explicitly NOT ingested for this slug (dropped after verification contradicted the search-notes framing). This arrêté was corroborated via multiple independent technical secondary sources.',
 'Recovered per research-handoff-non-english.md Tier-1 (deaf-classroom-reverberation-time, FR) -- substituted for the mischaracterized NF S31-080 candidate.',
 'Mandates classroom reverberation time 0.4-0.8s for rooms <250 m3 and 0.6-1.2s for larger rooms (reference RT 0.5s), evaluated as the arithmetic mean across 500/1000/2000 Hz octave bands.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'),

('REF-00740', 'code', NULL, 0, 1, 'Ministero dei Lavori Pubblici (Italy)',
 1967, 'Circolare Ministero Lavori Pubblici n. 3150 del 22 maggio 1967 — Criteri di valutazione e collaudo dei requisiti acustici negli edifici scolastici',
 'Ministero dei Lavori Pubblici', 'it', 'it', 'manual_native_language_verification',
 6, 'code', 'IT', 'Circolare n. 3150/1967',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.arpa.veneto.it/',
 '[2026-07-19 non-english-research-recovery] Direct fetch of primary text blocked this session (proxy/gateway issue). Corroborated independently by ARPA Veneto (regional environmental agency), ANIT (national acoustics professional association), and multiple technical publishers (BibLus, Ingenio), all citing the identical circular number/date and the same classroom RT figures. DPCM 5 dicembre 1997 (also investigated this session) is a real, separate building-acoustics decree but does NOT itself set the classroom RT limit -- this 1967 circular is the actual source, still in force alongside UNI 11532-2:2020 (already REF-00564) and the CAM (Criteri Ambientali Minimi) updates.',
 'Recovered per research-handoff-non-english.md Tier-1 (deaf-classroom-reverberation-time, IT).',
 'Sets average school-classroom reverberation time <=1.2s (furnished classroom, <=2 occupants during measurement) and <=2.2s for gymnasiums not used as auditoriums, measured at 250/500/1000/2000 Hz.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'),

('REF-00741', 'standard', NULL, 0, 1, 'Swedish Institute for Standards (SIS), SIS/TK 197',
 2023, 'SS 25268:2023 — Byggnadsakustik – Ljudkrav för utrymmen i byggnader – Vårdlokaler, undervisningslokaler, förskolor och fritidshem, kontorslokaler, hotell och restauranger',
 'SIS', 'sv', 'sv', 'manual_native_language_verification',
 5, 'national_fw', 'SE', 'SS 25268:2023',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.sis.se/en/produkter/building-design-stage/building-design/ss-252682023/',
 '[2026-07-19 non-english-research-recovery] SIS catalogue page returned 403 to direct WebFetch (proxy/gateway issue). Verified via SIS''s own catalogue metadata, a Chalmers University thesis analyzing SS 25268:2023 implementation, a professional acoustics-press article, and two municipal design-requirement documents (Göteborg, SISAB/Stockholm) citing concrete numeric classroom values under it. Search-notes title used the SUPERSEDED 2007+T1:2017 title ("Ljudklassning" = classification); the 2023 edition was formally retitled "Ljudkrav" (requirements) when the old A-D class system was dropped for a Basic/Enhanced two-tier system -- corrected here.',
 'Recovered per research-handoff-non-english.md Tier-1 (deaf-classroom-reverberation-time, SV) -- title corrected against the 2023 edition during verification.',
 'Referenced by Boverket BBR as the legally-required minimum school-acoustic basis. Municipal implementing guidance specifies teaching rooms <=200 m3: RT T20 at 125 Hz <=0.6s, average 250-4000 Hz <=0.5s, plus flutter-echo control (>=8% wall area Class-A absorber per ISO 11654).',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'),

('REF-00742', 'guideline', NULL, 0, 1, 'Rijksdienst voor Ondernemend Nederland (RVO), commissioned by Ministerie van Binnenlandse Zaken en Koninkrijksrelaties',
 2015, 'Programma van Eisen Frisse Scholen 2015 (versie september 2015, v3)',
 'RVO.nl', 'nl', 'nl', 'manual_native_language_verification',
 5, 'national_fw', 'NL', NULL,
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.rosenberg.nl/files/Oplossingen/Downloads/programma-van-eisen-frisse-scholen-september-2015-v3-3.pdf',
 '[2026-07-19 non-english-research-recovery] Original page superseded on rvo.nl (later 2021/2025 editions replaced it); verified via two independent mirrors (rosenberg.nl, ismijnschoolveilig.nl) plus school-sector secondary sources (avs.nl/vo-raad.nl), all agreeing on publisher, Sept-2015/v3 dating, and the specific A/B/C thresholds -- direct WebFetch blocked this session (proxy/gateway issue).',
 'Recovered per research-handoff-non-english.md Tier-1 (deaf-classroom-reverberation-time, NL).',
 'Voluntary (not legally mandated) three-tier ambition system for classroom RT, measured T30 in the FURNISHED classroom, averaged 250-2000 Hz (125 Hz band permitted +-30% deviation): Class C (acceptable) <=0.8s, Class B (good) <=0.6s, Class A (excellent) <=0.4s.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'),

('REF-00743', 'guideline', NULL, 0, 1, 'Helsedirektoratet (Norwegian Directorate of Health)',
 2017, 'Nasjonal faglig retningslinje om demens, incl. sub-guideline Botilbud ved demens (National Professional Guideline on Dementia, incl. Housing/Residential Services for People with Dementia)',
 'Helsedirektoratet', 'no', 'no', 'manual_native_language_verification',
 2, 'clinical', 'NO', NULL,
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.helsedirektoratet.no/retningslinjer/demens/botilbud-ved-demens',
 '[2026-07-19 non-english-research-recovery] Primary helsedirektoratet.no pages blocked to direct WebFetch this session (proxy/gateway issue affecting many unrelated hosts). Verified via WebSearch synthesis corroborated across the Helsedirektoratet site itself, the Helsebiblioteket mirror, and the NAKU national competence-centre knowledge bank, all describing consistent content and structure. First published 16 Aug 2017; continuously/asynchronously revised ("levende retningslinje" format) -- most recently updated sub-sections dated Jan-Feb 2024 per different mirrors; no single fixed "latest edition" date exists by design.',
 'Recovered per research-handoff-non-english.md Tier-1 (wayfinding-dementia-spatial-design, NO, 10 non-EN hits).',
 'Contains genuine built-environment guidance nested in a clinical guideline: recommends physical surroundings that provide structure/activity/stimulation/cognitive support; single rooms (2-bed only for couples) with sized ensuite toilets for bedridden care; endorses small home-like units (~8 residents, per a cited 2015 SINTEF report) for staff oversight. Tier set to 2 (Co-2-adjacent national clinical guideline, not a T4-6 statutory code) per governance/tier-system.md.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'),

('REF-00744', 'standard', NULL, 0, 1, 'State Administration for Market Regulation (SAMR) / Standardization Administration of China (SAC), proposed by Ministry of Civil Affairs',
 2025, 'GB/T 46401—2025《养老机构认知障碍老年人照护指南》(Care Guide for Elderly with Cognitive Impairment in Senior Care Institutions)',
 'SAMR / SAC, drafted with Guangzhou Municipal Elderly Care Service Center', 'zh', 'zh', 'manual_native_language_verification',
 6, 'code', 'CN', 'GB/T 46401-2025',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'http://www.thnet.gov.cn/attachment/7/7911/7911657/10491690.pdf',
 '[2026-07-19 non-english-research-recovery] Primary PDF and openstd.samr.gov.cn returned 403 to direct WebFetch this session (proxy/gateway issue, consistent with other CN government domains blocked the same session). Verified via a government-hosted PDF mirror (thnet.gov.cn) carrying authentic ICS/CCS front matter plus two independent Guangzhou state-media outlets (Yangcheng Evening News, Guangzhou Daily group) describing the same standard number and 2025-10-05 effective date consistently.',
 'Recovered per research-handoff-non-english.md Tier-1 (wayfinding-dementia-spatial-design, ZH, 11 non-EN hits).',
 'A national recommended standard (GB/T, non-mandatory) -- China''s first national standard specifically for institutional cognitive-impairment care. Explicitly addresses environment/space design (optimizing physical space, facilities, and orientation-supportive/wayfinding-relevant design) alongside staffing and clinical-care protocols, adapted from Guangdong-Hong Kong-Macau Greater Bay Area institutional practice. Tier set to 6 (national code, matching this DB''s existing GB-standard convention) though GB/T is technically non-mandatory-recommended rather than fully statutory -- flagged for reverification alongside the GB 50763 cluster''s currency check.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery'),

('REF-00745', 'guideline', 4, 1, 0, 'Rappe E, Kotilainen H, Rajaniemi J, Topo P',
 2018, 'Muisti- ja ikäystävällinen asuminen ja asuinympäristö (Ympäristöopas 2018) — Memory- and Age-Friendly Housing and Residential Environment',
 'Ympäristöministeriö (Finnish Ministry of the Environment)', 'fi', 'fi', 'manual_native_language_verification',
 2, 'clinical', 'FI', NULL,
 'COMPLETE', 'VERIFIED-2', 'https://julkaisut.valtioneuvosto.fi/handle/10024/161060',
 '[2026-07-19 non-english-research-recovery] julkaisut.valtioneuvosto.fi blocked to direct WebFetch this session (proxy/gateway issue, confirmed via /__agentproxy/status connect_rejected on many unrelated hosts same session). Verified via the Valto publication-archive handle record and Ikäinstituutti''s own announcement page, both giving consistent title/publisher/year/ISBN. CORRECTION to the search_languages notes: publisher is Ympäristöministeriö (Ministry of the Environment), not Valtioneuvoston kanslia (PMO) -- Valto is a shared cross-ministry archive, not PMO-specific. Author list corrected to FOUR authors (Rappe, Kotilainen, Rajaniemi, Topo); the search notes named only two. The claimed "6-chapter" structure could not be confirmed (primary PDF unreachable this session) -- not asserted here.',
 'Recovered per research-handoff-non-english.md Tier-1 (wayfinding-dementia-spatial-design, FI, 9 non-EN hits).',
 'Government guide on memory- and age-friendly housing/residential environments: residential areas, courtyards, buildings, apartments; assistive technology for independent living; a memory/age-friendly planning checklist. ISBN 978-952-11-4806-4 / URN:ISBN:978-952-11-4806-4.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery');

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note)
VALUES
 ('REF-00738', 'deaf-classroom-reverberation-time', 'DCR-08', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Finnish acoustic classification standard; class C = regulatory-referenced minimum (~0.6-0.8s classroom RT).'),
 ('REF-00739', 'deaf-classroom-reverberation-time', 'DCR-09', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'French classroom-noise regulation; the correct FR citation (search-notes NF S31-080 candidate does not cover classrooms -- corrected during verification).'),
 ('REF-00740', 'deaf-classroom-reverberation-time', 'DCR-10', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Italian classroom acoustic requirements (RT<=1.2s furnished classroom); the actual source of the school-RT limit, distinct from DPCM 5/12/1997 which sets general building acoustics.'),
 ('REF-00741', 'deaf-classroom-reverberation-time', 'DCR-11', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Swedish school-acoustics standard referenced by BBR; corrected to the 2023 retitled edition.'),
 ('REF-00742', 'deaf-classroom-reverberation-time', 'DCR-12', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Dutch voluntary ambition guideline; three-tier classroom RT system, distinct from the legally-mandated NO/FR/IT/CN/DE tier.'),
 ('REF-00743', 'wayfinding-dementia-spatial-design', 'WDS-11', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Norwegian national dementia guideline with a dedicated housing/built-environment sub-guideline.'),
 ('REF-00744', 'wayfinding-dementia-spatial-design', 'WDS-12', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'China''s first national standard for institutional cognitive-impairment care, includes environment/space design provisions.'),
 ('REF-00745', 'wayfinding-dementia-spatial-design', 'WDS-13', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery', 'Finnish government guide on memory- and age-friendly housing/residential environment design.');

COMMIT;