-- data_20260525021500_b11_srb_supersession_audit.sql
-- DR-2026-05-24 Pass 2: SRB retroactive supersession audit (stair-ramp-threshold-biomechanics-accessibility)
-- 15 anchors audited (1 T4 standard + 14 T3 clinical/grey)
-- Distribution: 12 current_best + 3 refined_by. 0 superseded_by, 0 divergent, 0 pending.
-- Key refinement: Tanaka 2025 (doi 10.1007/s40520-025-02929-5) stair-descent phenotype clustering
--   refines 3 anchors (SRB-02 Simoneau 1991 visual factors, SRB-05 Pavol 2001 lower extremity fall, SRB-13 Ram 2024).
-- Templer 1992 (SRB-01) remains foundational stair-design reference; no comprehensive replacement.
-- No Co-1 anchors in this slug, so Co-1 supersession-treatment owner decision not required.

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-ae6100b1fd77', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-01', 'REF-00383', 4, 'standard_eb', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "web_search_composite", "query": "stair geometry riser tread fall safety systematic review 2020-2025", "date_filter": "published_after:2015", "candidates_returned": 8, "candidates_reviewed": 5}', 8, 5, '2026-05-25T03:04:48Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Templer 1992 The Staircase monograph remains the foundational stair-safety design reference, cited by all 2019-2025 stair-fall biomechanics literature surveyed (Francksen 2020/2022, Harper 2025, Foster 2019). Post-Templer work adds incremental refinements on inter-step variation tolerances and contrast cues but no comprehensive replacement of the design framework. Current best for stair-design parameter-space; flagged for jurisdiction-tracker handoff because incorporation into specific codes (IBC, ADA, OSHA 1910.25) is downstream regulatory question.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-6a3c6e6bef61', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-02', 'REF-00384', 3, 'clinical', 'refined_by', NULL, '["10.1007/s40520-025-02929-5"]', 'Kinematic phenotype refinement: Tanaka 2025 identifies 3 stair-descent phenotypes (N/E/R-type) in 82 community-dwelling older adults via hierarchical cluster analysis, refining the descent-kinematic-variables evidence base. Anchor Simoneau 1991 governs the visual-factors-on-fall-kinematics mechanism; new evidence adds phenotype-level pattern recognition.', NULL, '{"tool": "pubmed_search", "query": "stair descent fall older adults biomechanics", "date_filter": "published_after:2020", "candidates_returned": 15, "candidates_reviewed": 3}', 15, 3, '2026-05-25T03:04:49Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'pubmed_search', 'Tanaka et al 2025 doi 10.1007/s40520-025-02929-5 Aging Clin Exp Res phenotype clustering refines kinematic interpretation.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-d16e75de21f0', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-03', 'REF-00385', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search", "query": "walking energy expenditure standard tables", "date_filter": "published_after:2020", "candidates_returned": 0, "candidates_reviewed": 0}', 0, 0, '2026-05-25T03:04:49Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Waters 1988 walking energy-speed standard tables remain foundational physiological reference. No comprehensive update or replacement table found in 2020-2025 search; the gait-energy literature has added gait-pathology-specific work but not replaced the typical-population baseline tables.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-fabaf75bf303', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-04', 'REF-00386', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search", "query": "manual wheelchair ramp slope propulsion", "date_filter": "published_after:2020", "candidates_returned": 0, "candidates_reviewed": 0}', 0, 0, '2026-05-25T03:04:49Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'pubmed_search', 'Kim 2014 ramp-slope + height + pushing-force wheelchair performance. No newer primary work in 2020-2025 PubMed search on the same parameter triple. Anchor current best by absence of replacement.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-6175bce0ae7e', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-05', 'REF-00387', 3, 'clinical', 'refined_by', NULL, '["10.1007/s40520-025-02929-5"]', 'Phenotype + strength dimension: Tanaka 2025 found stair-descent phenotypes correlate with muscle-strength factor (CB&M strength sub-score); refines the lower-extremity-strength fall-risk mechanism Pavol 2001 anchored. Anchor still governs the broader lower-extremity-fall-likelihood relationship.', NULL, '{"tool": "pubmed_search", "query": "stair descent fall older adults biomechanics", "date_filter": "published_after:2020", "candidates_returned": 15, "candidates_reviewed": 3}', 15, 3, '2026-05-25T03:04:49Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'pubmed_search', 'Same Tanaka 2025 candidate as SRB-02. Refinement applies to the muscle-strength-fall-risk mechanism dimension.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-42f20fe88f7e', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-06', 'REF-00025', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search_composite", "query": "cluster: wheelchair_propulsion", "date_filter": "published_after:2020", "candidates_returned": 2, "candidates_reviewed": 2}', 2, 2, '2026-05-25T03:05:08Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Lawati 2017 manual wheelchair threshold momentum method. No newer primary work surfaced in wheelchair-threshold-propulsion search; specialized intervention study remains current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-30fe243e00d2', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-07', 'REF-00388', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search_composite", "query": "cluster: wheelchair_propulsion", "date_filter": "published_after:2020", "candidates_returned": 2, "candidates_reviewed": 2}', 2, 2, '2026-05-25T03:05:08Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Koontz 2012 backrest height wheelchair propulsion biomechanics. No newer primary work surfaced; specialized backrest-height parameter study remains current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-bcc8d6d42a91', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-08', 'REF-00389', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search_composite", "query": "cluster: sit_to_stand", "date_filter": "published_after:2020", "candidates_returned": 2, "candidates_reviewed": 2}', 2, 2, '2026-05-25T03:05:08Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Rodosky 1989 chair height STS lower limb mechanics. 36-year-old anchor; no comprehensive replacing SR found in 2020-2025 PubMed search. The post-2020 STS literature has 20+ primary studies but no synthesis that supersedes the foundational chair-height-mechanics relationship. Current best by absence of superseding SR.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-2ad0d447c461', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-09', 'REF-00390', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search_composite", "query": "cluster: sit_to_stand", "date_filter": "published_after:2020", "candidates_returned": 2, "candidates_reviewed": 2}', 2, 2, '2026-05-25T03:05:08Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Lord 1993 STS performance multifactor sensation balance psych. Foundational multifactor framework; no comprehensive multifactor SR found in 2020-2025. Recent STS work has addressed specific factors but not replaced the multifactor framework. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-3f5d71eb8a3c', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-10', 'REF-00391', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search_composite", "query": "cluster: grab_bar_sts", "date_filter": "published_after:2020", "candidates_returned": 2, "candidates_reviewed": 2}', 2, 2, '2026-05-25T03:05:08Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Levine 2025 grab bar grasp bathtub STS. Already 2025; current state-of-the-literature. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-efd2e6058a62', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-11', 'REF-00392', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search_composite", "query": "cluster: tiadl", "date_filter": "published_after:2020", "candidates_returned": 2, "candidates_reviewed": 2}', 2, 2, '2026-05-25T03:05:08Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Owsley 2001 TIADL tasks. Methodological-instrument primary study; no superseding TIADL development surfaced. Current best for its measurement focus.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-58c3bf767f82', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-12', 'REF-00393', 3, 'grey', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search_composite", "query": "cluster: luminance_contrast", "date_filter": "published_after:2020", "candidates_returned": 2, "candidates_reviewed": 2}', 2, 2, '2026-05-25T03:05:08Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Manandhar 2022 luminance contrast preferences vision impairment. Recent (3 years) grey-lit; cluster searches surfaced Harper 2025 contrast striping work but on different parameter (interstep variation cue not preference). Current best for its specific user-preference focus.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-877ba04e347c', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-13', 'REF-00394', 3, 'clinical', 'refined_by', NULL, '["10.1007/s40520-025-02929-5"]', 'Phenotype-clustering analysis adds to controlled-lab-vs-real-stair fall-risk-parameters evidence: Tanaka 2025 hierarchical cluster analysis identifies 3 phenotypes in a separate 82-participant cohort using lab measurement, complementing Ram 2024 prospective faller/non-faller methodology. Anchor still governs the lab-vs-home environment-specific risk parameter comparison; refinement adds phenotype-stratification dimension.', NULL, '{"tool": "pubmed_search", "query": "stair descent fall older adults biomechanics", "date_filter": "published_after:2024", "candidates_returned": 15, "candidates_reviewed": 3}', 15, 3, '2026-05-25T03:05:23Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'pubmed_search', 'Tanaka 2025 phenotype clustering adds analytic dimension to Ram 2024 lab-vs-real comparison.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-f180d84ceadf', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-14', 'REF-00395', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search", "query": "interstep variations high contrast striping fall", "date_filter": "published_after:2025", "candidates_returned": 0, "candidates_reviewed": 0}', 0, 0, '2026-05-25T03:05:23Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Harper 2025 interstep variations contrast striping anchor. Published 2025; no superseding work in subsequent literature. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-60ca1b49109f', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-15', 'REF-00396', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "pubmed_search", "query": "safety perception fall risk older adults stairs", "date_filter": "published_after:2025", "candidates_returned": 0, "candidates_reviewed": 0}', 0, 0, '2026-05-25T03:05:23Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Wharton 2025 perception-vs-actual safety anchor. Published 2025; perceptions/qualitative research focus. Current best.');

UPDATE bpc_metadata
   SET supersession_check_complete = 1,
       closure_definition_version = 'v2',
       updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
       updated_by_session = 'session_2026-05-23-bpc-rewrite-phase-b-closure'
 WHERE slug = 'stair-ramp-threshold-biomechanics-accessibility';

COMMIT;
