-- data_20260802222709_2026-08-02-w5-2-processing-state.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-02-w5-2-processing-state
-- Generated:  2026-08-02T22:27:09+00:00
-- Summary:    de-conflate value columns into paired overflows
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- De-conflate value columns using the paired overflows from migration 041.
-- Hypotheses, comments and qualifiers go to the overflow; the value column keeps
-- only a value, or NULL. Nothing is discarded.

-- (1) Restore two authors the previous migration destroyed. Both were
--     recoverable from inside this database: REF-00100 from
--     evidence_source_authors position 1, REF-00310 from author_display.
--     They were not "real gaps becoming visible" — they were gaps I created.
UPDATE evidence_sources
   SET first_author_last = (SELECT a.last_name FROM evidence_source_authors a
                            WHERE a.ref_id = evidence_sources.ref_id AND a.position = 1)
 WHERE ref_id = 'REF-00100';
UPDATE evidence_sources SET first_author_last = 'Erdtman' WHERE ref_id = 'REF-00310';

-- (2) author_display: a state or a hedge is not a display name.
UPDATE evidence_sources
   SET author_display_note = author_display, author_display = NULL
 WHERE author_display LIKE '[%' OR author_display LIKE '%pending%'
    OR author_display LIKE '%TBC%' OR author_display LIKE '%Unknown (%';

-- (3) publisher: '[Pending — likely X or Y]' is a hypothesis, not a publisher.
UPDATE evidence_sources
   SET publisher_note = publisher, publisher = NULL
 WHERE publisher LIKE '[%' OR publisher LIKE '%pending%' OR publisher LIKE '%TBC%';

-- (4) standard_number: copy EVERY value into the overflow first, so no prose is
--     lost whichever way the split falls, then clear the value column only where
--     the content cannot be an identifier. The conservative test is a leading
--     identifier pattern; anything that starts with one keeps its value, and its
--     qualifier survives in the overflow. This deliberately errs toward keeping
--     values: the previous attempt cleared 'BS 6440:2011 (supersedes …)' on a
--     length heuristic, which is exactly the mis-split an overflow exists to
--     make unnecessary.
UPDATE evidence_sources SET standard_number_note = standard_number
 WHERE COALESCE(standard_number,'') <> '' AND LENGTH(standard_number) > 40;

UPDATE evidence_sources SET standard_number = NULL
 WHERE COALESCE(standard_number,'') <> ''
   AND LENGTH(standard_number) > 40
   AND standard_number NOT GLOB '[A-Za-z][A-Za-z]*[ /-][0-9]*';

-- (5) corporate_name: '[Authors TBC]' and '(review article)' are not names, and
--     G02 counts them as author rows.
UPDATE evidence_source_authors
   SET corporate_name_note = corporate_name, corporate_name = NULL
 WHERE corporate_name LIKE '[%' OR corporate_name LIKE '%TBC%'
    OR corporate_name LIKE '%Unknown (%' OR corporate_name = '(review article)';

COMMIT;
