-- data_20260806222208_2026-08-06-clean-room-reset.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-06-clean-room-reset.md
-- Generated:  2026-08-06T22:22:08+00:00
-- Summary:    clean-room reset: set the evidence corpus aside, keep the frame
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Clean-room reset: the evidence corpus is set aside; the frame stays.
--
-- OWNER DECISION, 2026-08-06. The project proceeds as though no research has
-- been performed. What survives is the FRAME the owner defined: research topics
-- (slugs, organised by disability population / access need / functional
-- impairment against the built environment), languages, aliases and
-- terminologies within languages, and jurisdictions national and international.
-- Plus the code values in jurisdictional_values, which are cited correctly for
-- their class (standard_name + source_section, exactly what R3 requires of
-- codes) and are therefore NOT research output to be discarded.
--
-- WHY. Not because the work was poor, but because the corpus could not show its
-- work: 824 of 863 sources had no recorded admission, 15 of 2,139 cells were
-- determined, 3 of 61 governing references carried a population grade, and no
-- published best practice could be walked back to the search that found it. A
-- corpus that cannot show its work is reference, not assertion.
--
-- NOTHING IS LOST. The full pre-reset database is preserved twice:
--   * branch `archive/pre-reset-corpus-2026-08-06` (authoritative)
--   * `_archived/data/corpus-pre-reset-2026-08-06.db` (queryable without
--     checkout; named so no tool resolves it and repo-wide search skips it)
-- The file surfaces (references/bpc/**, bpc-reasoning/**, connections/**,
-- site/, parts/) are untouched and remain as reference.
--
-- Deletions are ordered child-before-parent so foreign keys hold throughout.
-- Row counts are as measured immediately before this migration was emitted.

DELETE FROM bpc_metadata;   -- 83 rows
DELETE FROM case_study_outcomes;   -- already empty
DELETE FROM case_study_populations;   -- already empty
DELETE FROM case_study_specs;   -- already empty
DELETE FROM case_study_strategies;   -- already empty
DELETE FROM cell_source_links;   -- 61 rows
DELETE FROM citation_mining;   -- 183 rows
DELETE FROM citation_population_links;   -- 7 rows
DELETE FROM conflicts;   -- already empty
DELETE FROM connection_targets;   -- 507 rows
DELETE FROM economics_entry_populations;   -- already empty
DELETE FROM economics_entry_specs;   -- already empty
DELETE FROM evidence_population_match;   -- 64 rows
DELETE FROM evidence_source_authors;   -- 1478 rows
DELETE FROM external_root_registry;   -- already empty
DELETE FROM extraction_population_links;   -- already empty
DELETE FROM gap_mining;   -- already empty
DELETE FROM item_audit_runs;   -- 87 rows
DELETE FROM item_bpc_links;   -- 3 rows
DELETE FROM probe_population_links;   -- 36 rows
DELETE FROM search_admissions;   -- 39 rows
DELETE FROM search_candidates;   -- 18 rows
DELETE FROM search_coverage;   -- 4960 rows
DELETE FROM search_languages;   -- 1558 rows
DELETE FROM situations;   -- already empty
DELETE FROM source_slug_links;   -- 1011 rows
DELETE FROM supersession_check;   -- 134 rows
DELETE FROM connections;   -- 273 rows
DELETE FROM convergence_assessment;   -- 14 rows
DELETE FROM evidence_cell_state;   -- 15 rows
DELETE FROM source_value_extractions;   -- 8 rows
DELETE FROM spec_value_probes;   -- 31 rows
DELETE FROM economics_entries;   -- 5 rows
DELETE FROM reasoning_doc_citations;   -- 14 rows
DELETE FROM search_executions;   -- 84 rows
DELETE FROM gaps;   -- 313 rows
DELETE FROM case_studies;   -- already empty
-- item_population_elaborations: the frame/research line runs THROUGH this table,
-- not around it. It records THAT an (item x population) pair has distinct spec
-- variants — a manual vs a power wheelchair need different landing depths; reach
-- envelope changes with upper-limb involvement. That is taxonomy and it stays.
-- WHAT the number is, and which source says so, is research and it goes.
-- Rows 1-3 carry no ref and no value: kept. Rows 4-6 cite REF-00325/00561/00735.
-- Row 7 carries an RT60 value sourced to code convergence rather than a ref_id,
-- so it broke no key — same class of claim, removed on the same principle rather
-- than left behind for being invisible to the constraint.
-- These run BEFORE the evidence_sources delete: a two-migration fix-forward left
-- an intermediate state with 3 FK violations, which migrate_db's per-migration
-- foreign_key_check correctly refused on replay.
DELETE FROM item_population_elaborations WHERE evidence_ref_id IS NOT NULL;
DELETE FROM item_population_elaborations WHERE item_code='A-18' AND population_code='ALL';

DELETE FROM evidence_sources;   -- 863 rows

COMMIT;
