-- data_20260803032904_2026-08-03-adversarial-corrections.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-03-adversarial-corrections
-- Generated:  2026-08-03T03:29:04+00:00
-- Summary:    drop overflow notes that duplicate their value column
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Remove overflow notes that merely duplicate their value column.
--
-- Migration 041's de-conflation copied EVERY standard_number over 40 chars into
-- standard_number_note (147 rows) and then cleared only 19 of the value columns.
-- The other 128 rows hold the note byte-identical to the value: the overflow
-- adds nothing, and the value column still carries the conflated prose the
-- exercise was meant to separate. Duplication is not de-conflation.
--
-- The 128 remain conflated and are left visible rather than split by another
-- heuristic — the last heuristic split lost a real identifier.
UPDATE evidence_sources SET standard_number_note = NULL
 WHERE standard_number_note IS NOT NULL
   AND standard_number_note = standard_number;

COMMIT;
