-- data_20260812083218_2026-08-12-specification-rename.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    2026-08-12-specification-rename
-- Generated:  2026-08-12T08:32:18+00:00
-- Summary:    record D-0158 (specification rename + AFTER_DATA replay order) in the canonical decisions table
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Mirror D-0158 into the canonical `decisions` table.
-- The register YAML and this table are held equal by test_db_integrity L01 in both
-- directions; a DR landing in only one of them fails that check.
-- List fields are JSON-encoded here, matching every existing row.

INSERT INTO decisions (decision_id, category, delegation, delegation_rationale, summary, outcome, rationale, decision_date, decided_by, model_routing, effort_level, status, review_status, supersedes, predecessors, decision_artifacts, alternatives_considered, notes, created_at, created_by_session, updated_at, updated_by_session)
VALUES (
  'D-0158',
  'D-SCHEMA',
  'DG-NON',
  'Owner directive of 2026-08-12 named the rename outright; the session captured owner-directed naming rather than originating it. The replay-order half is mechanism forced by that naming, recorded in the same decision.',
  'Rename the (item x population) determination from `cell` to `specification` (evidence_cell_state -> specifications, cell_source_links -> specification_source_links, cell_id -> specification_id), and give migration replay a way to express the real chronology so the rename does not permanently wall the two tables off from the numbered schema phase.
',
  'ADOPTED by owner directive 2026-08-12 ("product cell as (item x population) is confusing terminology. rename to specification"). Executed: schema version 055 as a version marker, its DDL in the paired data migration data_20260812075349_2026-08-12-rename-cell-to-specification.sql, and schema version 056 carrying an AFTER_DATA marker that reopens the numbered schema phase on the post-rename names. Both tables held 0 rows, so no row moved. From 057 onward, ordinary numbered schema migrations may name `specifications` and `specification_source_links` normally.
',
  '"Cell" was the matrix framing and collided with the vocabulary already in use everywhere else (spec_page.py, spec_value_probes, case_study_specs, economics_entry_specs, specs/) and with the Specification layer that armature_v4_resolutions.md reserves by name. The replay half was forced, not chosen: migrate_db.py applied all schema migrations before any data migration, and 19 committed immutable data migrations still write the old names, so a schema-phase rename broke `--rebuild` with `no such table: evidence_cell_state`. Migration 025 records the same collision from the other side.
',
  '2026-08-12 08:40',
  'owner_jordanelias_directive_2026-08-12',
  'opus/200/arbitrate',
  200,
  'ACTIVE',
  'NA',
  '[]',
  '["D-0157"]',
  '["decisions/DR-2026-08-12-specification-rename-and-replay-order.md", "workplan/2026-08-12-step-R-rename-execution-record.md"]',
  '(1) Rename in the schema phase and accept a broken rebuild - refused, a permanently red blocking gate is a disarmed gate. (2) Withdraw or rewrite the 19 old-name data migrations - refused, they are append-only and immutable. (3) Leave the DDL in the data phase with the invariant only documented - refused, it walls the two central tables off from the numbered schema phase forever and turns every future constraint into a data migration. (4) A compatibility view named evidence_cell_state with INSTEAD OF triggers - refused, its fidelity is unverifiable in the direction that matters and it returns a dead name to sqlite_master. (5) A schema+data baseline squash - deferred, not refused: it is the larger clean answer, needs a runner change for data-migration supersession that does not exist, and is a separate owner decision. AFTER_DATA does not foreclose it.
',
  'Enforcement is mechanical, not remembered: evidence_cell_state and cell_source_links are RV-020/RV-021 in governance/retired-vocabulary.yaml at severity `broken`, so the residual sweep is a standing check. cell_id is recorded in that file''s `rejected:` section - it fails admission test 4 because architecture/schema-spec.md''s aspirational `cell` table declares its own cell_id and no regex separates the two.
',
  '2026-08-12 08:40',
  'session_2026-08-12-specification-rename',
  '2026-08-12 08:40',
  'session_2026-08-12-specification-rename'
);

COMMIT;
