-- data_20260804175506_2026-08-04-hop4-item-edge.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-04-hop4-item-edge
-- Generated:  2026-08-04T17:55:06+00:00
-- Summary:    backfill source_value_extractions.item_code (8 rows -> A-18, three witness classes)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Backfill source_value_extractions.item_code — all 8 rows resolve to A-18.
--
-- THE STANDARD THIS IS HELD TO
-- From data_20260804161658 (the D-0157 remap): "a value is written only where
-- the row itself already supplies it. Where a row does not evidence its own
-- method, the method stays NULL — an honest queue, not a guess dressed as a
-- backfill." That standard was enforced against me three days' work ago:
-- data_20260804164915 reverted three assignments I had made from a mapping
-- table instead of from the rows.
--
-- So the witness for every row below is named and quoted, and the rows fall
-- into three classes of decreasing directness. The classes are recorded rather
-- than flattened, because "all 8 → A-18" is true but hides that they are not
-- all known the same way.
--
-- WHAT WAS NOT USED AS A WITNESS
-- "The slug's primary item_bpc_links row plus parameter='RT60'" resolves to
-- A-18 uniquely today — and only because A-10b has no link yet. Step 9 is
-- expected to give it one. A witness with an expiry date is not a witness, and
-- text-matching `parameter` is the fuzzy hop this column exists to replace.
-- Using it here would reproduce the D-0157 mapping-table error in the next
-- migration after the one that corrected it.

-- ── W1: typed key on the row ───────────────────────────────────────────────
-- extraction 1's root_classification_basis contains "PMP-A18-001-F
-- strict-termination PASS at 0.3 s (gap_signed 0.00, REF-00325 anchor)".
-- spec_value_probes.probe_id='PMP-A18-001-F' carries item_code='A-18' in a
-- NOT NULL FK column. The row names a typed object; the object names the item.
UPDATE source_value_extractions
   SET item_code = 'A-18',
       updated_at = '2026-08-04 18:05',
       updated_by_session = 'session_2026-08-04-hop4-item-edge'
 WHERE extraction_id = 1;

-- ── W2: typed join, one hop from the row ───────────────────────────────────
-- extraction 2 carries root_id='root-rt60-deaf-iglehart' and
-- root_ref_id='REF-00325' — identical to extraction 1's — and describes itself
-- as a "Standards echo of the Iglehart measurement line". Same root, same item.
UPDATE source_value_extractions
   SET item_code = 'A-18',
       updated_at = '2026-08-04 18:05',
       updated_by_session = 'session_2026-08-04-hop4-item-edge'
 WHERE extraction_id = 2;

-- extraction 3 (REF-00561, AUT) is governed by exactly one cell:
-- cell_source_links(9011, 'REF-00561', 'governing'), and cell 9011 is
-- (item_code='A-18', population_code='AUT', state='provisional'). The synthesis
-- edge already made this call; this reads it rather than repeating it. Worth
-- naming: on claim text alone a "daily-care facility" is not self-evidently a
-- learning space, so without the cell this row would have stayed NULL.
UPDATE source_value_extractions
   SET item_code = 'A-18',
       updated_at = '2026-08-04 18:05',
       updated_by_session = 'session_2026-08-04-hop4-item-edge'
 WHERE extraction_id = 3;

-- ── W3: row-supplied locator, dereferenced ─────────────────────────────────
-- extractions 4–8 carry no typed object naming an item. What each DOES carry is
-- a file_anchor — a locator the row itself supplies — into
-- references/bpc-reasoning/room-acoustic-performance.md, at the Step 3
-- jurisdiction-comparison table. That document's subject item is established at
-- its line 92: "A-18 authored under standing rule #3 Change Order with 4
-- population elaborations (closes GAP-282)"; the whole document is the A-18
-- rule-#9 walk. Each row's claimed value was checked against its own anchored
-- Step 3 row and matches.
--
-- This is dereferencing a locator the row provides, not inferring from a table
-- the row never mentions — which is the line the D-0157 standard draws. One
-- dereference step is required (anchor names the section; the section's item is
-- established at doc line 92), and that step is stated here rather than hidden.
--
--   4  REF-00563 US 0.6      anchor "#step-3 (US) + step-7"  → doc:131 US row,
--                            "RT60 ≤ 0.6 s (≤ 283 m³)"
--   5  REF-00562 UK 0.6–0.8  anchor "#step-3 (UK) + REF-00562 Table 6" → doc:132
--                            UK row (0.4–0.8 by room type; the 0.4 floor is the
--                            specially-resourced HI value, which is why the row
--                            records general as 0.6–0.8 — its own note says so)
--   6  REF-00329 DE 0.4–0.8  anchor "#step-3 (DE)" → doc:134 DE row, "target
--                            curve typically 0.4–0.8 s"
--   7  REF-00564 IT 0.5      anchor "#step-3 (IT)" → doc:135 IT row, "A4
--                            (high-criticality educational) ≈ 0.5 s"
--   8  REF-00574 AU/NZ       anchor "#step-3 (AU/NZ)" → doc:137 AU/NZ row,
--             0.4–0.6        "typical classroom 0.4–0.6 s"
--
-- The competing item is excluded on the same evidence: A-10b is hydrotherapy
-- and pool environments, and every one of these five rows is scoped to
-- classrooms, teaching spaces or learning spaces in its own claim_text.
UPDATE source_value_extractions
   SET item_code = 'A-18',
       updated_at = '2026-08-04 18:05',
       updated_by_session = 'session_2026-08-04-hop4-item-edge'
 WHERE extraction_id IN (4, 5, 6, 7, 8);

COMMIT;
