-- data_20260724193523_2026-07-24-research-matrix-completion.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-research-matrix-completion
-- Generated:  2026-07-24T19:35:23+00:00
-- Summary:    batch 9: first real ID-language searches unblocked by Phase-0 vocabulary (2 new cells, non-mirror local findings, candidates staged)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Batch 9 (Phase-0 proof-of-unblock): first REAL Indonesian-language searches, enabled by the
-- ID vocabulary built this session. These are NEW cells (ID x id) on slugs previously covered
-- only in EN, so no duplication. Both are genuine non-mirror results: ID-language academic
-- studies of local implementation failure that do not surface in English search.
-- No source admitted: ID university eprints/journal PDFs lack DOIs and full metadata in-snippet;
-- staged as candidates pending locator+metadata verification (citation discipline).
INSERT INTO search_executions (slug,jurisdiction,language,target_tier,target_evidence_type,target_scope,query_text,engine,depth_method,mining_direction,results_found,results_screened,results_admitted,saturation_signal,admitted_ref_ids,deferred_reason,backfill,session,executed_at) VALUES
('detectable-gradient-protocol-sensory-zones','ID','id',3,'grey','national','"ubin pemandu" penelitian evaluasi jalur pemandu tunanetra trotoar Indonesia studi','web','scoping','none',8,6,0,'partial',NULL,NULL,0,'session_2026-07-24-research-matrix-completion','2026-07-24T19:35:00+00:00'),
('accessible-circulation-geometry','ID','id',3,'grey','national','lift aksesibilitas pengguna kursi roda difabel bangunan gedung penelitian standar Indonesia','web','scoping','none',8,6,0,'partial',NULL,NULL,0,'session_2026-07-24-research-matrix-completion','2026-07-24T19:35:00+00:00');
-- Record the substantive findings on the vocabulary rows' provenance trail (notes on the cells):
UPDATE search_executions SET deferred_reason = NULL, saturation_signal='partial'
 WHERE slug='detectable-gradient-protocol-sensory-zones' AND language='id';

COMMIT;
