-- data_20260804161658_2026-08-04-d0157-remap.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-04-d0157-remap
-- Generated:  2026-08-04T16:16:58+00:00
-- Summary:    D-0157: remap 863 rows onto standing/disposition/method columns; clear metadata_quality junk; I2 counter backfill (tool-witnessed only)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- D-0157 standing remap: 863 rows onto the columns migration 049 added.
--
-- Implements decisions/DR-2026-08-04-verification-status-is-a-standing-not-a-history.md
-- section 5 (ADOPTED 2026-08-04). After this, verification_status holds two
-- values; how and how-hard live in their own columns; and the tuple can be
-- checked against itself.
--
-- THE RULE GOVERNING EVERY WRITE BELOW: a value is written only where the row
-- itself already supplies it. Where a row does not evidence its own method, the
-- method stays NULL -- an honest queue for the audit DR section 6 defers, not a
-- guess dressed as a backfill. 201 VERIFIED rows land that way deliberately.

-- 1. VERIFIED (750) -> VERIFIED + CLOSED. Method from the row's own witness.
--    Co-1 first: 41 rows carry verified_by_tool='co1-manual-pre-pipeline'.
--    Under section 3.1 the artefact obtained is the attestation, not a
--    publication; without this clause the definition of VERIFIED would demote
--    every Co-1 source in the corpus, which are co-primary with T1 under
--    CRPD Art. 4.3.
UPDATE evidence_sources
   SET verification_disposition='CLOSED', verification_method='co1-attestation',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status='VERIFIED' AND verified_by_tool LIKE 'co1%';

--    508 remaining tool-witnessed rows.
UPDATE evidence_sources
   SET verification_disposition='CLOSED', verification_method='tool',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status='VERIFIED' AND verified_by_tool IS NOT NULL
   AND verified_by_tool!='' AND verified_by_tool NOT LIKE 'co1%';

--    201 rows with no tool witness: standing preserved, method left NULL.
--    These are the population the section 6 audit must read one at a time; some
--    will prove to be citing-bibliography and lose VERIFIED. Batch-guessing
--    'direct-render' here would be exactly the overclaim this DR exists to end.
UPDATE evidence_sources
   SET verification_disposition='CLOSED',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status='VERIFIED' AND (verified_by_tool IS NULL OR verified_by_tool='');

-- 2. VERIFIED-1 (1) and VERIFIED-WITH-CORRECTION (2) -> VERIFIED.
--    The first was coined for a direct document render; the second describes an
--    event already recorded in verification_note, not a standing.
UPDATE evidence_sources
   SET verification_status='VERIFIED', verification_disposition='CLOSED',
       verification_method='direct-render',
       verification_note=COALESCE(verification_note||' ','')||
         '[D-0157 REMAP 2026-08-04] Status was '||verification_status||
         '; standing is VERIFIED, method direct-render. Any correction recorded above stands.',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status IN ('VERIFIED-1','VERIFIED-WITH-CORRECTION');

-- 3. VERIFIED-2 (71) -> UNVERIFIED + OPEN. The material change.
--    These rows are honestly documented -- "real retrieval, not fabrication,
--    but one step removed from a direct render" -- and the document was never
--    obtained, so they are not verified. OPEN, not CLOSED: 13 record HTTP 403
--    and are candidates for closure, but each needs adjudicating individually.
--    Zero published cells cite one, so no cell state and no page changes.
UPDATE evidence_sources
   SET verification_status='UNVERIFIED', verification_disposition='OPEN',
       verification_method='corroborated-not-retrieved',
       verification_note=COALESCE(verification_note||' ','')||
         '[D-0157 REMAP 2026-08-04] Was VERIFIED-2. Existence and metadata were corroborated '||
         'across independent retrievals; the document itself was not obtained, so the standing '||
         'is UNVERIFIED with method corroborated-not-retrieved. OPEN: a return pass is owed.',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status='VERIFIED-2';

-- 4. UNVERIFIED-1 (31) -> UNVERIFIED + OPEN. Attempt counts already hold the
--    truth the suffix mis-stated (25 of 31 record zero attempts); they are left
--    exactly as they are.
UPDATE evidence_sources
   SET verification_status='UNVERIFIED', verification_disposition='OPEN',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status='UNVERIFIED-1';

-- 5. DISPUTED (7) -> UNVERIFIED + OPEN, NOT closed.
--    disputed-existence is the ratified closure reason for these, but invariant
--    I3 requires attempt_count >= 2 and none of the seven records it. Writing
--    CLOSED here would assert an effort the counter denies -- the precise
--    failure that condemned UNVERIFIED-1. They close in a later migration that
--    cites audits/anchor-correctness-sweep-2026-07-20.md as the witness.
UPDATE evidence_sources
   SET verification_status='UNVERIFIED', verification_disposition='OPEN',
       verification_note=COALESCE(verification_note||' ','')||
         '[D-0157 REMAP 2026-08-04] Was DISPUTED. Standing is UNVERIFIED. The ratified closure '||
         'reason disputed-existence applies, but cannot be written until verification_attempt_count '||
         'reflects the two independent retrievals the 2026-07-20 sweep performed (I3).',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status='DISPUTED';

-- 6. SUPERSEDED (1, REF-00844) -> the pointer is the record.
--    superseded_by_ref_id is non-null, which is the lifecycle fact; the status
--    column was carrying it a second time. No tool witness and no evidence of
--    retrieval on this row, so the honest standing is UNVERIFIED + OPEN.
UPDATE evidence_sources
   SET verification_status='UNVERIFIED', verification_disposition='OPEN',
       verification_note=COALESCE(verification_note||' ','')||
         '[D-0157 REMAP 2026-08-04] Status was SUPERSEDED, which is a row-lifecycle fact already '||
         'recorded by superseded_by_ref_id, not a verification standing. This row carries no tool '||
         'witness and no evidence of retrieval, so its standing is UNVERIFIED.',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE verification_status='SUPERSEDED';

-- 7. metadata_quality PARTIAL (5) -> NULL. Section 4.5: it cross-cut three
--    different verification statuses, so it was never describing verification.
--    Its outstanding-work meaning is now carried by disposition=OPEN.
UPDATE evidence_sources
   SET metadata_quality=NULL,
       verification_note=COALESCE(verification_note||' ','')||
         '[D-0157 REMAP 2026-08-04] metadata_quality PARTIAL cleared; the outstanding-work meaning '||
         'is carried by verification_disposition=OPEN.',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE metadata_quality='PARTIAL';

-- 8. metadata_quality high/medium (4) -> NULL. Confidence vocabulary written
--    into the wrong column by a 2026-07-25 batch. Junk data, not a vocabulary
--    question.
UPDATE evidence_sources
   SET metadata_quality=NULL,
       verification_note=COALESCE(verification_note||' ','')||
         '[D-0157 REMAP 2026-08-04] metadata_quality held a confidence word (high/medium) rather '||
         'than a metadata-completeness value; cleared rather than guessed at.',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE metadata_quality IN ('high','medium');

-- 9. source_type grey_literature (2) -> grey. A spelling variant of the
--    canonical value, not a distinct type.
UPDATE evidence_sources
   SET source_type='grey',
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE source_type='grey_literature';

-- 10. Invariant I2 backfill, tool-witnessed rows only (138).
--     A row whose verified_by_tool names the tool that established it, with a
--     zero attempt count, is a counter that was never incremented -- bookkeeping,
--     not a lie. Set to 1. The 83 DOI-RESOLVED-without-tool rows and the 142
--     with no witness at all are NOT touched: those are adjudication under R10,
--     and the whole point of I2 is that it sorts them rather than hides them.
UPDATE evidence_sources
   SET verification_attempt_count=1,
       updated_at='2026-08-04 16:20', updated_by_session='session_2026-08-04-d0157-remap'
 WHERE COALESCE(verification_attempt_count,0)=0
   AND verified_by_tool IS NOT NULL AND verified_by_tool!='';

COMMIT;
