-- data_20260610222258_2026-06-09-stage2-5-tier-consistency.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-06-09-stage2.5-tier-consistency.md
-- Generated:  2026-06-10T22:22:58+00:00
-- Summary:    Stage 2.5 tier-consistency sweep: resolve 17 NULL-scope rows (11 tier fixes, 6 evidence_type corrections) per D-A
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

UPDATE evidence_sources SET scope='intrinsic', tier=3 WHERE ref_id='REF-00240';
UPDATE evidence_sources SET scope='intrinsic', tier=3 WHERE ref_id='REF-00242';
UPDATE evidence_sources SET scope='intrinsic', tier=3 WHERE ref_id='REF-00628';
UPDATE evidence_sources SET scope='intrinsic', tier=3 WHERE ref_id='REF-00379';
UPDATE evidence_sources SET evidence_type='national_fw', scope='intrinsic', tier=5 WHERE ref_id='REF-00734';
UPDATE evidence_sources SET scope='international', tier=4 WHERE ref_id='REF-VERIFIED-005';
UPDATE evidence_sources SET scope='international', tier=4 WHERE ref_id='REF-VERIFIED-006';
UPDATE evidence_sources SET scope='international', tier=4 WHERE ref_id='REF-VERIFIED-008';
UPDATE evidence_sources SET scope='lower_control', tier=3 WHERE ref_id='REF-00712';
UPDATE evidence_sources SET scope='lower_control', tier=3 WHERE ref_id='REF-00718';
UPDATE evidence_sources SET evidence_type='grey', scope='intrinsic', tier=3 WHERE ref_id='REF-00049';
UPDATE evidence_sources SET scope='national', tier=2 WHERE ref_id='REF-00297';
UPDATE evidence_sources SET scope='national', tier=2 WHERE ref_id='REF-00306';
UPDATE evidence_sources SET evidence_type='sr_meta', scope='intrinsic', tier=2 WHERE ref_id='REF-00547';
UPDATE evidence_sources SET evidence_type='clinical', scope='lower_control', tier=3 WHERE ref_id='REF-00611';
UPDATE evidence_sources SET evidence_type='clinical', scope='lower_control', tier=3 WHERE ref_id='REF-00612';
UPDATE evidence_sources SET evidence_type='clinical', scope='lower_control', tier=3 WHERE ref_id='REF-00613';

COMMIT;
