-- data_20260917224649_2026-09-17-notation-present-both.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-17-notation-present-both.md
-- Generated:  2026-09-17T22:46:49+00:00
-- Summary:    Owner ruling 2026-09-17 (present both notations), part 1: extraction 17 comparator recorded, GAP-006 closed by the ruling, determination 4 retired for recomputation
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- Research batch delta, captured by scripts/research/emit_batch_sql.py
-- Captured:  2026-09-17T22:46:49+00:00
-- Scratch:   /tmp/claude-0/-home-user-guidebook/cb2e5827-e176-5e25-a0ab-28bd3ff8005c/scratchpad/pa.db
-- Canonical: data/guidebook.db (schema version 87)
-- Totals:    0 insert(s), 3 update(s)
--
-- No transaction wrapper: the migration runner owns the boundary (F5).
-- Feed this to: python3 scripts/emit_data_migration.py --input <this file>

-- gaps: 0 insert(s), 1 update(s)
UPDATE "gaps" SET "status" = 'CLOSED-DECIDED', "updated_at" = '2026-09-17 22:46', "updated_by_session" = 'session_2026-09-17-notation-present-both' WHERE "gap_id" = 'GAP-006';

-- source_value_extractions: 0 insert(s), 1 update(s)
UPDATE "source_value_extractions" SET "notes" = 'THE MAXIMUM, NOT A RECOMMENDED VALUE, and the code says so itself in its own advisory (see the sibling finding extraction). Stored as the source states it — a rise:run ratio, not degrees — because converting would write a value the source does not state. 1:12 = 4.76 deg for reconciliation against the degree-denominated research rows; that conversion is NOT stored. root_type=committee_assertion and measurement_paradigm=stated_unmeasured: a standard asserts, it does not measure. T6, the regulatory stratum, walled off from full-strength anchoring per CLAUDE.md section 6. || 2026-09-17 comparator SET NULL -> <= (RECORDING WHAT THE SOURCE ALREADY SAYS, not changing a judgment. The row carried NO comparator while its own verified claim_text reads "Ramp runs shall have a running slope not steeper than 1:12" — unambiguously a ceiling, and every other governing row for this parameter carries <=. parse_bound reads a bare number as a POINT, so this row contributed a floor of 1:12 as well as a ceiling and the most-accommodating selection returned a minimum (8.33%) above its maximum (5%): an interval describing nothing. UNREACHABLE UNTIL TODAY BY LUCK — the row is written as a ratio, and before the owner ruling of 2026-09-17 the engine could not read ratios, so it never reached the selection. Reading it exposed it. The engine now refuses an incoherent interval rather than publishing one; this fixes the cause rather than the symptom. amend-extraction is the sanctioned verb: comparator is one of the two fields it permits, because a wrong claimed_value would be a second row and a contest, and this is not that — the value is right and its bound was never recorded.)', "updated_at" = '2026-09-17 22:46', "updated_by_session" = 'session_2026-09-17-notation-present-both', "comparator" = '<=' WHERE "extraction_id" = 17;

-- specifications: 0 insert(s), 1 update(s)
UPDATE "specifications" SET "updated_at" = '2026-09-17 22:46', "updated_by_session" = 'session_2026-09-17-notation-present-both', "retired_at" = '2026-09-17 22:46', "retired_by_session" = 'session_2026-09-17-notation-present-both', "retirement_reason" = 'Recomputed under the owner ruling of 2026-09-17 (present both notations, never choose between ratio and percentage). Computed when compose_value could not read a ratio, so its interval came from 2 of 7 governing claims — the two stating a percentage — while five ratio-stated rows contributed to the cell state but not to its value. Migration 087 and the notation arithmetic make all seven compose on one exact scale, and the result changes: the ratio-stated 1:20 now participates and is the gentlest ceiling. Retired in place per the 2026-09-16 ruling; the row is kept because it correctly accounted for what the engine could read when it was computed.' WHERE "specification_id" = 4;