-- data_20260916233024_2026-09-16-research-batch-09-ramp-gradient-co1.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-16-research-batch-09-ramp-gradient-co1.md
-- Generated:  2026-09-16T23:30:24+00:00
-- Summary:    link specification 2 -> 3 supersession
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- Research batch delta, captured by scripts/research/emit_batch_sql.py
-- Captured:  2026-09-16T23:30:23+00:00
-- Scratch:   /tmp/claude-0/-home-user-guidebook/2aa77402-d300-51b4-963f-be2d9885fbaa/scratchpad/batch09/link.db
-- Canonical: data/guidebook.db (schema version 84)
-- Totals:    0 insert(s), 1 update(s)
--
-- No transaction wrapper: the migration runner owns the boundary (F5).
-- Feed this to: python3 scripts/emit_data_migration.py --input <this file>

-- specifications: 0 insert(s), 1 update(s)
UPDATE "specifications" SET "updated_at" = '2026-09-16 23:30', "superseded_by_specification_id" = 3 WHERE "specification_id" = 2;