-- data_20260913040739_2026-09-13-clear-circulation-corpus.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-13-clear-circulation-corpus.md
-- Generated:  2026-09-13T04:07:39+00:00
-- Summary:    clear all 229 circulation rows across every pipeline stage (owner ruling: redo from the start)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- Clear every circulation row produced by research batches 04, 05, 06 and 07.
--
-- Owner ruling 2026-09-13: "all the circulation rows that have been produced are
-- not able to be trusted, so we have to redo them all from the start."
--
-- Append-only discipline (CLAUDE.md rule 3): this is a COMPENSATING migration.
-- The batch migrations that wrote these rows stay on disk and stay applied; this
-- one undoes their effect forward. A rebuild replays write-then-delete and lands
-- on the same state.
--
-- SCOPE IS DERIVED, NOT LISTED BY SESSION. The unit is the slug
-- 'accessible-circulation-geometry' and the 13 ref_ids reachable from it through
-- source_slug_links. Deleting by session would have missed the 33 observed_terms
-- that session_2026-09-03-defect-programme harvested from circulation sources,
-- and the one source_locators row.
--
-- WHAT IS KEPT, and why each is not research output:
--   terms, term_aliases, slugs   base vocabulary, minted 2026-05-09, months before
--                                any of this. base_parameters is what promoted
--                                TERM-001/002 into the parameter layer and that
--                                promotion IS research output, so it goes.
--   research_code_leads          a restored register with no ref_id and no slug.
--   gaps GAP-B01-*, GAP-B02-*    acoustics batches 01/02.
--   room-acoustic-performance    every row under that slug across
--                                search_executions, search_candidates and
--                                citation_mining.
--   retrieval-log/*              untouched on disk. The payload bytes are the
--                                evidence; a re-run verifies against the same
--                                bytes and re-fetches nothing.
--   sessions/, attestations/     the record that the work happened. Clearing the
--                                rows is not erasing the audit trail.
--
-- Order is children-to-parents so no FK is violated mid-transaction.
--
-- THE REF LIST IS MATERIALISED FIRST, and that is not a stylistic choice. Every
-- ref-scoped selector below reads source_slug_links, but source_slug_links is
-- itself a CHILD of evidence_sources, so it has to be deleted BEFORE its parent.
-- Reading the junction and deleting it are therefore in conflict: order it last
-- and the FK fails on evidence_sources; order it first and every selector after
-- it silently scopes to nothing and the migration deletes almost nothing while
-- reporting success. The temp table breaks the conflict by fixing the list once,
-- up front, so deletion order and selector correctness stop competing.
-- Caught by rehearsal against a scratch copy: FOREIGN KEY constraint failed at
-- the evidence_sources statement, 13 statements in.

CREATE TEMP TABLE temp._circ_refs AS
  SELECT ref_id FROM source_slug_links
   WHERE slug = 'accessible-circulation-geometry';

-- specification stage -----------------------------------------------------
DELETE FROM specification_source_links
 WHERE specification_id IN (SELECT specification_id FROM specifications);
DELETE FROM specifications
 WHERE parameter_id IN (SELECT parameter_id FROM base_parameters);
DELETE FROM gaps WHERE gap_id IN ('GAP-001', 'GAP-002');

-- judgment stage ----------------------------------------------------------
DELETE FROM extraction_relations
 WHERE from_extraction_id IN (
   SELECT extraction_id FROM source_value_extractions
    WHERE slug = 'accessible-circulation-geometry');
DELETE FROM source_value_extractions
 WHERE slug = 'accessible-circulation-geometry';

-- base stage: the parameter promotions, not the terms they point at -------
DELETE FROM base_parameters WHERE term_id IN ('TERM-001', 'TERM-002');

-- term harvest ------------------------------------------------------------
DELETE FROM term_adjudications
 WHERE observation_id IN (
   SELECT observation_id FROM observed_terms
    WHERE ref_id IN (SELECT ref_id FROM temp._circ_refs));
DELETE FROM observed_terms
 WHERE ref_id IN (SELECT ref_id FROM temp._circ_refs);

-- evidence stage ----------------------------------------------------------
DELETE FROM evidence_population_match
 WHERE ref_id IN (SELECT ref_id FROM temp._circ_refs);
DELETE FROM evidence_source_authors
 WHERE ref_id IN (SELECT ref_id FROM temp._circ_refs);
DELETE FROM search_admissions
 WHERE ref_id IN (SELECT ref_id FROM temp._circ_refs);
DELETE FROM source_locators
 WHERE ref_id IN (SELECT ref_id FROM temp._circ_refs);
DELETE FROM citation_mining WHERE slug = 'accessible-circulation-geometry';

-- the junction is a CHILD of evidence_sources, so it goes first; _circ_refs is
-- what keeps the selectors above correct once it is gone.
DELETE FROM source_slug_links WHERE slug = 'accessible-circulation-geometry';
DELETE FROM evidence_sources
 WHERE ref_id IN (SELECT ref_id FROM temp._circ_refs);

-- research stage ----------------------------------------------------------
DELETE FROM search_candidates
 WHERE found_under_slug = 'accessible-circulation-geometry'
    OR exec_id IN (SELECT exec_id FROM search_executions
                    WHERE slug = 'accessible-circulation-geometry');
DELETE FROM search_executions WHERE slug = 'accessible-circulation-geometry';

-- Schema-qualified because an unqualified DROP would resolve to a real table of
-- this name if one ever existed. It does NOT silence emit_data_migration's
-- risky-pattern warning: that regex matches the bare DROP TABLE token and fires
-- either way. The warning on this migration is expected and is about this line.
DROP TABLE temp._circ_refs;