-- data_20260719003303_2026-07-19-batch1-a02-grading.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-batch1-a02-grading.md
-- Generated:  2026-07-19T00:33:03+00:00
-- Summary:    Batch-1 A-02 provisional cell-state: NRC code-floor (regulatory_stratum_only), verifier-confirmed
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- A-02 (Acoustic Ceiling Panels, NRC) — provisional cell-state. Verifier-CONFIRMED code-floor (◐) grade.
-- The NRC value is anchored SOLELY on ANSI/ASA S12.60 S5.3 (REF-00563, a Tier-4 code); no Tier-1/2 source
-- sets an NRC panel threshold (the 17 linked T<=2 acoustic sources establish RT60/speech/effort OUTCOMES,
-- which anchor A-18, not this technique's NRC). Per doctrine (T4-6 walled off; converge != evidence) and the
-- E-06/MOB precedent, this grades regulatory_stratum_only=1, state=provisional — NOT a best-practice (●) value.

INSERT INTO convergence_assessment
  (convergence_id, status, clinical_sources, co1_sources, co2_sources, down_weighted_sources,
   discounted_sources, rationale, created_at, created_by_session)
VALUES
  (9012, 'single_axis', '[]', '[]', '[]', '[]', '["REF-00563"]',
   'Regulatory stratum only (T4-6): NRC >= 0.90 anchored solely on ANSI/ASA S12.60 S5.3 (REF-00563, code; empirical ceiling 0.935). No T1/T2 source sets an NRC panel threshold — the 17 linked Tier<=2 acoustic sources establish RT60 / speech-perception / listening-effort OUTCOMES (anchoring item A-18), not this NRC. convergence-not-evidence (tier-system 2.7). Contested-technique flag: REF-00580 (Amlani & Russo 2016, Tier-1, PMID 27885976) documents acoustic panels significantly increasing listening effort beyond the critical distance — the technique has an adverse mode; it complicates, and does not set, the NRC value.',
   '2026-07-19T00:00:00Z', 'session_2026-07-19-batch1-a02-grading');

INSERT INTO evidence_cell_state
  (cell_id, item_code, population_code, state, design_scale, convergence_id, tier_basis, governing_refs,
   code_floor_only, regulatory_stratum_only, value_min, value_max, value_unit, falsification_condition,
   has_unverified_sources, all_sources_disqualified, rule_version, created_at, created_by_session)
VALUES
  (9012, 'A-02', 'ALL', 'provisional', 'universal', 9012, 'T4-6-only(regulatory_stratum_only)', '["REF-00563"]',
   0, 1, 0.90, 0.935, 'NRC',
   'Floor claim: NRC >= 0.90 per ANSI/ASA S12.60 S5.3 (REF-00563; empirical ceiling 0.935). Overturned if the cited code edition is superseded. Never becomes a best-practice (filled-circle) claim by more codes agreeing — only a Tier-1/2 study establishing an NRC panel threshold, or Co-1/Co-2, can do that. Note: the item-name spec "NRC >= 0.85" sits BELOW this 0.90 code floor (surfaced for review).',
   0, 0, 'batch1-2026-07-19', '2026-07-19T00:00:00Z', 'session_2026-07-19-batch1-a02-grading');

COMMIT;
