-- data_20260511145000_2026-05-11g-citation-mining.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-05-11g-citation-mining.md
-- Generated:  2026-05-11T14:40:15+00:00
-- Summary:    Close GAP-290 — Phase 1 migration-based DB writes adopted
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Close GAP-290 — adopted Phase 1 migration-based DB writes
UPDATE gaps
SET status = 'CLOSED-FIXED',
    updated_at = '2026-05-11T14:50:00',
    updated_by_session = 'session_2026-05-11g-citation-mining.md'
WHERE gap_id = 'GAP-290';

COMMIT;
