-- data_20260725031754_2026-07-24-research-matrix-completion.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-research-matrix-completion
-- Generated:  2026-07-25T03:17:54+00:00
-- Summary:    R12 remediation: 5 economics_entries from prose findings (all flagged UNVERIFIED-QUANT) + LSE CASE-147 candidate
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- R12 REMEDIATION: move economic findings out of prose and into economics_entries.
-- Every value below was captured from a SECONDARY summary (search-engine result), NOT from the
-- primary instrument or paper, and carries no clause/page citation. Per CLAUDE.md §6 they are
-- therefore recorded with quant_status='UNVERIFIED-QUANT' and MUST NOT be used as anchoring
-- values until the primary is read and cited. Putting them in the structured home flagged is the
-- honest move; leaving them in prose (the prior state) made them invisible AND unverifiable.
-- Where the project already holds the underlying source, ref_id links to it rather than
-- re-asserting an unlinked claim.
INSERT INTO economics_entries (entry_id,pillar,entry_type,source,ref_id,jurisdiction,finding,
 study_design,value_numeric,value_unit,currency,evidence_tier,confidence,source_section,
 quant_status,year,status,notes,created_at,created_by_session) VALUES
('ECON-0001','construction','cost_premium',
 'Secondary summary of universal-design cost literature (WebSearch 2026-07-24)',NULL,'MULTI',
 'Universal design incorporated from the outset is reported to add 0-2% to construction cost.',
 'secondary synthesis',2.0,'%',NULL,5,'LOW',NULL,'UNVERIFIED-QUANT',2026,'active',
 'Upper bound of a reported 0-2% range. Provenance is a secondary summary, not the underlying study; no page/table. Do not anchor. Remediation: locate and cite the primary cost study.',
 '2026-07-25T03:30:00+00:00','session_2026-07-24-research-matrix-completion'),
('ECON-0002','construction','retrofit_multiplier',
 'Secondary summary of universal-design cost literature (WebSearch 2026-07-24)',NULL,'MULTI',
 'Retrofitting for accessibility after construction is reported to cost 20-50% more than building accessible from the outset.',
 'secondary synthesis',50.0,'%',NULL,5,'LOW',NULL,'UNVERIFIED-QUANT',2026,'active',
 'Upper bound of a reported 20-50% range. Same provenance caveat as ECON-0001. This is the core "cost of inaction" multiplier and deserves a primary citation before any use.',
 '2026-07-25T03:30:00+00:00','session_2026-07-24-research-matrix-completion'),
('ECON-0003','inaction','grant_programme',
 'Citizens Information (IE) — Housing Adaptation Grant for People with a Disability',NULL,'IE',
 'Irish Housing Adaptation Grant for People with a Disability: maximum effective grant EUR 30,000, means-tested. Social-housing tenants are INELIGIBLE and must use the separate Disabled Persons Grant.',
 'programme documentation',30000.0,'currency','EUR',5,'MODERATE',NULL,'UNVERIFIED-QUANT',2026,'active',
 'ACCESS-INEQUITY FINDING: eligibility is split by tenure, so the scheme a disabled person can access depends on whether they rent socially. Value from a government information page, not the statutory instrument; no clause cited.',
 '2026-07-25T03:30:00+00:00','session_2026-07-24-research-matrix-completion'),
('ECON-0004','inaction','grant_programme',
 'Scope / UK government guidance — Disabled Facilities Grant',NULL,'UK',
 'UK Disabled Facilities Grant maxima reported as GBP 30,000 (England), 36,000 (Wales), 25,000 (Northern Ireland); means-tested for adults, not means-tested for children.',
 'programme documentation',30000.0,'currency','GBP',5,'LOW',NULL,'UNVERIFIED-QUANT',2026,'active',
 'Three jurisdictions with different caps — a jurisdictional-divergence candidate. Values from secondary guidance pages; not clause-cited to the governing regulations.',
 '2026-07-25T03:30:00+00:00','session_2026-07-24-research-matrix-completion'),
('ECON-0005','inaction','housing_deficit',
 'Habinteg Housing Association research (via secondary summary); underlying value study held as REF-00268',
 'REF-00268','UK',
 'Reported UK accessible-housing deficit: a wheelchair user joining a local-authority waiting list may wait up to 47 years for a new-build wheelchair-accessible home; ~41% of homes planned over 10 years meet neither M4(2) nor M4(3); M4(3) share ~8.9% of affordable vs ~3.3% of open-market homes.',
 'sector research',47.0,'years',NULL,5,'LOW',NULL,'UNVERIFIED-QUANT',2022,'active',
 'HARM/INADEQUACY finding surfaced by the Co-1 pass (R1). Linked to REF-00268 (Social and Economic Value of Wheelchair User Homes) which the project already holds. Figures are from a secondary summary of Habinteg research — obtain the primary report and cite before use.',
 '2026-07-25T03:30:00+00:00','session_2026-07-24-research-matrix-completion');

-- Register the remaining economics candidates so they do not sit only in prose.
INSERT INTO search_candidates (exec_id,found_under_slug,suggested_slug,disposition,title,locator,
 locator_status,tier_guess,harm_finding,why_not_admitted,notes,session,created_at) VALUES
(NULL,'economics-sources','economics-sources','PENDING-VERIFICATION',
 'Living not existing: the social and economic value of wheelchair user homes (Habinteg / LSE CASE report 147)',
 'https://sticerd.lse.ac.uk/dps/case/cr/casereport147.pdf','UNVERIFIED',5,1,
 'Primary PDF not retrieved; project already holds a related record (REF-00268) — reconcile rather than duplicate.',
 'Co-1-adjacent: includes lived experience of disabled people on housing circumstances. Reconcile with REF-00268 before admitting.',
 'session_2026-07-24-research-matrix-completion','2026-07-25T03:30:00+00:00');

COMMIT;
