-- data_20260901205639_2026-09-01-research-batch-04-accessible-circulation.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-01-research-batch-04-accessible-circulation.md
-- Generated:  2026-09-01T20:56:39+00:00
-- Summary:    owner ruling 2026-09-01: the database holds base and research only - retract every row after research, and delete the item layer
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- Owner ruling 2026-09-01: the database holds base and research, and nothing else.
-- Two acts in one migration, because they share a dependency chain.
--
-- ACT 1 - retract every row downstream of the research stage.
-- ACT 2 - delete the item layer. Item codes are a pre-existing set of containers
--         carrying determinations in their names; leaving them standing biases
--         every subsequent finding toward a slot that already exists.
--
-- Research is untouched: search_executions, search_candidates, gaps and
-- source_locators carry no item_code column, so the clue store and the slugs
-- survive intact. citation_mining is retained in research with its foreign key
-- nulled, which preserves 147 harvested DOI leads that would otherwise be lost.

-- --- ACT 1: downstream of research, children before parents ------------------
DELETE FROM evidence_population_match;
DELETE FROM search_admissions;
DELETE FROM source_slug_links;
DELETE FROM evidence_source_authors;

-- Keep the mining record and its DOI leads; drop only its pointer into evidence.
UPDATE citation_mining SET global_ref_id = NULL WHERE global_ref_id IS NOT NULL;

DELETE FROM evidence_sources;

-- --- ACT 2: the item layer ---------------------------------------------------
DELETE FROM item_taxonomy_links;
DELETE FROM term_item_links;
DELETE FROM jurisdictional_values;
DELETE FROM items;

-- --- Coherence: H05 requires results_admitted to equal the admission-edge count,
-- --- which is now zero for every execution.
UPDATE search_executions SET results_admitted = 0 WHERE COALESCE(results_admitted, 0) > 0;