-- data_20260725034213_2026-07-25-synonym-grouping-fix.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-25-synonym-grouping-fix
-- Generated:  2026-07-25T03:42:13+00:00
-- Summary:    fix-forward: narrow TERM-074 off its overlap with TERM-012, annotate deliberate DOMAIN-code sharing, scope-note the TERM-043/053 axis collision
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Compensating migration for the 2026-07-25 synonym-grouping build.
-- Fixes defects found by re-running the alias-collision audit AFTER the build
-- (it had only been run before, which is how these got through).

-- 1. TERM-074 was authored as a near-duplicate of TERM-012 (sensory room):
--    both claimed "quiet room" / Ruheraum / rauhoittumistila / stillerom.
--    TERM-012 owns the designated ROOM. TERM-074's genuinely distinct
--    contribution is the route OUT — exit legibility and withdrawal space that
--    is not necessarily a room. Narrow it to that and surrender the overlap.
UPDATE terms SET
  canonical_en = 'withdrawal space and exit legibility',
  definition   = 'Somewhere to withdraw to that is not necessarily a room, plus a legible visible route out of it',
  scope_note   = 'Links items A-16, D-05, E-13. The designated room is TERM-012 (sensory room) — this term is the wider provision (alcove, recess, edge seating) plus the exit-legibility half. Retreat without a legible exit fails the arousal-safety axis (TERM-032).',
  updated_at   = '2026-07-25T04:00:00Z',
  updated_by_session = 'session_2026-07-25-synonym-grouping-fix'
WHERE term_id = 'TERM-074';

-- Surrender the aliases that belong to TERM-012.
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='quiet room'         AND language='en';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='calm space'         AND language='en';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='Ruheraum'           AND language='de';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='rauhoittumistila'   AND language='fi';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='stillerom'          AND language='no';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='stillerum'          AND language='da';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='tyst rum'           AND language='sv';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='stanza tranquilla'  AND language='it';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='sala tranquila'     AND language='pt';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='sala de calma'      AND language='es';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='salle de repos'     AND language='fr';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='stilteruimte'       AND language='nl';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='静養室'              AND language='ja';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='静音室'              AND language='zh';
DELETE FROM term_aliases WHERE term_id='TERM-074' AND alias='정온실'              AND language='ko';

-- Point the two at each other so the relation is explicit rather than implied
-- by a shared string.
INSERT INTO term_aliases(term_id,alias,language,alias_type,notes,created_at,created_by_session,updated_at,updated_by_session)
VALUES('TERM-074','sensory room','en','NARROWER',
 'the designated-room case of withdrawal provision; canonical at TERM-012',
 '2026-07-25T04:00:00Z','session_2026-07-25-synonym-grouping-fix','2026-07-25T04:00:00Z','session_2026-07-25-synonym-grouping-fix');

-- 2. TERM-053 shares de 'Belastungsintoleranz' with axis TERM-043. Same
--    content-vs-axis pattern already documented for TERM-020/042; note it here too.
UPDATE terms SET
  scope_note = scope_note || ' Shares the de alias ''Belastungsintoleranz'' with axis TERM-043 (Sustained-exertion demand): this is the symptom, that is the demand layer.',
  updated_at = '2026-07-25T04:00:00Z',
  updated_by_session = 'session_2026-07-25-synonym-grouping-fix'
WHERE term_id = 'TERM-053';

-- 3. Document the deliberate one-code-to-two-concepts DOMAIN aliases so a future
--    collision audit reads them as intent, not drift. Searching 'OFS' SHOULD
--    return both fatigue and dysautonomia.
UPDATE term_aliases SET
  notes = notes || ' Deliberately shared with a sibling concept: one population/project code legitimately spans both, and retrieval should return both.',
  updated_at = '2026-07-25T04:00:00Z',
  updated_by_session = 'session_2026-07-25-synonym-grouping-fix'
WHERE alias_type='DOMAIN' AND language='en' AND alias IN ('OFS','TALL','LMB','MOVE');

COMMIT;
