-- data_20260724202042_2026-07-24-e08-adversarial-fixforward.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-e08-adversarial-fixforward
-- Generated:  2026-07-24T20:20:42+00:00
-- Summary:    fix-forward on E-08 inclusion repair: correct AX-BAL overclaim (vestibular slug + 21 sources exist; GAP-300 pre-registered), MS/LPA applies->context_dependent, flag stale AX-BAL coverage_status
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Compensating migration for data_20260724193917_2026-07-24-e08-inclusion-repair.sql
-- Data migrations are immutable once committed, so defects are fixed forward.
--
-- Adversarial self-review of that migration found two defects.
--
-- DEFECT 1 (overclaim). The E-08 -> AX-BAL mechanism_note asserted the balance
-- counter-strand was "UNSOURCED (AX-BAL coverage_status=STUB; zero slugs, zero
-- searches)" and that "the guidebook currently has NO handrail item" as though
-- newly found. Both mis-state the corpus:
--   * slug `vestibular-balance-built-environment` is ACTIVE with
--     serves_axes = ["AX-BAL"] and 21 source_slug_links, including Tier-1
--     handrail biomechanics (REF-00911 Komisar 2019 reach-to-grasp on slope
--     descent; REF-00912 loading profiles; REF-00913 Gosine 2020 balance
--     recovery), a Tier-2 Cochrane falls SR (REF-00792), WHO handrail/grab-bar
--     specification APS15 (REF-00883) and code dimensions (REF-00921).
--     AX-BAL's own coverage_status='STUB' text ("zero slugs, zero searches") is
--     therefore STALE metadata, not a current fact.
--   * the missing handrail item is already registered as GAP-300 (P2, OPEN),
--     with GAP-301 for stair going/riser. Not a new discovery.
-- What IS genuinely unmeasured is narrower: the interaction between corridor
-- CLEAR WIDTH and balance support. Handrails and falls are well evidenced; no
-- source relates corridor width to steadying-surface distance.
--
-- DEFECT 2 (over-inclusion). MS and LPA were recorded 'applies', implying clear
-- width is their operative variable. It is not. MS's documented corridor strand
-- is route-length/cooling (a longitudinal metric, like COM's rest interval), and
-- LPA's is reach/envelope (AX-REA), not cross-section. Marking them 'applies'
-- asserted a width stake the corpus does not evidence -- inclusion as gesture,
-- which is the arbitrariness the repair was meant to avoid. Both move to
-- 'context_dependent', which is what that value exists to express. They remain
-- linked: the stake is real, the variable is simply not width.

UPDATE item_axis_links
SET mechanism_note =
  'OPEN COUNTER-STRAND, narrowly scoped: the interaction between corridor CLEAR WIDTH and balance support is unmeasured -- a wider corridor puts wall or handrail further from an unsteady walker, and AX-BAL names large uniform visual fields as a dizziness precipitant. The BALANCE DOMAIN ITSELF IS NOT UNSOURCED: slug vestibular-balance-built-environment (ACTIVE, serves_axes=["AX-BAL"], 21 sources) carries T1 handrail-recovery biomechanics (REF-00911/00912/00913), a T2 Cochrane falls SR (REF-00792, home modification reduces fall rate 0.81 CI 0.68-0.97, more effective when OT-delivered), WHO APS15 handrail spec (REF-00883) and code dimensions (REF-00921: 900-1000 mm height, 32-51 mm section, >=50 mm clearance, both sides continuous). AX-BAL.coverage_status=STUB and its "zero slugs, zero searches" note are STALE against that slug. Candidate resolution -- add continuous support rather than narrow the route -- is already named in AX-BAL.design_domains; the blocker is that no handrail-dimension item exists to carry it, registered as GAP-300 (P2, OPEN), with GAP-301 for stair going/riser.',
    source = 'Owner directive 2026-07-24 (fall-risk/balance counter-strand); corrected by adversarial self-review same session. Axis mechanism per axes.AX-BAL; population routing per population_axis_map (VES PRIMARY, BRAIN PRIMARY, COM SITUATIONAL); evidence per slug vestibular-balance-built-environment; gaps GAP-300/GAP-301'
WHERE item_code = 'E-08' AND axis_code = 'AX-BAL';

UPDATE item_population_links
SET applicability = 'context_dependent'
WHERE item_code = 'E-08' AND population_code IN ('MS', 'LPA');

-- Record the stale-metadata contradiction on the axis itself so the next reader
-- meets it as a flagged finding rather than trusting "zero slugs" again.
-- coverage_status is deliberately NOT re-graded here: STUB -> PARTIAL is a
-- taxonomy judgment and taxonomy is owner-gated. The contradiction is recorded;
-- the re-grade is proposed.
UPDATE axes
SET notes = notes || ' || FLAGGED 2026-07-24 (adversarial review): coverage_status=STUB and the "zero b-codes, zero slugs, zero searches" text above are STALE. Slug vestibular-balance-built-environment is ACTIVE with serves_axes=["AX-BAL"] and 21 source_slug_links (T1 REF-00911/00912/00913 handrail-recovery biomechanics; T2 REF-00792 Cochrane falls SR; T4 REF-00883 WHO APS15; T5 REF-00921 code dimensions), and evidence_cell_state already holds VES cells at B-08 and C-06 (both provisional, T3-only). Re-grade to PARTIAL is PROPOSED, not applied: axis coverage grading is a taxonomy decision and owner-gated.'
WHERE axis_code = 'AX-BAL';

COMMIT;
