-- data_20260916050416_2026-09-16-research-batch-08-ramp-gradient.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-16-research-batch-08-ramp-gradient.md
-- Generated:  2026-09-16T05:04:16+00:00
-- Summary:    batch 08 fix: REF-00986 and REF-00984 shared a per-slug local_ref_id, blocking citation_mining
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- COMPENSATING: two sources in this slug were given the SAME per-slug label.
--
-- Batch 08 admitted four sources in two passes. The first pass used local-ref-id
-- 1..4 and two of its four admissions were REFUSED (the RETIRED-tombstone DOI
-- collision, fixed in the same PR); the retry pass restarted its counter at 3, so
-- REF-00984 (from pass 1) and REF-00986 (from pass 2) both carry local_ref_id '4'.
--
-- That is not cosmetic. `citation_mining` keys on (slug, local_ref_id) with a UNIQUE
-- constraint and looks the label up from source_slug_links rather than inventing it,
-- so the second source of the pair CANNOT be given a mining row at all -- log-mining
-- failed with `UNIQUE constraint failed: citation_mining.slug,
-- citation_mining.local_ref_id`, and the R2 completeness audit was therefore
-- unsatisfiable for REF-00986 by any route.
--
-- No CLI writer can amend a slug link, so this is the sanctioned path (rule 3: fix
-- forward with a compensating migration, never edit the applied one).
--
-- NOTE FOR THE READER OF migration_reproducibility: this is an UPDATE, and that
-- blocking check compares row COUNTS only, so it cannot see this statement. The
-- deep variant can, and is advisory.

UPDATE source_slug_links
   SET local_ref_id = '5'
 WHERE ref_id = 'REF-00986'
   AND slug = 'accessible-circulation-geometry'
   AND local_ref_id = '4';