-- data_20260720040430_2026-07-19-citation-mining-nonenglish-batch6-redo.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-citation-mining-nonenglish-batch6-redo.md
-- Generated:  2026-07-20T04:04:30+00:00
-- Summary:    Migration-history reconciliation: capture session_2026-07-19-citation-mining-nonenglish-batch6-redo's direct DB writes (never emitted as a migration -- GAP-290 violation) so committed data/guidebook.db reproduces from migration history
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Migration-history reconciliation for session_2026-07-19-citation-mining-nonenglish-batch6-redo
-- Per DR-2026-05-15-migration-history-drift-repair.md precedent: this session's DB
-- writes were never captured as a migration file (GAP-290 violation), surfaced by
-- audit.yml's migration-reproducibility check once source_slug_links_duplicates.py's
-- crash was fixed. All rows below already exist in the committed DB, verbatim --
-- this migration makes migration history match reality; no new data, no data change.

INSERT INTO evidence_sources (ref_id, source_type, author_count, author_count_is_complete, first_author_last, first_author_first, is_corporate_primary, author_display, pub_year, pub_year_note, pub_title, pub_subtitle, chapter_title, original_title, lang_detected, lang_detection_method, pub_title_en, pub_subtitle_en, chapter_title_en, journal_name_en, translation_method, translation_reviewed, journal_name, journal_abbrev, volume, issue, pages_start, pages_end, article_number, publisher, publisher_location, edition, book_title, series, series_number, report_number, institution, standard_number, doi, pmid, pmcid, isbn, issn, url, url_accessed, handle, local_id, tier, evidence_type, jurisdiction, co1_provenance, co1_source_type, synthesis_attribution_required, metadata_quality, verification_status, doi_resolution_outcome, bpc_shorthand, bpc_note, grey_flag, grey_reason, verification_note, prior_expectation, search_queries_used, derivation_chain, notes, created_at, created_by_session, updated_at, updated_by_session, verified_by_tool, last_verified_at, verification_attempt_count, superseded_by_ref_id, pages, pub_month, language, subtype, citation_count, url_resolution_outcome, url_last_fetched, url_match_similarity, metadata_integrity_status, metadata_integrity_detail, code_currency_status, code_currency_verified_at, code_currency_verified_by_session, code_currency_notes, scope) VALUES
('REF-00844', NULL, NULL, 0, NULL, NULL, 0, 'van Mierlo T, Bovenberg F, Voskes Y, Mulder N', 2013, NULL, 'Werkboek HIC: High en Intensive Care in de Psychiatrie', NULL, NULL, NULL, 'nl', 'native_title_verified', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 'co2', 'NL', NULL, NULL, NULL, 'COMPLETE', 'VERIFIED', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Identified via a review article in Tijdschrift voor Psychiatrie citing this workbook; ISBN 978-90-589-8235-3, De Tijdstroom Utrecht, 142pp. Discusses architectural/built-environment aspects of high-intensive-care psychiatric rooms (temperature, lighting, blinds, sightlines) as part of patient autonomy provisions.', '2026-07-20 00:37', 'session_2026-07-19-citation-mining-nonenglish-batch6-redo', '2026-07-20 00:37', 'session_2026-07-19-citation-mining-nonenglish-batch6-redo', NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note) VALUES
('REF-00844', 'mental-health-built-environment', 'MHB-34', '2026-07-20 00:37', 'session_2026-07-19-citation-mining-nonenglish-batch6-redo', '2026-07-20 00:37', 'session_2026-07-19-citation-mining-nonenglish-batch6-redo', NULL),
('REF-00051', 'cognitive-wayfinding-design', 'CWD-25', '2026-07-20T00:37:51Z', 'session_2026-07-19-citation-mining-nonenglish-batch6-redo', '2026-07-20T00:37:51Z', 'session_2026-07-19-citation-mining-nonenglish-batch6-redo', NULL);

COMMIT;
