-- data_20260719232404_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery.md
-- Generated:  2026-07-19T23:24:04+00:00
-- Summary:    WS1 Batch B: anchor 2 no-anchor slices via reachable-tool discovery — relink orphan REF-VERIFIED-003 (T2 SR) to stair-ramp-threshold-biomechanics; ingest 2 T2 systematic reviews (REF-00771 Tan 2022, REF-00772 Goudriaan 2021) as first anchors for circadian-lighting-melanopic-edi
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- WS1 Batch B — anchor recovery for supporting-only (no-anchor) slices, via
-- reachable-tool discovery (PubMed + Scholar Gateway), the citation-graph APIs
-- (CrossRef/OpenAlex/Semantic Scholar) being egress-blocked this session (403).
-- Recorded as evidence-expansion / WS1 anchoring, NOT as citation_mining, since
-- semantic/related-article discovery is not the project's backward=CrossRef /
-- forward=OpenAlex reference-graph method. Every source verified via a real tool
-- retrieval (PubMed get_article_metadata / Scholar Gateway), deduped vs the 251
-- existing DOIs, tier-graded per governance/tier-system.md.
--
-- (1) RELINK the orphan REF-VERIFIED-003 (Rouvier 2022 MWC-biomechanics SR, T2,
--     already VERIFIED in-DB, linked to no slug) to its natural home — gives
--     stair-ramp-threshold-biomechanics-accessibility (was T3x14, 0 anchors) its
--     first best-practice anchor with zero new fabrication surface.
-- (2) INGEST two T2 systematic reviews as the first anchors for
--     circadian-lighting-melanopic-edi (was T3x5/T4x2/T5x3, 0 anchors).

-- (1) orphan relink
INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note) VALUES
('REF-VERIFIED-003', 'stair-ramp-threshold-biomechanics-accessibility', 'SRB-27', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery',
 'First best-practice ANCHOR (T2 sr_meta) for this slice: systematic review of manual-wheelchair biomechanics crossing slopes, cross-slopes, curbs and ground types — directly on the slice''s ramp/threshold/curb biomechanics parameter. Row was already VERIFIED in-DB but orphaned; routed here per audit-remediation-batch-a.md orphan inventory.');

-- (2) two new T2 systematic-review anchors for circadian-lighting-melanopic-edi
INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete, first_author_last, is_corporate_primary, author_display,
    pub_year, pub_title, journal_name, volume, pages, publisher, language, lang_detected, lang_detection_method,
    tier, evidence_type, jurisdiction, doi, pmid, pmcid, url,
    metadata_quality, verification_status, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
) VALUES
('REF-00771', 'journal_article', 5, 1, 'Tan', 0, 'Tan JSI, Cheng LJ, Chan EY, Lau Y, Lau ST',
 2022, 'Light therapy for sleep disturbances in older adults with dementia: a systematic review, meta-analysis and meta-regression',
 'Sleep Medicine', '90', '153-166', 'Elsevier', 'en', 'en', 'native_english',
 2, 'sr_meta', 'INT', '10.1016/j.sleep.2022.01.013', '35180479', NULL, 'https://doi.org/10.1016/j.sleep.2022.01.013',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery] Verified via PubMed get_article_metadata (PMID 35180479, DOI 10.1016/j.sleep.2022.01.013): article_types = Meta-Analysis + Systematic Review; 18 RCTs, n=1012, Cochrane RoB + GRADE, meta-regression in Stata. DOI absent from the 251 existing corpus DOIs (deduped). CrossRef/OpenAlex/Semantic-Scholar egress-blocked this session, so no reference-graph mining attempted.',
 'PubMed PMID 35180479 -> get_article_metadata; tier per governance/tier-system.md (SR+meta of RCTs = T2 sr_meta).',
 'First T2 anchor for circadian-lighting-melanopic-edi (previously T3/T4/T5 only). SR+meta-analysis of light therapy on sleep/circadian outcomes in dementia; anchors best-practice claims about circadian lighting intensity/timing where the slice previously had only code/framework convergence.',
 '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery'),

('REF-00772', 'journal_article', 5, 1, 'Goudriaan', 0, 'Goudriaan I, van Boekel LC, Verbiest MEA, van Hoof J, Luijkx KG',
 2021, 'Dementia Enlightened?! A Systematic Literature Review of the Influence of Indoor Environmental Light on the Health of Older Persons with Dementia in Long-Term Care Facilities',
 'Clinical Interventions in Aging', '16', '909-937', 'Dove Medical Press', 'en', 'en', 'native_english',
 2, 'sr_meta', 'INT', '10.2147/CIA.S297865', '34079240', 'PMC8163627', 'https://doi.org/10.2147/CIA.S297865',
 'COMPLETE', 'VERIFIED-2',
 '[session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery] Verified via PubMed get_article_metadata (PMID 34079240, PMC8163627, DOI 10.2147/CIA.S297865): article_types = Systematic Review; n=37 studies 1991-2020 on indoor daylight/lighting (not just light-boxes) in dementia long-term-care. DOI absent from existing corpus DOIs (deduped). Reference-graph mining not attempted (CrossRef/OpenAlex/S2 egress-blocked this session).',
 'PubMed PMID 34079240 -> get_article_metadata; tier per governance/tier-system.md (systematic review = T2 sr_meta).',
 'Second T2 anchor for circadian-lighting-melanopic-edi, specifically on INDOOR AMBIENT light (built-environment-relevant, vs clinical light-box therapy) — directly supports built-environment circadian-lighting best-practice framing.',
 '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery');

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note) VALUES
('REF-00771', 'circadian-lighting-melanopic-edi', 'CML-11', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery', 'T2 SR+meta-analysis (18 RCTs) on light therapy for circadian/sleep outcomes in dementia — first anchor tier for this slice.'),
('REF-00772', 'circadian-lighting-melanopic-edi', 'CML-12', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery', '2026-07-19T23:23:51Z', 'session_2026-07-19-evidentiary-audit-ws1-batch-b-anchor-recovery', 'T2 systematic review on indoor ambient lighting in dementia care — built-environment-relevant circadian-lighting anchor.');

COMMIT;
