-- data_20260725050836_2026-07-25-energy-conservation-rest-points-seating.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-25-energy-conservation-rest-points-seating.md
-- Generated:  2026-07-25T05:08:36+00:00
-- Summary:    remediate 4 DoD failures (R2 mining register, R3 clause locator, R13 ASLA grade) + normalise search_executions.language case so logged searches actually suppress their coverage cells
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Remediation of the 4 DoD-gate failures on batch 1, plus one substrate bug the gate exposed.

-- (1) SUBSTRATE BUG. search_executions.language carried mixed case ('en' vs 'EN') while
-- lang_jur_map and search_languages are uppercase throughout. v_coverage_priority suppresses a
-- queue cell via se.language = ljm.language, and SQLite '=' on TEXT is case-sensitive, so 57 of
-- 68 logged searches were never suppressing their own coverage cell: the priority queue was
-- reporting completed work as un-done. Normalising to the uppercase convention used by
-- lang_jur_map / search_languages. This changes no evidence claim and moves no adjudicated
-- figure; it is a mechanical case normalisation of the log's join key.
UPDATE search_executions SET language = upper(language) WHERE language <> upper(language);

-- (2) R3. The gate reads the clause locator from evidence_sources.pages / article_number, not
-- from notes. REF-00949's clause citations were captured in notes only. Promoting them.
UPDATE evidence_sources
   SET pages = 'Section 4.5 Seating, p.31 (50m urban interval); p.102 (seat dimensions); p.124 (100m countryside interval)',
       updated_at = '2026-07-25',
       updated_by_session = 'session_2026-07-25-energy-conservation-rest-points-seating'
 WHERE ref_id = 'REF-00949';

-- (3) R13. REF-00951 (ASLA) was admitted without its own population grade. The grade is the
-- point of the source: it asserts a claim about mobility-disabled people on no population basis.
INSERT INTO evidence_population_match
 (match_id, source_ref, ref_id, target_population, study_population, sample_size,
  match_grade, mismatch_note, gap_id, created_at, created_by_session)
VALUES
 ('EPM-00951-A','REF-00951','REF-00951','MOB','NONE - no study, no participants. A professional-body design guide asserting a claim about "older adults and mobility-disabled people" while citing a single study that enrolled neither disabled participants nor institutional residents.',NULL,
  'MISMATCH','R13 MISMATCH. Per the rule, a source with NO PARTICIPANTS is graded PROXY at best; this one is graded MISMATCH because it does not merely generalise from an adjacent population, it names a population ("mobility-disabled people") that appears nowhere in its evidence base. Recording the grade is what stops the corpus inheriting the extrapolation.','GAP-304',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating');

-- (4) R2. Citation mining performed in this batch, written to the register rather than left
-- implicit in a mining_direction flag. Honest deferrals recorded as deferrals, not as absence.
INSERT INTO citation_mining
 (slug, local_ref_id, global_ref_id, doi, backward, forward, connections_produced, notes,
  created_at, created_by_session, updated_at, updated_by_session, deferred_reason)
VALUES
 ('energy-conservation-rest-points-seating','ECR-07','REF-00951',NULL,1,0,1,
  'BACKWARD MINING EXECUTED AND PRODUCTIVE. REF-00951 carries exactly one citation: a bare hyperlink to PMC5549237. Resolved it to REF-00952 and re-retrieved the full text. Result: the cited study contains no bench-spacing figure and no disabled cohort, establishing that REF-00951 20m/65ft interval is unsupported by its own source. 1 connection produced (REF-00951 -> REF-00952). Forward mining not applicable: an undated web guide has no forward citation graph.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating',NULL),

 ('energy-conservation-rest-points-seating','ECR-06','REF-00950',NULL,1,0,0,
  'BACKWARD MINING EXECUTED. REF-00950 reference list enumerated in full: DfT Inclusive Mobility 2021, BS8300-1:2018, HSE HSG57, Building Regs Approved Documents K and M, LTN 1/20, BS4800, Blackler et al 2018 (Seating in Aged Care, SAGE Open Med), DfT Reference Wheelchair Report 2022, City of York Accessible Seating Review. 0 connections produced because none were resolved to a locator within this batch; all 6 novel items staged in search_candidates as PENDING-VERIFICATION rather than admitted, per R10. The single most valuable lead is Blackler 2018, which may be the only primary basis for the seat-dimension figures.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating',NULL),

 ('energy-conservation-rest-points-seating','ECR-01','REF-00945','10.1111/j.1532-5415.2010.03143.x',0,0,0,
  NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating',
  'DEFERRED TO BATCH 2, WITH REASON - NOT SKIPPED. REF-00945, REF-00946 and REF-00948 share authors and institution (Jyvaskyla: Rantakokko, Rantanen, Iwarsson, Portegijs) and largely one Finnish cohort tradition. Naive backward/forward mining on this anchor would walk further into the same cluster and return co-citations that LOOK like independent replication. Mining must first be constructed to escape the cluster - different countries, different cohorts, non-Finnish first authors - which needs a deliberately adversarial query design rather than a citation walk. Registered as GAP-306.'),

 ('energy-conservation-rest-points-seating','ECR-02','REF-00946','10.1111/j.1532-5415.2010.02792.x',0,0,0,
  NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating',
  'DEFERRED TO BATCH 2, WITH REASON. Same single-group cluster as ECR-01; see GAP-306. Deferring is the honest call here: mining this anchor now would inflate apparent corroboration.'),

 ('energy-conservation-rest-points-seating','ECR-03','REF-00947','10.1093/geront/gns119',0,0,0,
  NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating',
  'DEFERRED TO BATCH 2, WITH REASON. REF-00947 is the batch only EXACT population match and a US cohort independent of the Finnish cluster, so it is the HIGHEST-VALUE mining target for batch 2 - forward citations from it are the most likely route to independent replication of the resting-places finding. Deferred here only because batch 1 exhausted its verification budget on the ASLA mis-citation chain, not because the target is low value.'),

 ('energy-conservation-rest-points-seating','ECR-04','REF-00948','10.1155/2013/769645',0,0,0,
  NULL,'2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating',
  'DEFERRED TO BATCH 2, WITH REASON. Same Jyvaskyla cluster; see GAP-306. Forward mining is nonetheless wanted eventually because a null result on individual-level intervention is the kind of finding that later work cites when arguing for environmental provision.'),

 ('energy-conservation-rest-points-seating','ECR-08','REF-00952','10.1007/s10433-015-0340-5',1,0,0,
  'BACKWARD MINING PARTIAL. Full text retrieved and read for the specific question of whether any bench-spacing figure exists (it does not). Its own reference list was not enumerated: the source was admitted to adjudicate the REF-00951 claim, and that question was answered without needing its ancestry. Recorded as partial rather than complete so batch 2 does not read this as an exhausted anchor.',
  '2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating','2026-07-25','session_2026-07-25-energy-conservation-rest-points-seating',NULL);

COMMIT;
