-- data_20260804002752_2026-08-03-db-integrity-backlog.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-08-03-db-integrity-backlog
-- Generated:  2026-08-04T00:27:52+00:00
-- Summary:    D04: merge 7 same-work DOI-less duplicate groups; preserve the MHB-34 mining witness; retire the tombstone's live processing state
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- D04: seven confirmed same-work duplicate groups, merged.
--
-- D04/D05 were restored by commit 57db66a after the DOI-less dedup contract was
-- lost with the doi_less_key column, so this is a never-worked backlog rather
-- than a regression. Every pair was opened and compared field by field --
-- matching author, title and year, consistent tier -- before merging.
--
-- Pattern per the ce5b2b5 dedup precedent: repoint slug links, delete leftovers,
-- set superseded_by_ref_id, append a note, RETAIN the duplicate row.
--
-- TWO CORRECTIONS TO THAT PATTERN, both learned by running it and watching a
-- check go red.
--
-- 1. `UPDATE OR IGNORE` silently skips the repoint where the canonical already
--    links the same slug, and the following DELETE then destroys the duplicate
--    link outright -- taking its local_ref_id with it. That (slug, local_ref_id)
--    pair is the join key citation_mining and supersession_check resolve
--    through. Two of the seven collide this way: REF-00928/CRB-13 (no
--    dependents) and REF-00844/MHB-34, which carries
--    deferred_reason='print_paywalled_no_fulltext' -- the witness behind
--    REF-00844's 'deferred' state and the thing check C09 exists to protect.
--    That mining row is therefore re-pointed to the CANONICAL by global_ref_id,
--    not left dangling. Verified: no supersession_check rows depend on either
--    pair.
--
-- 2. A tombstone must not keep asserting a live processing state. Once
--    REF-00844 is superseded it holds no slug links, so a global_ref_id aimed
--    at it would fail A07, and a 'deferred' mining status on it would demand a
--    witness it can no longer reach (C09). Citation mining is genuinely
--    not-applicable to a row that no longer represents the work -- the
--    canonical does -- and 'not-applicable' is in migration 040's own
--    vocabulary. The historical fact is not lost: it survives in the MHB-34
--    mining row and its deferred_reason.
--
-- The other six tombstones are all 'pending'/'pending' and need no such care.

-- Re-point the at-risk mining witness to the canonical BEFORE any link moves.
UPDATE citation_mining SET global_ref_id='REF-00762'
 WHERE slug='mental-health-built-environment' AND local_ref_id='MHB-34'
   AND global_ref_id IS NULL;

-- REF-00309 -> REF-00304: identical ADA National Network cost FAQ 2025; both T6 code.
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00304', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog' WHERE ref_id='REF-00309';
DELETE FROM source_slug_links WHERE ref_id='REF-00309';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00304', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog', verification_note=COALESCE(verification_note,'')||' [DEDUP 2026-08-04: same-work duplicate of REF-00304 (matching author, title and year, consistent tier); superseded, links repointed, row retained.]' WHERE ref_id='REF-00309';

-- REF-00153 -> REF-00076: same paper; canonical carries the cell link. Author initial differs (D. vs S.) -- the duplicate records "Sidney Newton", so the canonical first-initial is worth re-checking.
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00076', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog' WHERE ref_id='REF-00153';
DELETE FROM source_slug_links WHERE ref_id='REF-00153';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00076', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog', verification_note=COALESCE(verification_note,'')||' [DEDUP 2026-08-04: same-work duplicate of REF-00076 (matching author, title and year, consistent tier); superseded, links repointed, row retained.]' WHERE ref_id='REF-00153';

-- REF-00201 -> REF-00084: identical EADDAT (Palmer) 2022; both T5 national_fw; canonical has 2 slug links.
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00084', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog' WHERE ref_id='REF-00201';
DELETE FROM source_slug_links WHERE ref_id='REF-00201';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00084', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog', verification_note=COALESCE(verification_note,'')||' [DEDUP 2026-08-04: same-work duplicate of REF-00084 (matching author, title and year, consistent tier); superseded, links repointed, row retained.]' WHERE ref_id='REF-00201';

-- REF-00378 -> REF-00053: identical "Adaptations without delay" 2019; both T2 standard_eb. Canonical anchors cell 9003 and has 3 slug links.
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00053', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog' WHERE ref_id='REF-00378';
DELETE FROM source_slug_links WHERE ref_id='REF-00378';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00053', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog', verification_note=COALESCE(verification_note,'')||' [DEDUP 2026-08-04: same-work duplicate of REF-00053 (matching author, title and year, consistent tier); superseded, links repointed, row retained.]' WHERE ref_id='REF-00378';

-- REF-00928 -> REF-00156: UN CRPD General Comment No. 2 (2014) Art. 9 -- same document beyond doubt. CLASSIFICATION CONFLICT: canonical is standard_eb, duplicate national_fw, both T4. Question RECORDED, NOT RESOLVED.
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00156', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog' WHERE ref_id='REF-00928';
DELETE FROM source_slug_links WHERE ref_id='REF-00928';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00156', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog', verification_note=COALESCE(verification_note,'')||' [DEDUP 2026-08-04: same-work duplicate of REF-00156 (UN CRPD General Comment No. 2 (2014) Art. 9, identical title and year); superseded, links repointed, row retained. CLASSIFICATION CONFLICT RECORDED, NOT RESOLVED: this row was national_fw, the canonical is standard_eb, both T4. Neither label is obviously right for a treaty-body interpretive instrument; the canonical value is kept pending adjudication.]' WHERE ref_id='REF-00928';

-- REF-00844 -> REF-00762: identical Werkboek HIC 2013; both T3 grey. Canonical has a URL and VERIFIED-2 standing; duplicate has no locator.
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00762', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog' WHERE ref_id='REF-00844';
DELETE FROM source_slug_links WHERE ref_id='REF-00844';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00762', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog', verification_note=COALESCE(verification_note,'')||' [DEDUP 2026-08-04: same-work duplicate of REF-00762 (matching author, title and year, consistent tier); superseded, links repointed, row retained.]' WHERE ref_id='REF-00844';

-- REF-00308 -> REF-00305: identical Woodstock HomeMod 2020; both T3 grey.
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00305', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog' WHERE ref_id='REF-00308';
DELETE FROM source_slug_links WHERE ref_id='REF-00308';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00305', updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog', verification_note=COALESCE(verification_note,'')||' [DEDUP 2026-08-04: same-work duplicate of REF-00305 (matching author, title and year, consistent tier); superseded, links repointed, row retained.]' WHERE ref_id='REF-00308';

-- REF-00844: tombstone housekeeping. SUPERSEDED states its actual standing and
-- is in-vocabulary (B01); this also clears C01 and C04, which it failed by
-- claiming VERIFIED with no locator while its canonical holds the real URL.
UPDATE evidence_sources
   SET verification_status='SUPERSEDED',
       citation_mining_status='not-applicable',
       updated_at='2026-08-04 00:32', updated_by_session='session_2026-08-03-db-integrity-backlog'
 WHERE ref_id='REF-00844';

COMMIT;
