-- data_20260916050710_2026-09-16-research-batch-08-ramp-gradient.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-16-research-batch-08-ramp-gradient.md
-- Generated:  2026-09-16T05:07:10+00:00
-- Summary:    batch 08 part 5: two extractions re-graded finding -> condition after the adversarial pass
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- Research batch delta, captured by scripts/research/emit_batch_sql.py
-- Captured:  2026-09-16T05:07:10+00:00
-- Scratch:   /tmp/claude-0/-home-user-guidebook/e124fa82-8e34-508e-805f-fe29e0f1c1c9/scratchpad/batch08/walk.db
-- Canonical: data/guidebook.db (schema version 82)
-- Totals:    0 insert(s), 2 update(s)
--
-- No transaction wrapper: the migration runner owns the boundary (F5).
-- Feed this to: python3 scripts/emit_data_migration.py --input <this file>

-- source_value_extractions: 0 insert(s), 2 update(s)
UPDATE "source_value_extractions" SET "notes" = 'FIGURE-ROLE IS finding, NOT claim: 0-4.8 deg is the range the study TESTED AT, not a gradient it recommends. The source measures the EFFECT of slope (articular discomfort rising 14 to 36%) and states no design value. Grading this ''claim'' would let the engine anchor a determination on an experimental condition. || 2026-09-16 figure_role SET finding -> condition (Adversarial pass, 2026-09-16. The schema''s own definitions decide it: figure_role=''finding'' supplies DIRECTION, never value, and this row carries a claimed_value; ''condition'' is defined as ''a rig setting or a limit the value is conditioned by'', which is exactly what a treadmill inclination or a set of laboratory ramp slopes is. db.py''s own refusal text names this case: ''a tested slope read as a claim is how 1:20, 1:16, 1:12, 1:8 became a range no source ever asserted''. The determination is unaffected because both roles are excluded from the governing set, so the cell stays ''pending'' — this corrects the record, not the answer.)', "updated_at" = '2026-09-16 05:06', "figure_role" = 'condition' WHERE "extraction_id" = 11;
UPDATE "source_value_extractions" SET "notes" = 'finding, NOT claim: these are the slopes TESTED, not a recommended gradient. The source''s own conclusion is directional -- ''imperative that bus operators minimize ramp slope'' -- and names no permitted value. Population is able-bodied proxies (n=7, no propulsion experience), graded PROXY. || 2026-09-16 figure_role SET finding -> condition (Adversarial pass, 2026-09-16. The schema''s own definitions decide it: figure_role=''finding'' supplies DIRECTION, never value, and this row carries a claimed_value; ''condition'' is defined as ''a rig setting or a limit the value is conditioned by'', which is exactly what a treadmill inclination or a set of laboratory ramp slopes is. db.py''s own refusal text names this case: ''a tested slope read as a claim is how 1:20, 1:16, 1:12, 1:8 became a range no source ever asserted''. The determination is unaffected because both roles are excluded from the governing set, so the cell stays ''pending'' — this corrects the record, not the answer.)', "updated_at" = '2026-09-16 05:06', "figure_role" = 'condition' WHERE "extraction_id" = 12;