-- data_20260719190934_2026-07-19-non-english-research-recovery-batch7.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-non-english-research-recovery-batch7.md
-- Generated:  2026-07-19T19:09:34+00:00
-- Summary:    Ingest Indonesia's Permen PUPR 14/2017 (first Indonesian jurisdiction); resolve Italian Linee guida n.1 date to 31 marzo 1994 with Legge 724/1994 cross-ref confirmed
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Indonesia: Permen PUPR No. 14/PRT/M/2017 -- currently-operative national building
-- accessibility regulation. Verified via WebSearch-only real retrieval (WebFetch
-- non-functional, 4th consecutive session): complete official title confirmed
-- (no fire-safety-style scope trap like SNI 03-1735-2000), genuine disability-
-- accessibility scope confirmed, JDIH BPK RI status "Berlaku" (in force) confirmed
-- via search snippet of the official record. First Indonesian jurisdiction in the
-- corpus.
INSERT INTO evidence_sources (
  ref_id, source_type, author_count, author_count_is_complete,
  is_corporate_primary, author_display, pub_year, pub_title,
  lang_detected, lang_detection_method, publisher, standard_number,
  url, tier, evidence_type, jurisdiction, metadata_quality,
  verification_status, verification_note, derivation_chain, notes,
  created_at, created_by_session, updated_at, updated_by_session,
  language
) VALUES (
  'REF-00770', 'code', NULL, 0,
  1, 'Kementerian Pekerjaan Umum dan Perumahan Rakyat (Ministry of Public Works and Public Housing, PUPR)', 2017,
  'Peraturan Menteri Pekerjaan Umum dan Perumahan Rakyat Republik Indonesia Nomor 14/PRT/M/2017 tentang Persyaratan Kemudahan Bangunan Gedung',
  'id', 'manual_native_language_verification', 'Kementerian PUPR', '14/PRT/M/2017',
  'https://peraturan.bpk.go.id/Home/Details/104477/permen-pupr-no-14prtm2017-tahun-2017', 6, 'code', 'ID', 'AUTHOR-TITLE-ONLY',
  'VERIFIED-2', '[session_2026-07-19-non-english-research-recovery-batch7] WebFetch non-functional this session (4th consecutive session). Complete official title confirmed identically across the official Kementerian PUPR Cipta Karya site, peraturan.go.id, and JDIH BPK RI (record 104477) via independent WebSearch retrieval -- deliberately checked against the SNI 03-1735-2000 scope-trap lesson from batch 6, and no hidden qualifier was found; the full title is unambiguously about building accessibility (kemudahan bangunan gedung), not a different scope. Genuine disability-accessibility content confirmed: covers ease of access to/from/within buildings, ramps (slope/width specified to enable inter-floor access for disabled users), lifts, and guiding facilities for all users including persons with disabilities (penyandang disabilitas). Legal status "Berlaku" (in force) confirmed via a WebSearch snippet of the JDIH BPK RI status field for record 104477, not a direct page read. Caveat: PP No. 16 Tahun 2021 (the Cipta Kerja-era implementing regulation of the Building Law) now also covers the kemudahan aspect at a higher regulatory tier (Pasal 27, 46), but no source found PP 16/2021 explicitly revoking this Permen -- it appears to remain the operative ministerial technical regulation beneath PP 16/2021, not superseded by it. Exact numeric parameters (ramp gradients, minimum widths) are in the regulation''s technical annexes but were not independently confirmed this session -- not asserted as specific values. Medium-high confidence overall (high on identity/title/scope, medium on current-force status given reliance on a search snippet rather than a direct page read).',
  'Recovered per global-south-finding.md (Indonesian Global-South zero-result investigation, originally flagged batch 1) -- companion candidate Kepmen PU 468/KPTS/1998 was investigated alongside this one and found superseded (see batch 7 exclusion note); this is the first Indonesian jurisdiction ingested into the corpus.',
  'Sets technical ease-of-access (kemudahan) requirements Indonesian buildings must meet to guarantee accessibility and equal facility use for all users including persons with disabilities. Covers horizontal and vertical circulation, ramps, lifts/elevators, stairs, corridors, doors, accessible sanitary facilities, parking, and guiding/wayfinding facilities. Exact numeric specifications were not independently confirmed this session via WebSearch alone and are not asserted here.',
  '2026-07-19T19:10:00Z', 'session_2026-07-19-non-english-research-recovery-batch7', '2026-07-19T19:10:00Z', 'session_2026-07-19-non-english-research-recovery-batch7',
  'id'
);

INSERT INTO source_slug_links (
  ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note
) VALUES (
  'REF-00770', 'wayfinding-global-south', 'WGS-16',
  '2026-07-19T19:10:00Z', 'session_2026-07-19-non-english-research-recovery-batch7',
  '2026-07-19T19:10:00Z', 'session_2026-07-19-non-english-research-recovery-batch7',
  'Indonesian national mandatory building-accessibility regulation, currently in force; first Indonesian jurisdiction in this corpus.'
);

-- Correct the Italian "Linee guida del Ministero della Sanita n. 1" date on
-- REF-00746, previously recorded as uncertain (31 gennaio vs 31 marzo 1994).
-- Resolved via multiple independent WebSearch queries this session: the formal
-- act is dated 31 marzo 1994 (certifico.com and edizionieuropee.it both give
-- this verbatim); a separate 31 maggio 1994 date is the transmission date to
-- the Regions (not the document's own date), which likely fed the earlier
-- "gennaio" confusion. The Legge 23 dicembre 1994, n. 724 cross-reference
-- (art. 3, providing for a future DPCM on new dimensional requirements and a
-- five-year phased adaptation) is now confirmed, not just suspected.
UPDATE evidence_sources
SET notes = 'Primary mandatory Italian regulation establishing RSA (Residenza Sanitaria Assistenziale) structural standards: average 4 modules of 20-25 residents, max 6 modules/120 residents per facility, and 1 of every 3 modules (10-15 places) reserved for dementia care. A companion "Linee guida del Ministero della Sanita n. 1/1994 -- Indirizzi sugli aspetti organizzativi e gestionali delle Residenze Sanitarie Assistenziali" (dated 31 marzo 1994, confirmed batch 7 via independent WebSearch retrieval -- the document was separately transmitted to the Regions on 31 maggio 1994, which is likely the source of an earlier date-confusion artifact) elaborates organizational/management/cost-determination criteria; it is cross-referenced by Legge 23 dicembre 1994, n. 724, art. 3 (confirmed). It remains a separate document, not ingested here -- its content is organizational/managerial, not structural/spatial, so it would not itself anchor built-environment claims even if ingested.',
    derivation_chain = 'Recovered per research-handoff-non-english.md Tier-1 (wayfinding-dementia-spatial-design, IT, 9 non-EN hits) -- batch 2, completing the partial pass from batch 1. Companion "Linee guida n. 1" date resolved batch 7 (session_2026-07-19-non-english-research-recovery-batch7) via WebSearch-only re-verification.',
    updated_at = '2026-07-19T19:10:00Z',
    updated_by_session = 'session_2026-07-19-non-english-research-recovery-batch7'
WHERE ref_id = 'REF-00746';

COMMIT;