-- data_20260724050932_2026-07-24-vestibular-phase-b.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-vestibular-phase-b
-- Generated:  2026-07-24T05:09:32+00:00
-- Summary:    Adversarial correction: narrow REF-00907 attribution on VES cells 9014/9015 (provocation rests on Bronstein alone)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Adversarial-review correction (2026-07-24): over-attribution on VES cells 9014/9015.
-- Independent citation audit found REF-00907 (Saftari & Kwon 2018) supports only "visual-motion
-- perception is integral to balance"; it does NOT establish the visual-vertigo / optokinetic
-- provocation claim — that rests on REF-00908 (Bronstein 2016) alone. Narrow the attribution.
-- governing_refs keeps both (Saftari is legitimate mechanistic support), but the confidence
-- dimension is corrected to attribute the provocation to Bronstein only.
UPDATE evidence_cell_state SET
  confidence_dimensions_present='["Tier 3 review — Bronstein 2016 (REF-00908) — establishes visual-vertigo / vision-induced-dizziness provocation by specular/optokinetic/visually-charged surfaces; Saftari & Kwon 2018 (REF-00907) provides supporting mechanism only (visual-motion perception integral to balance), NOT the provocation claim"]',
  confidence_synthesis_basis='Provisional VES determination (Phase-B verified 2026-07-24; adversarial-corrected): the visual-vertigo provocation anchor is Bronstein 2016 (REF-00908) — a single T3 review; Saftari & Kwon (REF-00907) is supporting mechanism, not a second provocation source. Supports matte, low-reflectance floors for vestibular populations. The <=30-gloss value is inherited from item B-08 (established for other populations), NOT vestibular-validated: DIRECTION provisional (single T3 review), numeric threshold conventional. Single T3 axis => provisional, not stated.',
  updated_at='2026-07-24 05:10', updated_by_session='session_2026-07-24-vestibular-phase-b'
WHERE cell_id=9014;

UPDATE evidence_cell_state SET
  confidence_dimensions_present='["Tier 3 review — Bronstein 2016 (REF-00908) — establishes optokinetic / repeating-high-contrast-pattern and optic-flow provocation of visual vertigo; Saftari & Kwon 2018 (REF-00907) provides supporting mechanism only (visual-motion perception integral to balance), NOT the provocation claim"]',
  confidence_synthesis_basis='Provisional VES determination (Phase-B verified 2026-07-24; adversarial-corrected): optokinetic / repeating-high-contrast pattern and optic-flow provocation anchored on Bronstein 2016 (REF-00908, single T3 review); Saftari & Kwon (REF-00907) is supporting mechanism only. Supports plain, low-geometric-pattern floors. NB tension with junction-contrast items (C-04): localised edge/step contrast for detection is compatible; the harm is large repeating field patterns. Single T3 axis => provisional.',
  updated_at='2026-07-24 05:10', updated_by_session='session_2026-07-24-vestibular-phase-b'
WHERE cell_id=9015;

COMMIT;
