-- data_20260719055205_2026-07-19-non-english-research-recovery-batch4.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-19-non-english-research-recovery-batch4.md
-- Generated:  2026-07-19T05:52:05+00:00
-- Summary:    non-English research recovery batch 4: luminance-contrast-and-pattern (13 items, 0->13 non-EN), fresh-research ingests for mental-health-built-environment + deaf-spatial-design (stub-notes slugs)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- data migration — batch 4 of non-English research recovery
-- Summary: luminance-contrast-and-pattern (2 new + 11 relinks, closing a slug that had rich
-- TIER2 NATIVE SEARCH notes but ZERO source_slug_links) + first fresh-research ingests for two
-- PRE-REMEDIATION-stub slugs (mental-health-built-environment, deaf-spatial-design) where the
-- notes-extraction recovery pipeline doesn't apply (no named instruments in notes) -- these
-- required genuine new primary research, not recovery, and are scoped accordingly (2
-- jurisdictions each, not a full sweep).

BEGIN TRANSACTION;

-- ────────────────────────────────────────────────────────────────────────
-- PART 1 — luminance-contrast-and-pattern: 2 new sources + 11 relinks of already-verified rows.
-- This slug had rich TIER2 NATIVE SEARCH notes (14 languages, real named instruments) but ZERO
-- source_slug_links -- not even English -- discovered this session. Most named instruments
-- (TEK17, DIN 18040 family, Loi 2005/Arretes, BFS/BBR, GB 50763, BR18, CTE DB SUA, DM236/DPR503,
-- 편의증진법, Bouwbesluit/NEN, DL163/2006, Decree241/2017) are ALREADY in evidence_sources from
-- this session's earlier batches -- pure relink, zero new fabrication surface. Two genuinely new,
-- contrast-specific standards (DIN 32975 Germany, NS 11001 Norway) were real-retrieval verified
-- and ingested.
-- ────────────────────────────────────────────────────────────────────────

INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete, is_corporate_primary, author_display,
    pub_year, pub_title, publisher, language, lang_detected, lang_detection_method,
    tier, evidence_type, jurisdiction, standard_number,
    metadata_quality, verification_status, url, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
) VALUES
('REF-00758', 'standard', NULL, 0, 1, 'Deutsches Institut für Normung (DIN), Normenausschuss Medizin NA 063-06-04 AA',
 2009, 'DIN 32975:2009-12 — Gestaltung visueller Informationen im öffentlichen Raum zur barrierefreien Nutzung',
 'DIN', 'de', 'de', 'manual_native_language_verification',
 5, 'national_fw', 'DE', 'DIN 32975:2009-12 (amended Berichtigung 1, 2012-07)',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.dinmedia.de/en/standard/din-32975/122103522',
 '[session_2026-07-19-non-english-research-recovery-batch4] WebFetch non-functional this session (DIN Media, Beuth, standard.no, and ~15 unrelated domains all 403''d, confirmed session-wide tooling issue). Verified via 3+ independent secondary specialist sources (nullbarriere.de -- a well-known German accessibility/DIN-standards reference site; a Bavarian government accessibility-office blog; baunormenlexikon.de) agreeing on title, edition, and the K=0.4/0.7/0.8 threshold structure. "Handrails" attribution to the K>=0.4 tier specifically could not be independently confirmed (floor markings/orientation elements are the consistently-cited K>=0.4 category; handrail contrast is more prominently specified in DIN 32984/related guidance referencing these DIN 32975 values) -- not asserted here beyond what was confirmed.',
 'Recovered per research-handoff-non-english.md Tier-1/2 (luminance-contrast-and-pattern, DE, 8 non-EN hits). This slug had zero source_slug_links despite rich TIER2 NATIVE SEARCH notes -- first substantive ingest for it.',
 'Uses the Michelson contrast formula K=(L1-L2)/(L1+L2). K>=0.4 ("visuell kontrastierend"): orientation/guidance elements, floor-level markings. K>=0.7 ("visuell stark kontrastierend"): text, pictograms/signage, warning-type information. K>=0.8 target specifically for black/white color combinations.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4'),

('REF-00759', 'standard', NULL, 0, 1, 'Standard Norge',
 2018, 'NS 11001-1:2018 — Universell utforming av byggverk — Del 1: Arbeids- og publikumsbygninger (companion NS 11001-2:2018 — Del 2: Boliger)',
 'Standard Norge', 'no', 'no', 'manual_native_language_verification',
 5, 'national_fw', 'NO', 'NS 11001-1:2018 / NS 11001-2:2018',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://online.standard.no/nb/ns-11001-1-2018',
 '[session_2026-07-19-non-english-research-recovery-batch4] WebFetch non-functional this session. Verified via Standard Norge''s own official product pages (online.standard.no, standard.no) plus independent reseller listings (GlobalSpec, Intertek, Accuristech) agreeing on the two-part title structure and 2018 edition (superseding a ~2009 edition, "after nine years" per Standard Norge''s own materials). Contrast thresholds corroborated via Norges Blindeforbund''s practitioner-facing TEK17/NS-11001-consistent guidance (a credible secondary source, not the paywalled primary standard text). The "bathroom floor-wall = 0.4" sub-claim from the search notes could NOT be independently confirmed -- 0.4 was confirmed for guide-lines/general orientation elements specifically, not stated here for bathrooms.',
 'Recovered per research-handoff-non-english.md Tier-1/2 (luminance-contrast-and-pattern, NO, 9 non-EN hits).',
 'Referenced alongside TEK17 §8-6/§12-4/§12-6/§12-9/§12-14. Luminanskontrast >=0.4 for guide lines (ledelinjer) and general orientation/floor guidance elements; >=0.8 for handrails (håndløpere), stair tread/nosing markings (trappeneser), and warning/danger fields (fareflater) before stairs.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4');

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note)
VALUES
 ('REF-00758', 'luminance-contrast-and-pattern', 'LCP-01', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'German luminance-contrast standard, Michelson-formula thresholds -- the slug-specific instrument named in search_languages DE notes.'),
 ('REF-00759', 'luminance-contrast-and-pattern', 'LCP-02', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Norwegian luminance-contrast standard, referenced alongside TEK17 -- the slug-specific instrument named in search_languages NO notes.'),
 ('REF-00415', 'luminance-contrast-and-pattern', 'LCP-03', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified Arrête du 8 décembre 2014 (France) -- search notes: primary regulation uses qualitative "contraste visuel suffisant" language only, no numerical value in primary law.'),
 ('REF-00364', 'luminance-contrast-and-pattern', 'LCP-04', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified DM 236/1989 + DPR 503/96 (Italy) -- search notes: qualitative "contrasto di luminanza" language only, no specific numerical value in primary regulation.'),
 ('REF-00464', 'luminance-contrast-and-pattern', 'LCP-05', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified CTE DB SUA (Spain) -- this link is for DB SUA 9 (Accesibilidad section) "contraste cromático" (chromatic contrast) qualitative language for signage/tactile strips; DISTINCT from the SUA-1 sec.4.3 ramp-gradient table this ref was corrected/relinked for on stair-ramp-threshold-biomechanics-accessibility (batch 2) -- same document, different section, both citations accurate for their respective slugs.'),
 ('REF-00071', 'luminance-contrast-and-pattern', 'LCP-06', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified NEN 9120:2025 (Netherlands, general accessibility standard) -- the instrument named in search_languages NL notes for contrast (alongside Bouwbesluit 2012 and the older, non-binding NEN 1814:2001).'),
 ('REF-00322', 'luminance-contrast-and-pattern', 'LCP-07', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified BFS 2011:6/BBR (Sweden) -- search notes: NCS ljushetskontrast >=0.40 for all contrast markings per BBR avsnitt 3:1, a legally binding threshold (distinct metric from DE Michelson K / UK LRV).'),
 ('REF-00458', 'luminance-contrast-and-pattern', 'LCP-08', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified BR18 (Denmark) -- search notes: functional requirements (funktionskrav) only, no prescriptive numerical values in primary legislation; specific values come from SBi-anvisning 272 (not independently ingested this session).'),
 ('REF-00424', 'luminance-contrast-and-pattern', 'LCP-09', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified Government Decree 241/2017 (Finland) -- search notes: decree framework confirmed but specific numerical luminanssikontrast thresholds not retrieved by the original search.'),
 ('REF-00365', 'luminance-contrast-and-pattern', 'LCP-10', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified Decreto-Lei 163/2006 (Portugal) -- search notes: primary text uses accessible-route/facility language, specific luminance-contrast numerical values not confirmed by the original search.'),
 ('REF-00065', 'luminance-contrast-and-pattern', 'LCP-11', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified バリアフリー法-family standard (Japan, general instrument) -- search notes name a MORE SPECIFIC instrument (道路の移動等円滑化整備ガイドライン / Road Mobility Guideline, 輝度比>=2.0 for tactile guidance blocks) which is NOT independently confirmed/ingested this session; this general link is not a substitute for that specific citation, flagged for a future pass.'),
 ('REF-00511', 'luminance-contrast-and-pattern', 'LCP-12', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified 편의증진법 (Korea) -- search notes: primary regulation covers structural/dimensional requirements; visual/tactile contrast specifics not confirmed by the original search.'),
 ('REF-00462', 'luminance-contrast-and-pattern', 'LCP-13', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Relink of already-verified GB 50763-2012 (China) -- search notes: qualitative language only for stair tread/riser contrast (踏面和踢面的颜色宜有区分和对比), no specific numerical value.');

-- ────────────────────────────────────────────────────────────────────────
-- PART 2 — mental-health-built-environment: 3 new sources from FRESH primary research (this
-- slug's search_languages notes are PRE-REMEDIATION stubs with zero named instruments -- the
-- notes-extraction recovery pipeline does not apply; this is genuine new research, scoped to 2
-- jurisdictions, not a full sweep). Germany: national/federal-level psychiatric-facility design
-- guidance. Netherlands: the de facto national practice standard for acute psychiatric units.
-- ────────────────────────────────────────────────────────────────────────

INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete, is_corporate_primary, author_display,
    pub_year, pub_title, publisher, language, lang_detected, lang_detection_method,
    tier, evidence_type, jurisdiction, standard_number,
    metadata_quality, verification_status, url, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
) VALUES
('REF-00760', 'guideline', NULL, 0, 1, 'universalRAUM-Institut',
 2012, 'Evidenzbasiertes Planungshandbuch Psychiatrie (EPH), Band 1',
 'universalRAUM-Institut; research funded by the Bundesministerium für Wirtschaft und Technologie', 'de', 'de', 'manual_native_language_verification',
 3, 'grey', 'DE', 'ISBN 978-3-86780-304-8',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://eph-psychiatrie.de/',
 '[session_2026-07-19-non-english-research-recovery-batch4] FRESH RESEARCH, not notes-extraction (this slug''s search_languages notes are PRE-REMEDIATION stubs -- see slug-language-tracking-matrix.md). WebFetch non-functional this session. Verified via the companion web portal (eph-psychiatrie.de) structure, an Amazon listing (ISBN), and a secondary "Kurzinfo EPH" document, independently corroborating publisher/funder/year/ISBN. Could not directly read book text -- specific room-dimension/numeric detail is not independently confirmed beyond the topic list in notes below.',
 'Fresh-research recovery per research-handoff-non-english.md, extended to a PRE-REMEDIATION-stub slug (mental-health-built-environment, DE) -- see slug-language-tracking-matrix.md for the substrate-quality distinction from the notes-extraction slugs.',
 'Federally-funded evidence-based planning handbook devoted specifically to psychiatric-facility architecture: wet rooms/bathrooms, doors, windows/façade, building technical services, orientation/wayfinding, staff base and acute-care areas, general design/fittings -- oriented around suicide-prevention design, accessibility, security, and therapeutic environmental design.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4'),

('REF-00761', 'guideline', NULL, 0, 1, 'Deutsche Gesetzliche Unfallversicherung (DGUV), Fachbereich Gesundheitsdienst und Wohlfahrtspflege',
 2019, 'DGUV Information 207-027 — Neu- und Umbauplanung im Krankenhaus unter Gesichtspunkten des Arbeitsschutzes – Anforderungen an Pflegebereiche',
 'DGUV', 'de', 'de', 'manual_native_language_verification',
 5, 'national_fw', 'DE', 'DGUV Information 207-027 (01/2019)',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://kuvb.de/fileadmin/daten/dokumente/GBI/Gesundheitsdienst/DGUV_Information_207-027__Neu-_und_Umbauplanung_im_Krankenhaus_-_Pflegebereiche_.pdf',
 '[session_2026-07-19-non-english-research-recovery-batch4] FRESH RESEARCH (PRE-REMEDIATION-stub slug). WebFetch non-functional this session. Verified via multiple independent statutory-accident-insurer mirror sites (kuvb.de, unfallkasse-nrw.de) hosting the identical document with matching title/number/edition, plus the public "Sicheres Krankenhaus" interpretive portal (jointly published by BGW and Unfallkasse NRW) which republishes this series with dedicated pages for psychiatric/forensic-psychiatric wards -- content details (glazing thickness, flooring class) recurred consistently across independent queries.',
 'Fresh-research recovery per research-handoff-non-english.md, extended to a PRE-REMEDIATION-stub slug (mental-health-built-environment, DE).',
 'National occupational-safety-oriented hospital-planning standard with a dedicated section on closed psychiatric wards (geschlossene psychiatrische Stationen): vandalism-resistant supply-line routing, entrance airlocks/vestibules with lockable storage for prohibited items, hazard-analysis-driven window/door/glazing resistance (4mm polycarbonate interior glazing, 6mm for forensic units), slip-resistant flooring (R10/R11 class) in wet areas, sound insulation and blackout provisions, color-design recommendations.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4'),

('REF-00762', 'book', 4, 1, 0, 'van Mierlo T, Bovenberg F, Voskes Y, Mulder N',
 2013, 'Werkboek HIC: High en Intensive Care in de Psychiatrie',
 'De Tijdstroom / Boom uitgevers', 'nl', 'nl', 'manual_native_language_verification',
 3, 'grey', 'NL', 'ISBN 978-90-5898-235-3',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.tijdschriftvoorpsychiatrie.nl/issues/478/articles/10309',
 '[session_2026-07-19-non-english-research-recovery-batch4] FRESH RESEARCH (PRE-REMEDIATION-stub slug). WebFetch non-functional this session. Verified via a Tijdschrift voor Psychiatrie review, publisher page (boom.nl), and independent project descriptions (e.g. GGz Breburg implementation) corroborating authors/ISBN/publisher/originating field initiative. The underlying "HIC-monitor" audit instrument has been validated across 21 Dutch institutions/38 audits (VUmc research, 2014-2015) and is now the de facto national practice standard for acute/intensive psychiatric admission units -- field-developed, not government-mandated, but nationally adopted. Specific room-layout detail is drawn from secondary project descriptions, not the primary text (which could not be directly fetched).',
 'Fresh-research recovery per research-handoff-non-english.md, extended to a PRE-REMEDIATION-stub slug (mental-health-built-environment, NL). A second NL candidate (College bouw zorginstellingen "Referentiekader bestaande bouw AWBZ") was investigated and found to be a defunct/historical national standard (the issuing body was dissolved ~2009 when Dutch healthcare-building financing moved to a market-based system) -- not ingested, since citing it as current guidance would be misleading; flagged in the coverage matrix instead.',
 'The HIC-monitor quality instrument (built on this workbook) includes "ruimtelijke vormgeving" (spatial/architectural design) as one of ten quality dimensions: avoiding corners/niches to maintain staff sightlines, central staff positioning with unit-wide overview, three graduated security levels within a unit (High Care / Intensive Care / extra-secure EBK rooms), calming color schemes, cleanable flooring, non-institutional park-like building appearance.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4');

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note)
VALUES
 ('REF-00760', 'mental-health-built-environment', 'MHB-26', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Federally-funded German evidence-based psychiatric-facility planning handbook.'),
 ('REF-00761', 'mental-health-built-environment', 'MHB-27', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'National German occupational-safety standard with concrete psychiatric-ward provisions (glazing, flooring, security).'),
 ('REF-00762', 'mental-health-built-environment', 'MHB-28', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'De facto national Dutch practice standard for acute/intensive psychiatric unit design, field-validated across 21 institutions.');

-- ────────────────────────────────────────────────────────────────────────
-- PART 3 — deaf-spatial-design: 2 new sources from FRESH primary research (same PRE-REMEDIATION-
-- stub situation as Part 2). Neither Germany nor Japan has a binding national standard for
-- Deaf-specific spatial design (distinct from general accessibility/acoustic codes) -- that
-- absence is itself recorded honestly, not papered over. Ingested instead: the strongest real,
-- citable, Deaf-spatial-design-specific source found per jurisdiction. Japan's second addition
-- (Metote Lab) is DEAF-LED lived-experience research -- flagged as Co-1 evidence, a track this
-- corpus has documented as thin and skewed toward US/UK English sources (README.md: "29 co1
-- sources linked but 26/29 English, 21/29 US+UK").
-- ────────────────────────────────────────────────────────────────────────

INSERT INTO evidence_sources (
    ref_id, source_type, author_count, author_count_is_complete, is_corporate_primary, author_display,
    pub_year, pub_title, publisher, language, lang_detected, lang_detection_method,
    tier, evidence_type, jurisdiction, standard_number, co1_provenance, co1_source_type,
    metadata_quality, verification_status, url, verification_note, derivation_chain, notes,
    created_at, created_by_session, updated_at, updated_by_session
) VALUES
('REF-00763', 'grey', NULL, 0, 1, 'Koch JP (profiled); Deutsches Architektenblatt',
 2019, 'Deaf Space: Die richtige Architektur für Gehörlose – inklusive Checkliste',
 'Deutsches Architektenblatt (DABonline) — Bundesarchitektenkammer', 'de', 'de', 'manual_native_language_verification',
 3, 'grey', 'DE', NULL, NULL, NULL,
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.dabonline.de/architektur/deaf-space-die-richtige-architektur-bauen-fuer-gehoerlose-jan-philipp-koch/',
 '[session_2026-07-19-non-english-research-recovery-batch4] FRESH RESEARCH (PRE-REMEDIATION-stub slug). WebFetch non-functional this session. Verified via multiple independent WebSearch passes returning consistent detail (the specific checklist content, the nose-shadow/lip-reading lighting point), published by Deutsches Architektenblatt, the official professional journal of the German Chambers of Architects. Germany has NO binding national standard for Deaf-specific spatial design -- DIN 18040 covers only the general "two-senses principle" (accessibility doctrine, not DeafSpace-style design) and is not cited as a substitute here. A frequently-surfacing "Richtlinien Hörbehindertengerechtes Bauen" document is Swiss (SIA 500:2009 Appendix F), not German -- explicitly NOT conflated with a German source.',
 'Fresh-research recovery per research-handoff-non-english.md, extended to a PRE-REMEDIATION-stub slug (deaf-spatial-design, DE).',
 'Profiles Dr. Jan Philipp Koch, a Deaf German architect, on DeafSpace-specific design applied to his own residence: near-total absence of internal partition walls to preserve sightlines; large glass fronts and glazed corridor corners so approaching people are visible; indirect/diffuse lighting avoiding glare and the "nose-shadow" effect that impairs lip-reading under direct/downward light. A related built exemplar (Elbschule Hamburg, a German school for Deaf/hard-of-hearing students, occupied 2013) applies the same principles (glazed corridor corners, recessed monitors, light-signal systems) but is not separately ingested -- documented here as corroborating context.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4'),

('REF-00764', 'grey', NULL, 0, 1, 'Tsukuba University of Technology (国立大学法人筑波技術大学)',
 2025, '天久保キャンパス (Amakubo Campus) facilities description',
 'Tsukuba University of Technology', 'ja', 'ja', 'manual_native_language_verification',
 3, 'grey', 'JP', NULL, NULL, NULL,
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://www.tsukuba-tech.ac.jp/introduction/openinfo/educational_info/amakubo_campus.html',
 '[session_2026-07-19-non-english-research-recovery-batch4] FRESH RESEARCH (PRE-REMEDIATION-stub slug). WebFetch non-functional this session. Verified via the university''s own official site content plus a corroborating June 2025 news item ("デフスペースデザイン講演会を開催" / DeafSpace Design Lecture Held) on the same domain, independently confirmed via two WebSearch queries. Japan also has NO binding national government standard for Deaf-specific spatial design (general バリアフリー法 is accessibility law, not Deaf-spatial-specific, and is not cited as a substitute).',
 'Fresh-research recovery per research-handoff-non-english.md, extended to a PRE-REMEDIATION-stub slug (deaf-spatial-design, JA). Tsukuba University of Technology is Japan''s only national university established specifically for deaf/hard-of-hearing and visually-impaired students.',
 'The university''s own site describes deliberate sightline design: main pedestrian routes never cross vehicle routes; connecting corridors/building wings allow sightlines across the central courtyard, explicitly stated as easing communication and enabling visual situational awareness and rapid guidance during emergencies (visual cues substituting for audible ones). The university states faculty are actively conducting "デフスペースデザイン" (DeafSpace Design) research and hosted a 2025 lecture with Gallaudet-affiliated DeafSpace experts.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4'),

('REF-00765', 'grey', NULL, 0, 0, 'めとてラボ (Metote Lab)',
 2024, 'デフスペースデザインリサーチ：目で聴く家 (DeafSpace Design Research: The House That Listens With Eyes)',
 'めとてラボ (Metote Lab), 東京アートポイント計画 (Tokyo Art Point Project, Arts Council Tokyo-affiliated); grant funding from 窓研究所 (Mado Research Institute)', 'ja', 'ja', 'manual_native_language_verification',
 3, 'grey', 'JP', NULL, 'BPC', 'dpo_research',
 'AUTHOR-TITLE-ONLY', 'VERIFIED-2', 'https://note.com/metotelab/n/n67c67f19d745',
 '[session_2026-07-19-non-english-research-recovery-batch4] FRESH RESEARCH (PRE-REMEDIATION-stub slug). WebFetch non-functional this session. Verified via Metote Lab''s own published account (note.com) and its Arts Council Tokyo / Tokyo Art Point Project affiliation. HONEST SCOPE NOTE: this is Tokyo-metropolitan-scoped, not a national-government source -- flagged as such, included specifically because it is genuinely DEAF-LED lived-experience research (Co-1 track), which this corpus has documented as thin and skewed toward US/UK English sources (README.md: "29 co1 sources linked but 26/29 English, 21/29 US+UK"). This is a non-English, non-US/UK Co-1 addition.',
 'Fresh-research recovery per research-handoff-non-english.md, extended to a PRE-REMEDIATION-stub slug (deaf-spatial-design, JA) -- deliberately sought as a Co-1 counterweight, not just a second national-instrument citation.',
 'A Deaf-led design research project studying homes where Deaf families actually live, examining from a Deaf-culture perspective what spatial/design elements make a home comfortable (distinct from professional/architect-authored guidance). Regional (Tokyo) in scope, not a national standard -- cited as Co-1 lived-experience evidence, not as a code-baseline or best-practice-anchoring national instrument.',
 strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4');

INSERT INTO source_slug_links (ref_id, slug, local_ref_id, created_at, created_by_session, updated_at, updated_by_session, relevance_note)
VALUES
 ('REF-00763', 'deaf-spatial-design', 'DSD-11', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'German professional-journal DeafSpace design checklist (sightlines, glazing, lip-reading-safe lighting).'),
 ('REF-00764', 'deaf-spatial-design', 'DSD-12', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'National Japanese Deaf-serving university''s own campus DeafSpace-design description (sightlines, circulation, emergency visual communication).'),
 ('REF-00765', 'deaf-spatial-design', 'DSD-13', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'session_2026-07-19-non-english-research-recovery-batch4', 'Deaf-led (Co-1) lived-experience design research, Tokyo -- deliberately sought as a non-English/non-US-UK Co-1 counterweight.');

COMMIT;