-- data_20260724050032_2026-07-24-vestibular-phase-b.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-vestibular-phase-b
-- Generated:  2026-07-24T05:00:32+00:00
-- Summary:    Backfill §2.3 confidence flags on regulatory-stratum cells 9012/9013 (A-02/A-08×ALL)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Backfill omitted §2.3 confidence flags on two pre-existing regulatory-stratum provisional
-- cells (9012 A-02×ALL, 9013 A-08×ALL; created 2026-07-19 batch-grading, flags left NULL).
-- Both anchor solely on REF-00563 = ANSI/ASA S12.60-2010 Part 1 (T4 acoustic standard).
-- Determination UNCHANGED (provisional, regulatory-stratum, weak-band); this only supplies the
-- required confidence dimensions so the cell-state machine (validate_evidence_state) passes.
UPDATE evidence_cell_state SET
  confidence_dimensions_present='["Tier 4 evidence-based standard: ANSI/ASA S12.60-2010 Part 1 (Schools) — REF-00563"]',
  confidence_dimensions_absent='["No Tier 1 clinical","No Co-1 lived-experience","No Tier 2 synthesis","No Co-2 CPG","No Tier 3 clinical"]',
  confidence_synthesis_basis='Regulatory-stratum floor: the acoustic value derives from a single T4 evidence-based standard (ANSI/ASA S12.60-2010 Part 1). NOT an evidence-anchored best practice — no clinical anchoring dimension; renders as weak-band (○) best-practice-as-currently-known only (Option A, DR-2026-07-21). §2.3 confidence flags backfilled 2026-07-24; determination unchanged.',
  updated_at='2026-07-24 04:12', updated_by_session='session_2026-07-24-vestibular-phase-b'
WHERE cell_id IN (9012,9013) AND confidence_synthesis_basis IS NULL;

COMMIT;
