-- data_20260913060013_2026-09-13-derivation-handshake.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-13-derivation-handshake.md
-- Generated:  2026-09-13T06:00:13+00:00
-- Summary:    H3: promote the functional-deficit-auditor population<->ICF mapping into population_icf_links; log the 7 unmapped pre-DR-2026-07-23 codes as a finding rather than aliasing them
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

-- H3: promote the functional-deficit-auditor's population<->ICF mapping into rows.
--
-- Ratified 2026-07-13 (DR-2026-07-13-value-genealogy-and-derivation-handshake), stated at
-- governance/evidence-architecture.md section 5.5: "One table (population_icf_links):
-- population code x ICF d-code x mechanism x confidence x provenance, promoting the FDA
-- mapping and the armature's mapping-confidence classifications out of prose into
-- provenance-bearing rows."
--
-- THE NAMED RECONCILIATION SUB-STEP, which doctrine requires to run BEFORE load: "the FDA
-- vocabulary and the live populations table disagree, so the migration ships an
-- FDA-code -> population-code crosswalk in which EVERY MAPPING IS A RECORDED ROW and EVERY
-- UNMAPPED CODE IS LOGGED AS A FINDING -- no silent aliasing, no FK failures discovered at
-- load time."
--
-- Reconciliation result, derived by parsing the skill against the live table rather than
-- transcribed: 14 mapping rows, 7 identity-mappable, 7 unmapped.
--
-- THE 7 UNMAPPED CODES ARE NOT ALIASED, and the reason is a rule, not caution. UPL, VIS,
-- OFS, ABI, ASD, LOW-VISION and PCS are the pre-DR-2026-07-23 taxonomy; that directive
-- replaced the population set with the flat 23 the live table holds. Some replacements look
-- obvious (ASD -> AUT) and some do not (LOW-VISION -> ?), and the difference does not matter:
-- choosing any of them is authoring population taxonomy, which CLAUDE.md section 8 places
-- under owner sign-off. They are logged as a finding below.
--
-- THAT FINDING IS ITSELF THE MECHANISM WORKING. Doctrine's argument for this table is that
-- it is "simultaneously the forward map and the substrate for REVERSE-mapping, which is what
-- would have flagged DEAF's absence from the corridor item's population links MECHANICALLY
-- rather than by eye". The first thing the reverse direction flags is that the auditor skill
-- still teaches a taxonomy retired fourteen months ago -- the same defect a doctrine audit
-- found by reading on 2026-09-13, now reachable by query.
--
-- MAPPING CONFIDENCE is 'high_predictive' for every promoted row: these are the FDA's own
-- primary-ICF-code assignments, which the skill states as the characteristic function of the
-- population rather than as a contextual association. A row derived later from a study
-- carries its own grade and its own provenance.

INSERT INTO population_icf_links
    (population_code, icf_code, mechanism, mapping_confidence, provenance,
     notes, created_at, created_by_session)
VALUES
    ('MOB', 'd410', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd420', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd450', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd455', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd460', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd465', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd470', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd510', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MOB', 'd530', 'Biomechanical — ambulation, balance, transfer, wheelchair use', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('DEM', 'd230', 'Cognitive — memory, attention, wayfinding, sequencing', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('DEM', 'd460', 'Cognitive — memory, attention, wayfinding, sequencing', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('DEM', 'd710–d729', 'Cognitive — memory, attention, wayfinding, sequencing', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('PAIN', 'd410', 'Pain-limited activity endurance; fatigue accumulation', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('PAIN', 'd450', 'Pain-limited activity endurance; fatigue accumulation', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('PAIN', 'd455', 'Pain-limited activity endurance; fatigue accumulation', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('PAIN', 'd640', 'Pain-limited activity endurance; fatigue accumulation', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('NDV', 'd230', 'Sensory processing, predictability, social navigation', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('NDV', 'd710–d729', 'Sensory processing, predictability, social navigation', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('NDV', 'd910–d920', 'Sensory processing, predictability, social navigation', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('DEAF', 'd310–d329', 'Sensory — communication, alert receipt', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('DEAF', 'd330–d349', 'Sensory — communication, alert receipt', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd410', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd420', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd450', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd455', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd465', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd510', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd520', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd530', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('SCI', 'd630', 'Biomechanical + autonomic', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MH', 'd230', 'Psychological — routine, retreat, sensory safety', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MH', 'd570', 'Psychological — routine, retreat, sensory safety', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MH', 'd710–d729', 'Psychological — routine, retreat, sensory safety', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake'),
    ('MH', 'd910', 'Psychological — routine, retreat, sensory safety', 'high_predictive', 'fda-skill-2026-09-13', 'promoted from skills/functional-deficit-auditor_SKILL.md', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake');

-- Every unmapped code, logged as a finding rather than guessed.
INSERT INTO gaps (gap_id, category, priority, status, skill, section, description,
                  created_at, created_by_session, updated_at, updated_by_session,
                  mining_addressability)
VALUES ('GAP-H3-CROSSWALK', 'ST', 'P2', 'OPEN', 'functional-deficit-auditor', 'evidence-architecture.md section 5.5 (H3)',
        'H3 reconciliation finding: the functional-deficit-auditor skill maps 7 population codes that are not in the live populations table -- UPL, VIS, OFS, ABI, ASD, LOW-VISION, PCS. These are the pre-DR-2026-07-23 taxonomy, which that owner directive replaced with the flat 23. They are NOT aliased into live codes: choosing a replacement is population-taxonomy content under CLAUDE.md section 8''s owner-sign-off list. Until they are ruled, the population<->function map is missing the characteristic functions of every population they covered, so reverse-mapping cannot flag an absence for those. Remedy: an owner ruling on the crosswalk, then a follow-up migration that loads the remaining rows.', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake', '2026-09-13 06:00', 'session_2026-09-13-derivation-handshake', 'NOT-ADDRESSABLE');