-- data_20260918014853_2026-09-18-research-batch-13-co2-occupational-therapy.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-09-18-research-batch-13-co2-occupational-therapy.md
-- Generated:  2026-09-18T01:48:53+00:00
-- Summary:    batch 13 part 1 of 2: retire specification 5 for parameter 3 (new evidence, REF-00997)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

UPDATE "specifications" SET "updated_at" = '2026-09-18 01:48', "updated_by_session" = 'session_2026-09-18-research-batch-13-co2-occupational-therapy', "retired_at" = '2026-09-18 01:48', "retired_by_session" = 'session_2026-09-18-research-batch-13-co2-occupational-therapy', "retirement_reason" = 'New evidence arrived for parameter 3. REF-00997 adds a governing claim (1:14 <=, rise >190mm), a condition (1:8 <=, rise <190mm) and a finding (the prescriber must assess whether THIS client can propel the recommended gradient). A determination is computed from the evidence set that existed when it ran; this one predates all three rows. Retired so the cell can be re-determined, not because its value was found wrong.' WHERE "specification_id" = 5;