-- data_20260525040000_b11_sea_supersession_audit.sql
-- DR-2026-05-24 Pass 2: SEA retroactive supersession audit (school-environment-autism)
-- 17 anchors audited (2 T2 SR + 13 T3 + 2 T4)
-- Distribution: 11 current_best + 6 refined_by. Composite cluster search caught Zaikina 2025 SR
-- (autism lighting+color) refining T2 SRs Tola 2021 + Abdelmoula 2024; Al Qutub 2026 (autism
-- multi-IEQ Saudi Arabia) refining 4 T3 anchors on jurisdictional + multi-IEQ-integration dimensions.
-- No Co-1 anchors in this slug; owner Co-1 decision not consumed here.

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-f9f58efe1194', 'school-environment-autism', 'SEA-01', 'REF-00642', 3, 'grey', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Simpson 2025 grey-lit autism school environment. Already 2025; current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-a6c684a1d797', 'school-environment-autism', 'SEA-02', 'REF-00710', 2, 'sr_meta', 'refined_by', NULL, '["10.1177/19375867251373096"]', 'Lighting + color SR sub-dimension: Zaikina 2025 HERD focused SR refines Tola 2021 broader autism BE SR.', NULL, '{"tool": "composite", "query": "autism built environment design systematic review + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:27Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'pubmed_search', 'Tola 2021 in both CWD-07 and SEA-02. Consistent refinement.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-59c22a5c6c80', 'school-environment-autism', 'SEA-03', 'REF-00711', 2, 'sr_meta', 'refined_by', NULL, '["10.1177/19375867251373096"]', 'Lighting + color SR sub-dimension: Zaikina 2025 HERD focused SR refines Abdelmoula 2024 inclusive architecture guidelines.', NULL, '{"tool": "composite", "query": "autism built environment design systematic review + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:27Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'pubmed_search', 'Abdelmoula 2024 inclusive architecture refined by Zaikina 2025.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-3c54a44908c2', 'school-environment-autism', 'SEA-bw-711-724', 'REF-00724', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Mostafa 2014 ARCHITECTURE FOR AUTISM. Sequential Mostafa series; SEA-bw-711-725 2023 is latest. Anchor remains foundational ASPECTSS reference for 2014 specification.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-7169af476557', 'school-environment-autism', 'SEA-bw-711-725', 'REF-00725', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Mostafa 2023 ASPECTSS-based design intervention impact. Already 2023; current intervention-effectiveness study.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-f5797ef3c2e2', 'school-environment-autism', 'SEA-bw-712', 'REF-00712', 4, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:55Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Bates 2016 Care and Design. Specialized care+design T4-classified work; no replacement. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-0565386979e5', 'school-environment-autism', 'SEA-bw-713', 'REF-00713', 3, 'clinical', 'refined_by', NULL, '["10.1016/j.envpol.2026.127992"]', 'Jurisdictional IEQ refinement: Al Qutub 2026 Saudi Arabia multi-IEQ refines Barakat 2019 nature-as-healer on broader environmental quality dimension.', NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Al Qutub 2026 adds non-Western jurisdictional + multi-parameter IEQ context to nature/biophilia anchor.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-e984c3e15ea7', 'school-environment-autism', 'SEA-bw-714', 'REF-00714', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Mostafa 2010 housing adaptation adults autism. Foundational; sequential refinements by same author in slug. Current best for housing-adaptation specifically.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-51f666c403bc', 'school-environment-autism', 'SEA-bw-715', 'REF-00715', 1, 'clinical', 'refined_by', NULL, '["10.1016/j.envpol.2026.127992", "10.1177/19375867251373096"]', 'Preschool sensory environment + participation refined: Al Qutub 2026 age 5-12 multi-IEQ + Zaikina 2025 SR lighting/color extend the sensory-environment evidence.', NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Piller 2016 preschool anchor remains current for participation outcome; new evidence refines IEQ and lighting/color sub-dimensions.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-010e0e77585f', 'school-environment-autism', 'SEA-bw-716', 'REF-00716', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'McAllister 2012 design considerations for ASD classrooms. 13-year-old anchor; Mostafa 2023 ASPECTSS and Abdelmoula 2024 cover newer frameworks. Anchor remains foundational for design-considerations enumeration.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-4cdb2db55c0a', 'school-environment-autism', 'SEA-bw-717', 'REF-00717', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:54Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Allister 2016 participatory design with autistic pupils. Specialized participatory methodology; no replacement. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-ca66f1526f9d', 'school-environment-autism', 'SEA-bw-718', 'REF-00718', 4, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:55Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Deochand 2015 Intensive Autism Treatment design considerations. Specialized treatment-setting; no replacement. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-b6e2559e8568', 'school-environment-autism', 'SEA-bw-719', 'REF-00719', 3, 'clinical', 'refined_by', NULL, '["10.1016/j.envpol.2026.127992"]', 'Acoustic + multi-IEQ refinement: Al Qutub 2026 measured sound levels among IEQ parameters in 37 autistic students, refining Kanakri 2017 noise + autism evidence.', NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:55Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Kanakri 2017 anchor still governs noise-specific findings; refinement adds cross-jurisdictional + multi-IEQ-integration.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-aacd02b21b39', 'school-environment-autism', 'SEA-bw-720', 'REF-00720', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:55Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Nagib 2018 therapeutic landscapes at home. Specialized home-biophilia work; no replacement. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-3d8772a19e5a', 'school-environment-autism', 'SEA-bw-721', 'REF-00721', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:55Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Tufvesson 2008 building process all-inclusive school. 17-year-old foundational methodology; no replacement. Current best.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-413ff2398b32', 'school-environment-autism', 'SEA-bw-722', 'REF-00722', 1, 'clinical', 'refined_by', NULL, '["10.1016/j.envpol.2026.127992"]', 'Behavioral outcome + multi-IEQ refinement: Al Qutub 2026 BASC-SOS behavioural observations (movement, vocalisation, task engagement) refines Kinnealey 2012 classroom-modification attention/engagement on multi-IEQ-integration dimension.', NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:55Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Kinnealey 2012 classroom modification anchor still governs the intervention specifically.');
INSERT OR REPLACE INTO supersession_check (check_id, slug, local_ref_id, ref_id, anchor_tier, anchor_evidence_type, outcome, superseding_ref_ids, superseding_dois, refinement_dimension, divergence_notes, search_strategy_record, candidates_returned, candidates_reviewed, checked_at, checked_by_session, check_method, notes) VALUES ('SUPCHK-9543af08af27', 'school-environment-autism', 'SEA-bw-723', 'REF-00723', 3, 'clinical', 'current_best', NULL, NULL, NULL, NULL, '{"tool": "composite", "query": "autism built environment design + IEQ multi-parameter + lighting color", "date_filter": "published_after:2022", "candidates_returned": 3, "candidates_reviewed": 3}', 3, 3, '2026-05-25T03:19:55Z', 'session_2026-05-23-bpc-rewrite-phase-b-closure', 'composite', 'Mostafa 2018 designing for autism. Sequential Mostafa chain; current best for 2018 synthesis time point.');

UPDATE bpc_metadata SET supersession_check_complete=1, closure_definition_version='v2',
  updated_at=strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  updated_by_session='session_2026-05-23-bpc-rewrite-phase-b-closure'
 WHERE slug='school-environment-autism';
COMMIT;
