-- data_20260518060000_pass3_batch1_bb93_pas6463.sql
--
-- Phase E.1 pilot Pass 3 (rule #10 reasoning-doc-citations) — first batch.
-- BB93:2015 (REF-00562) source fully read in this session at
-- https://assets.publishing.service.gov.uk/media/5a8170d3e5274a2e8ab54012/BB93_February_2015.pdf
-- All BB93 RDC rows below grounded in the document text read in context.
--
-- PAS 6463 §10 Table 2 (REF-00568) attempted but content beyond fetcher token
-- budget. Honest row recorded as NOT-FOUND with explicit reason; not fabricated
-- as SUPPORTED.

INSERT INTO reasoning_doc_citations (citation_id, reasoning_doc_slug, parameter, jurisdiction, population, claim_type, claimed_value, claimed_unit, claim_text, source_ref_id, source_section, value_match, claim_match, verified_at, verified_by_session, paywall_purchase_candidate, notes)
VALUES ('RDC-RAP-RT60-UK-001', 'room-acoustic-performance', 'RT60', 'UK', 'general (primary classroom)', 'jurisdiction_value', '0.6', 's', NULL, 'REF-00562', 'Table 6, p.33 (new build column)', 'PARTIAL', NULL, '2026-05-18 06:00', 'session_2026-05-17-pilot-pass-3-batch-1', 0, 'BB93 Table 6 specifies Tmf (mid-frequency reverberation time, arithmetic average of 500/1k/2k Hz octave bands per S1.5.1) <= 0.6 s for new-build primary classrooms. Same numerical value as pilot doc but BB93 uses Tmf not RT60 — different metric. Pilot doc step-3 cell "RT60 <= 0.4-0.8 s by room type" is a range covering this point; the value is supported, but the metric label needs correction. PARTIAL: BPC claim should read "Tmf <= 0.6 s" not "RT60 <= 0.6 s".');

INSERT INTO reasoning_doc_citations (citation_id, reasoning_doc_slug, parameter, jurisdiction, population, claim_type, claimed_value, claimed_unit, claim_text, source_ref_id, source_section, value_match, claim_match, verified_at, verified_by_session, paywall_purchase_candidate, notes)
VALUES ('RDC-RAP-RT60-UK-002', 'room-acoustic-performance', 'RT60', 'UK', 'general (secondary classroom)', 'jurisdiction_value', '0.8', 's', NULL, 'REF-00562', 'Table 6, p.33 (new build column)', 'EXACT', NULL, '2026-05-18 06:00', 'session_2026-05-17-pilot-pass-3-batch-1', 0, 'BB93 Table 6 specifies Tmf <= 0.8 s for secondary classroom / general teaching area / seminar room / tutorial room / language laboratory (new build). Pilot doc cites "0.4-0.8 s by room type"; this value sits at the upper bound of that range. Same Tmf-vs-RT60 metric distinction as RDC-RAP-RT60-UK-001 applies.');

INSERT INTO reasoning_doc_citations (citation_id, reasoning_doc_slug, parameter, jurisdiction, population, claim_type, claimed_value, claimed_unit, claim_text, source_ref_id, source_section, value_match, claim_match, verified_at, verified_by_session, paywall_purchase_candidate, notes)
VALUES ('RDC-RAP-RT60-UK-003', 'room-acoustic-performance', 'RT60', 'UK', 'DEAF / hearing-impaired (specially-resourced provision)', 'jurisdiction_value', '0.4', 's', NULL, 'REF-00562', 'Table 6, p.34 (Teaching space intended specifically for students with special hearing or communication needs)', 'PARTIAL', NULL, '2026-05-18 06:00', 'session_2026-05-17-pilot-pass-3-batch-1', 0, 'BB93 Table 6 specifies T <= 0.4 s averaged from 125 Hz to 4 kHz octave bands AND T <= 0.6 s in every octave band in this range — broader-band metric than mid-frequency Tmf used for general rooms, and broader than RT60. The 0.4 numerical value is supported but pilot doc framing as "RT60 <= 0.4 s" is metrically imprecise. PARTIAL: BPC claim should specify "averaged 125 Hz to 4 kHz" per BB93 S1.5.1.');

INSERT INTO reasoning_doc_citations (citation_id, reasoning_doc_slug, parameter, jurisdiction, population, claim_type, claimed_value, claimed_unit, claim_text, source_ref_id, source_section, value_match, claim_match, verified_at, verified_by_session, paywall_purchase_candidate, notes)
VALUES ('RDC-RAP-RT60-UK-004', 'room-acoustic-performance', 'RT60', 'UK', 'NDV/AUT (special hearing or communication needs - inclusive)', NULL, NULL, NULL, 'BB93 S0.4 lists "being on the autistic spectrum" within the population for whom "Pupils with hearing impairment, autism and other special needs are often very sensitive to specific types of noise" and for whom "required reverberation times are shorter" per S0.4 final paragraph.', 'REF-00562', 'Section 0.4, p.13-14 (Provision for children having special hearing or communication needs)', NULL, 'SUPPORTED', '2026-05-18 06:00', 'session_2026-05-17-pilot-pass-3-batch-1', 0, 'BB93 S0.4 explicitly includes autistic spectrum in the population requiring acoustic accommodation and states "required reverberation times are shorter" for this population. SUPPORTED but qualitative — BB93 provides no quantified NDV/AUT-specific RT60. Pilot doc step-3 cell saying "UK (transversal) PAS 6463 qualitative" applies to PAS; for BB93, NDV/AUT is included generally within the special-needs envelope but receives the same numerical target as DEAF (0.4 s averaged 125 Hz-4 kHz) — not a separate quantified row.');

INSERT INTO reasoning_doc_citations (citation_id, reasoning_doc_slug, parameter, jurisdiction, population, claim_type, claimed_value, claimed_unit, claim_text, source_ref_id, source_section, value_match, claim_match, verified_at, verified_by_session, paywall_purchase_candidate, notes)
VALUES ('RDC-RAP-COMP-UK-001', 'room-acoustic-performance', 'comparator-type', 'UK', NULL, 'qualitative', NULL, NULL, 'BB93 is room-type-based: Table 6 specifies values by room category (nursery, primary classroom, secondary classroom, music, drama, hall, etc.) rather than by volume or formula.', 'REF-00562', 'Section 1.5 entire (especially Table 6, p.33-34)', NULL, 'SUPPORTED', '2026-05-18 06:00', 'session_2026-05-17-pilot-pass-3-batch-1', 0, 'Pilot doc step-3 row classifies BB93 as "room-type-based (by space function)". BB93 Table 6 structurally confirms — Tmf maxima keyed to room type with no volume parameter or formula. SUPPORTED.');

INSERT INTO reasoning_doc_citations (citation_id, reasoning_doc_slug, parameter, jurisdiction, population, claim_type, claimed_value, claimed_unit, claim_text, source_ref_id, source_section, value_match, claim_match, verified_at, verified_by_session, paywall_purchase_candidate, notes)
VALUES ('RDC-RAP-STATUTORY-UK-001', 'room-acoustic-performance', 'statutory-status', 'UK', NULL, 'definitional', NULL, NULL, 'BB93 is the normal means of demonstrating compliance with Requirement E4 of the Building Regulations, the School Premises Regulations 2012, and the Independent School Standards 2013.', 'REF-00562', 'Section 0.2.1, p.8 (quoting Approved Document E)', NULL, 'SUPPORTED', '2026-05-18 06:00', 'session_2026-05-17-pilot-pass-3-batch-1', 0, 'Pilot doc step-3 scope column says "new build schools; statutory under Education (School Premises) Regulations." BB93 S0.2.1 confirms via Approved Document E text: "the normal way of satisfying Requirement E4 will be to meet the values for sound insulation, reverberation time and internal ambient noise which are given in section 1 of Building Bulletin 93". S0.2.2 confirms School Premises Regulations linkage. SUPPORTED.');

INSERT INTO reasoning_doc_citations (citation_id, reasoning_doc_slug, parameter, jurisdiction, population, claim_type, claimed_value, claimed_unit, claim_text, source_ref_id, source_section, value_match, claim_match, verified_at, verified_by_session, paywall_purchase_candidate, notes)
VALUES ('RDC-RAP-PAS-UK-001', 'room-acoustic-performance', 'RT60', 'UK', 'NDV/AUT', 'jurisdiction_value', NULL, NULL, 'PAS 6463:2022 §10 Acoustics provides qualitative guidance, no quantified RT60 target for neurodivergent populations.', 'REF-00568', '§10 Acoustics and noise management, p.51-57; Table 2 Recommended room acoustic values, p.54', NULL, 'NOT-FOUND', '2026-05-18 06:00', 'session_2026-05-17-pilot-pass-3-batch-1', 1, 'Verification ATTEMPTED but content beyond fetcher token budget. Fetched PDF returned pp. i-50 only; §10 starts at p.51 and Table 2 at p.54. PAS 6463 is open-access (BSI free PDF via housinglin.org.uk) so not strictly PAYWALL, but the fetcher truncated before reaching cited section. paywall_purchase_candidate=1 flag used as a routing signal that this row needs re-verification with a higher-budget fetch or per-section direct read. Pilot doc claim of "qualitative; no numeric comparator" is plausible given PAS 6463 Foreword self-describes as guidance/recommendations not specification, but NOT verified at the section level. NOT-FOUND honestly recorded rather than fabricated SUPPORTED.');

INSERT INTO data_migrations (migration_id, applied_at, content_sha, applied_by_session, notes)
VALUES (
    'pass3_batch1_bb93_pas6463_2026-05-18',
    '2026-05-18 06:00',
    'insert_7_rdc_rows_BB93_6_PAS6463_1_pilot_pass_3_first_concrete_application',
    'session_2026-05-17-pilot-pass-3-batch-1',
    'Phase E.1 pilot Pass 3 (rule #10 reasoning-doc-citations) first concrete batch. 6 rows against BB93:2015 grounded in full source read this session. 1 NOT-FOUND row against PAS 6463 with honest fetch-budget reason. First demonstrated rule-#10 catch: pilot doc cites BB93 RT60 values that are actually BB93 Tmf — different metric, same numerical value at general rooms but broader-band at DEAF rooms. PARTIAL rows queued for pilot-doc sharpening next session. Pass 3 not complete; remaining sources (Iglehart, Bettarello, Marzi 2024/2025, GB 50118, AIJES) defer to a session with cleaner context budget.'
);
