-- data_20260724062837_2026-07-24-merge-b03-normalize.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-24-merge-b03-normalize
-- Generated:  2026-07-24T06:28:37+00:00
-- Summary:    Normalize doi_resolution_outcome NO-MATCH-PMID-ONLY->NO-MATCH (B03; matches main's committed value)
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Normalize doi_resolution_outcome 'NO-MATCH-PMID-ONLY' -> 'NO-MATCH' (REF-00100, REF-00105).
-- The value comes from data_20260522110000_ato_verified_enrichment.sql but is NOT in the DB's
-- valid vocabulary (test_db_integrity B03: RESOLVED/NO-MATCH/REVERTED). main's committed DB
-- already held 'NO-MATCH' here (a value-level correction invisible to the count-based repro gate);
-- a clean rebuild re-derived the raw value. This forward migration makes committed == rebuild
-- AND satisfies B03. Fix-forward, deterministic.
UPDATE evidence_sources SET doi_resolution_outcome='NO-MATCH',
  updated_at='2026-07-24 06:40', updated_by_session='session_2026-07-24-merge-b03-normalize'
  WHERE doi_resolution_outcome='NO-MATCH-PMID-ONLY';

COMMIT;
