-- data_20260726015205_2026-07-26-energy-conservation-rest-points-seating-adversarial.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-26-energy-conservation-rest-points-seating-adversarial.md
-- Generated:  2026-07-26T01:52:05+00:00
-- Summary:    adversarial pass: read the 4 unread primaries; 7 errors found in my own batches 1-3 incl. a batch-2 prose overclaim, a same-dataset double-count, a circular figure, two tier misclassifications and a wrong R14 diagnosis
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- ADVERSARIAL PASS on batches 1-3 of energy-conservation-rest-points-seating.
-- Prompted by the owner: "adversarial pass. you should be reading your sources btw."
-- The four sources batch 3 admitted unread have now been read (abstracts + method sections via
-- PubMed). Every finding below is an error in MY work, not in the sources.

-- ============ A1. THE BATCH-2 OVERCLAIM (most serious) ============
-- Batch 2 prose asserted: "Six further sources were read ... Not one states a spacing figure."
-- FALSE as written. Only REF-00953 was read in full text (get_full_text_article) and REF-00954
-- was fetched. REF-00955..00959 were ABSTRACT-ONLY (get_article_metadata), as their own
-- verified_by_tool honestly records. An abstract that does not mention spacing does not
-- establish that the paper contains no spacing figure. The row-level metadata was accurate; the
-- PROSE built on it was not, and the prose is what a reader believes.
UPDATE evidence_sources SET
  verification_note = verification_note || ' || ADVERSARIAL CORRECTION 2026-07-26: batch-2 prose described this source as "read". It was NOT - only the PubMed abstract was retrieved. Any batch-2 statement about what this paper does or does not CONTAIN (specifically "states no spacing figure") is unverified for this row and must not be relied on until full text is obtained.',
  updated_at='2026-07-26', updated_by_session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial'
WHERE ref_id IN ('REF-00955','REF-00956','REF-00957','REF-00958','REF-00959');

-- ============ A2. SAME DATASET ADMITTED TWICE ============
-- REF-00963 (IJOSE 2001, 7(1):15-34) and REF-00964 (Appl Ergon 2000, 31(3):329-32) are the SAME
-- STUDY: both n=171 elderly people aged 65+, both metropolitan Sydney NSW, both Kothiyal &
-- Tettey. The 2000 paper is a 4-page data note (22 body dimensions); the 2001 paper is the
-- 20-page treatment adding design implications and application examples. Batch 3 admitted them
-- as two rows without noting this, inflating the apparent source count. This is the SAME ERROR
-- CLASS I caught in batch 1 when Wheels for Wellbeing's 50m turned out to cite the DfT standard
-- it appeared to corroborate - committed by me this time.
UPDATE evidence_sources SET
  notes = notes || ' || ADVERSARIAL CORRECTION 2026-07-26 - NOT AN INDEPENDENT SOURCE FROM REF-00964. Abstract now read: "In all 171 elderly people (males and females, aged 65 years and above) took part in the study", metropolitan Sydney NSW. REF-00964 reports THE SAME 171-person Sydney dataset. These two rows are companion reports of ONE study, not two sources, and must never be counted as independent corroboration of each other. This is the same double-count error class the batch-1 adversarial check caught on the 50m interval.',
  updated_at='2026-07-26', updated_by_session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial'
WHERE ref_id='REF-00963';

UPDATE evidence_sources SET
  notes = notes || ' || ADVERSARIAL CORRECTION 2026-07-26 - NOT AN INDEPENDENT SOURCE FROM REF-00963. Abstract now read: "An anthropometric data set on 171 elderly people in Australia ... 22 body dimensions ... metropolitan Sydney, New South Wales". Same study as REF-00963, published as a short data note in Applied Ergonomics 31(3):329-32 alongside the fuller IJOSE 7(1):15-34 treatment. Companion reports of ONE dataset. My batch-3 note calling this "probably the underlying dataset" for REF-00963 was half right - it is the same data, not an upstream source.',
  updated_at='2026-07-26', updated_by_session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial'
WHERE ref_id='REF-00964';

-- ============ A3. THE 376mm IS CIRCULAR ============
UPDATE evidence_sources SET
  notes = notes || ' || ADVERSARIAL FINDING 2026-07-26 - THE 376mm SEAT-DEPTH FIGURE IS CIRCULAR AND MUST NOT BE READ AS CORROBORATION. REF-00953 writes: "Jean has a buttock to popliteal length of 376 mm ... Kothiyal and Tettey recommend 376 mm for both office and bus seating, exactly right for Jean." Both halves trace to the SAME 171-person Sydney dataset (REF-00963/00964): the percentile and the recommendation are one number appearing twice. "Exactly right for Jean" is therefore a tautology, not an independent match. REF-00953 does not claim otherwise, but a reader - me, in batch 3 - could easily take it as two data points, and the corpus should record that it is one.',
  updated_at='2026-07-26', updated_by_session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial'
WHERE ref_id='REF-00953';

-- ============ A4/A5. THE TWO HOLDEN & FERNIE PAPERS ARE DIFFERENT SPECIES ============
-- Batch 3 filed both at tier 3 identically, having read neither. They are not comparable.
UPDATE evidence_sources SET
  pages_start='39', pages_end='45', volume='20', issue='1', pmid='15676714',
  verification_note='Abstract and method retrieved from PubMed 2026-07-26 (PMID 15676714); DOI confirmed. Batch 3 admitted this row on Crossref metadata alone.',
  notes = notes || ' || ADVERSARIAL RE-READ 2026-07-26 - STRONGER THAN RECORDED, AND A T1 CANDIDATE. Abstract: "An adjustable seating rig was used to create the three-dimensional shape of a static lounge chair. Elderly subjects from long-term care and rehabilitation hospital wards tested the chair. Questionnaires and video tapes were used to evaluate their comfort, posture, safety and ease of ingress/egress. The test shape was modified on the basis of results and retested to a total of four shapes." That is ITERATIVE EXPERIMENTAL MANIPULATION OF THE PARAMETER UNDER DESIGN (chair geometry) with outcome measurement on the served population - which is the tier-system T1 condition. DELIBERATELY NOT RE-TIERED UPWARD HERE: re-tiering on an abstract is precisely the inflation risk batch 3 was criticised for, and the whole point of this pass is to stop treating located-as-verified. Flagged T1-CANDIDATE pending full text. Toronto (Univ of Toronto, Dept of Surgery).',
  updated_at='2026-07-26', updated_by_session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial'
WHERE ref_id='REF-00961';

UPDATE evidence_sources SET
  pages_start='281', pages_end='288', volume='19', issue='4', pmid='15676669', grey_flag=1,
  grey_reason='Design-considerations discussion paper, not primary research - established by reading the abstract 2026-07-26.',
  verification_note='Abstract and method retrieved from PubMed 2026-07-26 (PMID 15676669); DOI confirmed. Batch 3 admitted this row on Crossref metadata alone.',
  notes = notes || ' || ADVERSARIAL RE-READ 2026-07-26 - WEAKER THAN RECORDED, DOWNGRADED TO GREY. Abstract: "Requirements for three types of chairs for the elderly are presented. A description of a typical user of each chair provides a reference for the level of ability that must be accommodated. Features of the chairs ... are discussed." No study, no participants, no measurement - this is a DESIGN-CONSIDERATIONS DISCUSSION PAPER. Batch 3 filed it at tier 3 identically to REF-00961, an experimental study, having read neither. Under tier-system section 5 the T3 species split matters: T3-clinical maps to the full band, T3-grey to the weak band. grey_flag set to 1 so this anchors at weak band only. Downgrading is the safe direction to move on an abstract; that is why it is done here and the REF-00961 upgrade is not.',
  updated_at='2026-07-26', updated_by_session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial'
WHERE ref_id='REF-00962';

-- ============ A6. MY R14 DIAGNOSIS IN BATCH 3 WAS WRONG ============
UPDATE search_executions SET
  findings_note = findings_note || ' || ADVERSARIAL CORRECTION 2026-07-26: THE R14 DIAGNOSIS IN THIS ROW IS WRONG. I recorded that "PubMed returned a single unrelated Holden+Fernie record: late-1980s ergonomics is thinly indexed there, a WRONG-INDEX result rather than absence." Both claims are false. ALL FOUR of the batch-3 primaries are indexed in PubMed - PMIDs 15676714, 15676669, 11276262, 10855457 - and the single record my query returned (15676669) WAS one of my two targets, the 1988 paper. I did not check the returned PMID against what I was looking for, and then blamed the index. The true diagnosis is QUERY SHAPE PLUS MY OWN SCREENING FAILURE. R14 exists to stop exactly this: misattributing a retrieval failure to the wrong cause makes the next session distrust a database that was working.'
WHERE session='session_2026-07-26-energy-conservation-rest-points-seating-b3'
  AND query_text LIKE 'Crossref query.bibliographic: Holden Fernie%';

-- ============ log the reads that this pass actually performed (R8) ============
INSERT INTO search_executions
 (slug, jurisdiction, language, target_tier, target_evidence_type, target_scope, query_text,
  engine, depth_method, mining_direction, results_found, results_screened, results_admitted,
  saturation_signal, admitted_ref_ids, deferred_reason, backfill, session, executed_at,
  findings_note, harm_finding)
VALUES
 ('energy-conservation-rest-points-seating',NULL,'EN',1,'clinical','high_control',
  'OpenAlex + Unpaywall OA-status check on all four batch-3 primaries (10.1016/s0003-6870(99)00052-6, 10.1080/10803548.2001.11076474, 10.1016/0003-6870(89)90007-0, 10.1016/0003-6870(88)90075-0)',
  'registry','systematic','none',4,4,0,'saturated',NULL,NULL,0,'session_2026-07-26-energy-conservation-rest-points-seating-adversarial','2026-07-26',
  'Three of four are closed access with no repository copy (Unpaywall is_oa=false, OpenAlex any_repository_has_fulltext=false). The fourth (Kothiyal 2001) is BRONZE OA with a live publisher PDF URL, but tandfonline returned HTTP 403 to this environment - bronze OA means free-to-read at the publisher, which is exactly the access mode a blocked fetcher cannot use. Recording the distinction because it explains why the batch-3 OpenAlex trick that rescued Ulahannan (GOLD OA, CC BY, repository copy) could not work here.',0),

 ('energy-conservation-rest-points-seating',NULL,'EN',1,'clinical','high_control',
  'Kothiyal anthropometric elderly Australia',
  'pubmed','systematic','backward',2,2,0,'saturated',NULL,NULL,0,'session_2026-07-26-energy-conservation-rest-points-seating-adversarial','2026-07-26',
  'THE READ THAT SHOULD HAVE HAPPENED IN BATCH 3. Returned BOTH Kothiyal papers (PMID 11276262, 10855457) with abstracts. Established that they are ONE study reported twice - n=171, aged 65+, metropolitan Sydney NSW - not two sources, and that the 376mm seat-depth figure is the same dataset percentile restated as a design value. Batch 3 admitted both rows on Crossref metadata and asserted the 2000 paper was "probably the underlying dataset" for the 2001 one; it is the same data.',0),

 ('energy-conservation-rest-points-seating',NULL,'EN',1,'clinical','high_control',
  'Holden Fernie lounge chair elderly specifications',
  'pubmed','systematic','backward',1,1,0,'saturated',NULL,NULL,0,'session_2026-07-26-energy-conservation-rest-points-seating-adversarial','2026-07-26',
  'Returned PMID 15676714, the 1989 specifications paper, which batch 3 had concluded PubMed did not index. A one-word change from the batch-3 query ("chairs...design" to "lounge chair...specifications") was the whole difference. Together with the batch-3 query this shows all four primaries were indexed the entire time and the batch-3 wrong-index diagnosis was mistaken. Abstract reveals the 1989 paper is an iterative rig-based experiment (T1 candidate) and the 1988 paper is a discussion piece (downgraded to grey) - two species batch 3 had filed identically.',0);

-- ============ gaps ============
UPDATE gaps SET
  description = description || ' || ADVERSARIAL PASS 2026-07-26 - PARTIALLY ADDRESSED AND PARTIALLY WORSE. All four primaries have now been READ AT ABSTRACT AND METHOD LEVEL via PubMed (all four were indexed there all along). Two findings change the picture: (a) REF-00963 and REF-00964 are ONE study (n=171, Sydney) reported twice, not two sources; (b) the 376mm seat-depth figure is CIRCULAR - the percentile and the "recommendation" are the same dataset number restated. STILL OPEN because the specific armrest dimensions (730/250/120/120mm) remain unlocated in any abstract and require the 1989 full text, which is closed access with no repository copy.',
  updated_at='2026-07-26', updated_by_session='session_2026-07-26-energy-conservation-rest-points-seating-adversarial'
WHERE gap_id='GAP-310';

INSERT INTO gaps (gap_id, category, priority, status, skill, section, description,
                  falsification_condition, created_at, created_by_session,
                  updated_at, updated_by_session, mining_addressability)
VALUES
 ('GAP-312','EG','P1','OPEN','evidence-auditor','energy-conservation-rest-points-seating',
  'THE GAP-307 EQUITY HARM RESTS ON ONE 25-YEAR-OLD SINGLE-CITY DATASET, AND THIS WAS NEVER STATED. GAP-307 argues that single-height seating excludes 5th-percentile older women and creates DVT and musculoskeletal risk. That argument runs entirely through REF-00953s "Jean", whose percentiles come from Kothiyal & Tettey - now established as ONE study of n=171 people aged 65+ in metropolitan Sydney, collected for publication in 2000/2001. So the harm claim generalises from 171 Sydney residents, measured a quarter-century ago, to seating provision generally. The claim may well be right - secular trends and the direction of the effect both favour it - but batches 2 and 3 presented it without any of this scope. Additionally the DVT and musculoskeletal-damage consequence is REF-00953s own inference in its Discussion, not a measured outcome of that study.',
  'Falsified or narrowed by a contemporary anthropometric dataset from another population showing the 5th-percentile popliteal height does not fall below common seat heights, or by a study measuring seated-pressure or DVT outcomes against seat height directly rather than inferring them.',
  '2026-07-26','session_2026-07-26-energy-conservation-rest-points-seating-adversarial','2026-07-26','session_2026-07-26-energy-conservation-rest-points-seating-adversarial','ADDRESSABLE'),

 ('GAP-313','RP','P1','OPEN','guidebook-auditor','energy-conservation-rest-points-seating',
  'PROSE OVERCLAIMED WHAT HAD BEEN READ, WHILE THE ROW METADATA STAYED HONEST. Batch 2 wrote "Six further sources were read ... Not one states a spacing figure", but five of the six (REF-00955..00959) were retrieved by get_article_metadata - abstracts only - as their own verified_by_tool fields correctly record. The structured data never lied; the narrative built on top of it did, and the narrative is what a reader believes. The specific unsupported claim is the negative one: an abstract omitting a spacing figure does not establish the paper contains none. GENERALISABLE RISK, not a one-off: nothing in the DoD gate compares a claim in prose against the retrieval depth recorded on the rows it cites, so this class of drift is currently invisible to every automated check.',
  'Falsified when the five sources are read in full and either do or do not contain spacing figures - which would settle the underlying question. Structurally addressed if a check is added that flags prose claims about source CONTENT where the cited rows were verified by metadata-only tools.',
  '2026-07-26','session_2026-07-26-energy-conservation-rest-points-seating-adversarial','2026-07-26','session_2026-07-26-energy-conservation-rest-points-seating-adversarial','ADDRESSABLE');

COMMIT;
