-- data_20260721215849_2026-07-21-steinfeld-adversarial-fix.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-21-steinfeld-adversarial-fix.md
-- Generated:  2026-07-21T21:58:49+00:00
-- Summary:    adversarial-fix: REF-00192 is REF-00059 (merge, not DOI-null); restore REF-00060 audit trail
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Adversarial-pass correction to the ratified Steinfeld DOI handling.
-- FINDING: REF-00192 ("...An International Comparison") shares PMID 20402047 with REF-00059 and
-- legitimately carries DOI 10.1080/10400430903520280 -- it is the SAME journal article, NOT a distinct
-- work. Only REF-00060 (the IDEA Center "Final Report") is genuinely distinct. So Steinfeld = 2 works,
-- not 3. Corrects the earlier over-split: merge REF-00192 into REF-00059; give REF-00060 a real audit
-- trail (its VERIFIED status had rested solely on the wrong DOI I nulled).

-- (1) REF-00192 is REF-00059: restore its legitimate DOI, repoint links to REF-00059, supersede it.
UPDATE evidence_sources SET doi='10.1080/10400430903520280', updated_at='2026-07-21T22:30:00Z', updated_by_session='session_2026-07-21-steinfeld-adversarial-fix',
  verification_note=COALESCE(verification_note,'')||' [ADVERSARIAL-FIX 2026-07-21: same journal article as REF-00059 (PMID 20402047, DOI 10.1080/10400430903520280); the earlier DOI-null over-split was wrong. DOI restored; superseded into REF-00059.]'
WHERE ref_id='REF-00192';
UPDATE OR IGNORE source_slug_links SET ref_id='REF-00059', updated_at='2026-07-21T22:30:00Z', updated_by_session='session_2026-07-21-steinfeld-adversarial-fix' WHERE ref_id='REF-00192';
DELETE FROM source_slug_links WHERE ref_id='REF-00192';
UPDATE evidence_sources SET superseded_by_ref_id='REF-00059', updated_at='2026-07-21T22:30:00Z', updated_by_session='session_2026-07-21-steinfeld-adversarial-fix' WHERE ref_id='REF-00192';

-- (2) REF-00060 (distinct Final Report): restore audit trail with the real report URL (WebSearch-corroborated;
--     WebFetch 403 bot-block on the IDEA Center PDF) and mark NO-MATCH for the absent DOI.
UPDATE evidence_sources SET
  url='http://idea.ap.buffalo.edu/wp-content/uploads/sites/110/2019/06/FinalAccessReport.pdf',
  url_accessed='2026-07-21', doi_resolution_outcome='NO-MATCH', updated_at='2026-07-21T22:30:00Z', updated_by_session='session_2026-07-21-steinfeld-adversarial-fix',
  verification_note=COALESCE(verification_note,'')||' [ADVERSARIAL-FIX 2026-07-21: audit trail restored. This is the IDEA Center (Univ. at Buffalo, for US Access Board) Anthropometry of Wheeled Mobility Final Report -- a distinct work from the journal article REF-00059; it has no DOI (NO-MATCH). Report URL WebSearch-corroborated.]'
WHERE ref_id='REF-00060';

COMMIT;
