-- data_20260720051847_2026-07-20-bathroom-typology-global-south-rederivation.sql
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    session_2026-07-20-bathroom-typology-global-south-rederivation.md
-- Generated:  2026-07-20T05:18:47+00:00
-- Summary:    Adversarial-review corrections: REF-00881 Sejong toilet pub_year 2022->2020; tighten NBR 9050 BTG-6 relevance note WC-rim to 43-45cm
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

BEGIN TRANSACTION;

-- Adversarial-review corrections for the bathroom-typology-global-south re-derivation batch
-- (session_2026-07-20-bathroom-typology-global-south-rederivation). A fresh-context reviewer
-- briefed to refute re-retrieved all 8 sources/claims; all 8 held. Two field corrections only.
-- Forward-only: the original migration (data_20260720051528_...) is not edited.

-- (1) REF-00881 (Sejong / Setengah Jongkok toilet): the Water for Women Fund page dates the
-- human-centred design PROCESS to 2020; the ~2022 originally recorded reflected article/publication
-- timing, not the project. Correct pub_year 2022 -> 2020.
UPDATE evidence_sources
  SET pub_year = 2020,
      verification_note = verification_note || ' [ADVERSARIAL 2026-07-20] Reviewer re-read the Water for Women Fund page: the human-centred design process dates to 2020 (not 2022 as first recorded); pub_year corrected 2022->2020. All other fields held.',
      updated_at = '2026-07-20T06:45:00Z', updated_by_session = 'session_2026-07-20-bathroom-typology-global-south-rederivation'
  WHERE ref_id = 'REF-00881';

-- (2) BTG-6 link relevance note (REF-00077 NBR 9050:2020): tighten the WC-height figure to the
-- strict norm value. NBR 9050 fixes the bowl rim at 0.43-0.45 m; "43-46 cm" was loose.
UPDATE source_slug_links
  SET relevance_note = 'Cluster 1 dedup-link: ABNT NBR 9050:2020 (Brazil, pt) — Global-South statutory accessible-bathroom dimensions (1.50m turning circle, 0.80m door, WC bowl rim 0.43-0.45m, grab bars rated ~150kg / 1.5kN). [ADVERSARIAL 2026-07-20: rim height tightened from loose 43-46cm to strict-norm 43-45cm.]',
      updated_at = '2026-07-20T06:45:00Z', updated_by_session = 'session_2026-07-20-bathroom-typology-global-south-rederivation'
  WHERE ref_id = 'REF-00077' AND slug = 'bathroom-typology-global-south';

COMMIT;
