#!/usr/bin/env bash
set -euo pipefail
cd /home/user/guidebook/.claude/worktrees/agent-acceda5e0fdea113d
export GUIDEBOOK_DB_PATH=/tmp/claude-0/-home-user-guidebook/34e8c762-53ff-5f39-b746-3f5298058fcb/scratchpad/b20.db
S=session_2026-09-25-research-batch-20-audit-cluster-templer-fhwa

python3 scripts/db.py log-search --slug accessible-circulation-geometry --language EN --engine nist-nvlpubs --depth-method scoping --session "$S" \
 --target-tier 3 --target-evidence-type grey --target-scope intrinsic --mining-direction none \
 --query-text "FULL-TEXT RETRIEVAL AND READ of candidate 117 (Templer, Mullet, Archea and Margulis, NBS IR 78-1554, An Analysis of the Behavior of Stair Users): nvlpubs.nist.gov/nistpubs/Legacy/IR/nbsir78-1554.pdf, persisted as retrieval-log/<session>/0d39bd2a78b840ff.pdf, then every page's text layer searched with pymupdf for ramp*, slope*, gradient*, incline* and ratio forms 1:N, and the low-text pages checked." \
 --prior-expectation "Committed in priors.md P3 before any query (be427f35): P3a [KNOWN from the runbook] no rampway recommendation, p=0.9, falsified by any passage recommending a ramp gradient or ramp design value; P3b the text layer is readable by pymupdf, p=0.7." \
 --results-found 1 --results-screened 1 --results-admitted 0 --saturation-signal saturated --harm-finding 0 \
 --findings-note "P3a CONFIRMED AND P3b CONFIRMED. HTTP 200, 3.2 MB, 80 pages; the text layer is real (about 93 thousand characters; the twelve low-text pages are stair-inventory plan sheets with riser/tread/width/surface columns, one statistics table, and blank end pages -- the blank one was rendered and looked at). 'ramp' occurs ten times and every one is incidental: the CPSC scope ('stair, ramp and landing accidents'), 'alternatives to stairs ... (elevators, ramps, etc)', a stair 'should be clearly seen as a stair and not mistaken for a ramp', a fall on a stair 'is not like a fall on an even surface like a ramp', and six citations of a forthcoming Templer book (below). 'slope' occurs zero times. 'gradient' occurs eight times and is a FALSE FRIEND: every one is the report's 'orientation gradient', a measure of how many visual orientation factors change from step to step, not an inclination. NO RAMP SLOPE OR LENGTH RECOMMENDATION EXISTS IN THE DOCUMENT. Dated 'February 1976, Issued November 1978' on its title page. ONE FINDING FOR THE FOOTNOTE-c QUESTION, recorded and not resolved: the report repeatedly cites 'Templer, J., Stairs and Ramps, Dowden, Hutchinson and Ross, Stroudsburg, PA., forthcoming' -- a Templer book on stairs AND ramps announced before REF-01005's 1979 report. It joins the 1974 dissertation and the FHWA ramp study (REF-01008) as a possible referent of 'Templer, 1977'; none is chosen." \
 2>&1 | tail -2

python3 scripts/db.py resolve-candidate --candidate-id 117 --disposition REHOME --session "$S" \
 --redescription "REHOME TO stair-ramp-threshold-biomechanics-accessibility (an ACTIVE slug in the slugs table), NOT ADMITTED ON PARAMETER 3. Retrieved in full from NIST (nbsir78-1554.pdf, persisted) and read -- the text layer is sound, and the low-text pages were checked. It is what its title says and what this row's own staging note predicted: a behavioural and accident study of STAIR users for the Consumer Product Safety Commission, with performance statements on risers, treads, handrails, lighting and visual orientation. It contains NO RAMP SLOPE OR LENGTH RECOMMENDATION: every 'ramp' is incidental (scope, alternatives to stairs, not mistaking a stair for a ramp, falls on stairs versus falls on ramps, and citations), and every 'gradient' is the report's 'orientation gradient', a perceptual measure, not a slope. R15 CORRECTIONS: the staged title gives 1978; the title page reads 'February 1976, Issued November 1978' -- the report was written two years before it was issued. The staging premise (nearest resolvable item to footnote c's 'Templer, 1977') was already retracted on 2026-09-20 in favour of candidate 125, now REF-01008. WHAT THE READ ADDS TO THE FOOTNOTE-c QUESTION, WITHOUT ANSWERING IT: the report cites 'Templer, J., Stairs and Ramps, Dowden, Hutchinson and Ross, Stroudsburg, PA., forthcoming' six times -- a Templer book on ramps announced in a 1976-78 federal report. That is a third possible referent for 'Templer, 1977' beside the 1974 dissertation and the FHWA ramp study, and it is NOT chosen here (candidate 115 stays PENDING). Rehome, not out-of-scope: stair-user behaviour, risers, treads and handrails are that slug's subject, and a later pass there should read it as primary stair evidence." 2>&1 | tail -4
