-- 065: seven-stage nomenclature + four lenses in one table.
--
-- AFTER_DATA: 20260827194239
--   This migration renames `decisions` to `base_decisions`, and the data
--   migration of that timestamp INSERTs into `decisions`. On a --rebuild the
--   runner replays every migration from the baseline, so without this marker the
--   rename would run first and the data step would fail on a table that no
--   longer exists. The marker is not paperwork: it is the only thing that keeps
--   `migrate_db.py --rebuild` reproducible, which is what CI compares against.
-- D-0167 spine | D-0168 hand-offs | D-0169 grammar | D-0170 four lenses |
-- D-0171 building | owner instruction 2026-08-28: all four lenses in the
-- same tables after the base phase, and loads of rows is fine.
--
-- Generated by scratchpad/session_2026-08-27-hook-audit/build_065.py.
-- Do not hand-edit: re-run the generator.
--
-- ORDER MATTERS, and the first draft had it wrong. RENAME COMES FIRST, then
-- the rebuilds happen IN PLACE under the new names. ALTER TABLE RENAME
-- repoints every inbound REFERENCES clause; DROP+CREATE does not. Rebuilding
-- case_studies before renaming it left three child tables pointing at a table
-- that no longer existed -- and PRAGMA foreign_key_check called it clean,
-- because all three hold 0 rows. Rule 4: a 0-row object is unproven, not clean.
--
-- WHAT IS DROPPED, AND ON WHAT EVIDENCE:
--   dual homes (rule 5 -- the link table is the pointer, the column the copy):
--     spec_value_probes.population        + probe_population_links
--     reasoning_doc_citations.population  + citation_population_links
--     source_value_extractions.population_code/_label + extraction_population_links
--     case_studies.populations_served_note + case_study_populations
--   measured 0-populated across every live row:
--     term_item_links.population            0 of 147
--     item_population_links.rationale_ref   0 of 372
--
-- NO LINK TABLE IS DROPPED. An earlier draft folded the five 0-row link
-- tables into their parents; that trades a many-to-many for one lens per
-- parent, which is a cardinality regression that 0 rows merely hides.
PRAGMA legacy_alter_table=OFF;

-- 1. the fourth lens needs an FK target. Empty: a medical vocabulary is
--    content doctrine (DG-NON) and is the owner's to write.
CREATE TABLE IF NOT EXISTS base_taxonomy_medical (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  definition TEXT,
  created_at TEXT,
  created_by_session TEXT
);

-- 2. the three registries: rename table, then PK column to `code`.
--    RENAME COLUMN carries every inbound foreign key with it, and rewrites
--    view bodies -- measured on 3.45.1, and it correctly leaves a same-named
--    column on a DIFFERENT table alone.
ALTER TABLE "populations" RENAME TO "base_taxonomy_identity";
ALTER TABLE "base_taxonomy_identity" RENAME COLUMN "population_code" TO "code";
ALTER TABLE "axes" RENAME TO "base_taxonomy_icf";
ALTER TABLE "base_taxonomy_icf" RENAME COLUMN "axis_code" TO "code";
ALTER TABLE "access_needs" RENAME TO "base_taxonomy_needs";
ALTER TABLE "base_taxonomy_needs" RENAME COLUMN "need_code" TO "code";

-- 3. every remaining rename, INCLUDING the tables about to be rebuilt.
ALTER TABLE "access_duration" RENAME TO "base_access_duration";
ALTER TABLE "access_need_axis_map" RENAME TO "base_needs_icf_map";
ALTER TABLE "access_need_icf" RENAME TO "base_access_need_icf_codes";
ALTER TABLE "access_stakes" RENAME TO "base_access_stakes";
ALTER TABLE "bpc_metadata" RENAME TO "synthesis_items";
ALTER TABLE "case_studies" RENAME TO "render_case_studies";
ALTER TABLE "case_study_outcomes" RENAME TO "render_case_study_outcomes";
ALTER TABLE "case_study_populations" RENAME TO "render_case_study_taxonomy_links";
ALTER TABLE "case_study_specs" RENAME TO "render_case_study_specification_links";
ALTER TABLE "case_study_strategies" RENAME TO "render_case_study_strategies";
ALTER TABLE "citation_mining" RENAME TO "research_mining_runs";
ALTER TABLE "citation_population_links" RENAME TO "synthesis_citation_taxonomy_links";
ALTER TABLE "conflicts" RENAME TO "synthesis_conflicts";
ALTER TABLE "connection_targets" RENAME TO "synthesis_connection_links";
ALTER TABLE "connections" RENAME TO "synthesis_connections";
ALTER TABLE "convergence_assessment" RENAME TO "synthesis_convergence";
ALTER TABLE "data_migrations" RENAME TO "base_data_migrations";
ALTER TABLE "decisions" RENAME TO "base_decisions";
ALTER TABLE "economics_entries" RENAME TO "render_economics_entries";
ALTER TABLE "economics_entry_populations" RENAME TO "render_economics_taxonomy_links";
ALTER TABLE "economics_entry_specs" RENAME TO "render_economics_specification_links";
ALTER TABLE "evidence_population_match" RENAME TO "judgment_match_grades";
ALTER TABLE "evidence_sources" RENAME TO "evidence_items";
ALTER TABLE "external_root_registry" RENAME TO "evidence_roots";
ALTER TABLE "extraction_population_links" RENAME TO "judgment_item_taxonomy_links";
ALTER TABLE "gap_mining" RENAME TO "research_gap_mining_runs";
ALTER TABLE "gaps" RENAME TO "research_gaps";
ALTER TABLE "item_audit_runs" RENAME TO "judgment_audit_runs";
ALTER TABLE "item_bpc_links" RENAME TO "synthesis_item_links";
ALTER TABLE "item_population_elaborations" RENAME TO "base_item_taxonomy_elaborations";
ALTER TABLE "items" RENAME TO "render_provisions";
ALTER TABLE "jurisdictional_values" RENAME TO "research_code_leads";
ALTER TABLE "lang_jur_map" RENAME TO "base_lang_jur_map";
ALTER TABLE "life_stage_modifiers" RENAME TO "base_life_stage_modifiers";
ALTER TABLE "pipeline_runs" RENAME TO "base_pipeline_runs";
ALTER TABLE "population_axis_map" RENAME TO "base_identity_icf_map";
ALTER TABLE "probe_population_links" RENAME TO "specification_probe_taxonomy_links";
ALTER TABLE "reasoning_doc_citations" RENAME TO "synthesis_citations";
ALTER TABLE "reference_stubs" RENAME TO "research_stubs";
ALTER TABLE "room_items" RENAME TO "render_room_element_links";
ALTER TABLE "rooms" RENAME TO "base_room_types";
ALTER TABLE "search_admissions" RENAME TO "evidence_admission_links";
ALTER TABLE "search_candidates" RENAME TO "research_candidates";
ALTER TABLE "search_coverage" RENAME TO "research_coverage_links";
ALTER TABLE "search_executions" RENAME TO "research_searches";
ALTER TABLE "search_languages" RENAME TO "research_language_links";
ALTER TABLE "situations" RENAME TO "base_situations";
ALTER TABLE "slugs" RENAME TO "base_slugs";
ALTER TABLE "source_locators" RENAME TO "research_items";
ALTER TABLE "source_slug_links" RENAME TO "evidence_slug_links";
ALTER TABLE "source_value_extractions" RENAME TO "judgment_items";
ALTER TABLE "spec_value_probes" RENAME TO "specification_value_probes";
ALTER TABLE "specifications" RENAME TO "specification_items";
ALTER TABLE "supersession_check" RENAME TO "evidence_supersession_runs";
ALTER TABLE "term_aliases" RENAME TO "base_term_aliases";
ALTER TABLE "term_item_links" RENAME TO "base_term_item_links";
ALTER TABLE "terms" RENAME TO "base_terms";
ALTER TABLE "url_verification_runs" RENAME TO "evidence_url_verification_runs";
ALTER TABLE "weighting_profile" RENAME TO "base_weighting_profile";

-- 3b. columns carrying retired vocabulary, renamed once their table is.
ALTER TABLE "base_identity_icf_map" RENAME COLUMN "population_code" TO "identity_code";
ALTER TABLE "base_identity_icf_map" RENAME COLUMN "axis_code" TO "icf_code";
ALTER TABLE "base_needs_icf_map" RENAME COLUMN "need_code" TO "needs_code";
ALTER TABLE "base_needs_icf_map" RENAME COLUMN "axis_code" TO "icf_code";
ALTER TABLE "base_access_need_icf_codes" RENAME COLUMN "need_code" TO "needs_code";
ALTER TABLE "evidence_roots" RENAME COLUMN "root_population_note" TO "root_group_note";
ALTER TABLE "base_slugs" RENAME COLUMN "serves_axes" TO "serves_icf";
ALTER TABLE "base_situations" RENAME COLUMN "attaches_axes" TO "attaches_icf";

-- 4. drop the 11 views that read a table about to be rebuilt.
DROP VIEW "v_best_practice";
DROP VIEW "v_code_floor_only";
DROP VIEW "v_divergence";
DROP VIEW "v_item_extractions";
DROP VIEW "v_item_provenance";
DROP VIEW "v_pending";
DROP VIEW "v_pmp_latest_walk";
DROP VIEW "v_root_id_conflicts";
DROP VIEW "v_source_reach_all";
DROP VIEW "v_unregistered_roots";
DROP VIEW "v_value_independence";

-- 5. rebuild IN PLACE: one taxonomy column becomes four nullable typed FK
--    columns, a CHECK, and a STORED coalesce. Every original CHECK and every
--    named index is carried across explicitly -- PRAGMA table_info carries
--    neither, and dbcore.check_values() reads the column's own CHECK, so a
--    lost CHECK silently disarms every db.py refusal while it still looks safe.

CREATE TABLE "synthesis_items__065" (
  "slug" TEXT,
  "last_updated" TEXT,
  "jurisdictions_searched" INTEGER DEFAULT 0,
  "co1_pass_count" INTEGER DEFAULT 0,
  "evidence_state" TEXT,
  "pico_complete" INTEGER NOT NULL DEFAULT 0,
  "search_complete" INTEGER NOT NULL DEFAULT 0,
  "bpc_complete" INTEGER NOT NULL DEFAULT 0,
  "citation_mining_complete" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL,
  "created_by_session" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "updated_by_session" TEXT NOT NULL,
  "supersession_check_complete" INTEGER NOT NULL DEFAULT 0,
  "closure_definition_version" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("slug"),
  FOREIGN KEY ("slug") REFERENCES "base_slugs"("slug"),
  CHECK (pico_complete IN (0,1)),
  CHECK (search_complete IN (0,1)),
  CHECK (bpc_complete IN (0,1)),
  CHECK (citation_mining_complete IN (0,1)),
  CHECK (supersession_check_complete IN (0, 1)),
  CHECK (closure_definition_version IS NULL OR closure_definition_version IN ('v1', 'v2')),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "synthesis_items__065" ("slug", "last_updated", "jurisdictions_searched", "co1_pass_count", "evidence_state", "pico_complete", "search_complete", "bpc_complete", "citation_mining_complete", "created_at", "created_by_session", "updated_at", "updated_by_session", "supersession_check_complete", "closure_definition_version", "identity_code") SELECT "slug", "last_updated", "jurisdictions_searched", "co1_pass_count", "evidence_state", "pico_complete", "search_complete", "bpc_complete", "citation_mining_complete", "created_at", "created_by_session", "updated_at", "updated_by_session", "supersession_check_complete", "closure_definition_version", "population" FROM "synthesis_items";
DROP TABLE "synthesis_items";
ALTER TABLE "synthesis_items__065" RENAME TO "synthesis_items";

CREATE TABLE "render_case_studies__065" (
  "case_study_id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "building_type" TEXT NOT NULL,
  "location" TEXT NOT NULL,
  "architect" TEXT,
  "year" INTEGER,
  "setting" TEXT,
  "participant_description" TEXT,
  "evidence_quality_tier" INTEGER,
  "cost_data" TEXT,
  "cost_data_quality" TEXT,
  "part_section" TEXT,
  "limitations" TEXT,
  "harm_finding" INTEGER NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'active',
  "notes" TEXT,
  "created_at" TEXT NOT NULL,
  "created_by_session" TEXT NOT NULL,
  "updated_at" TEXT,
  "updated_by_session" TEXT,
  "design_intent" TEXT,
  "outcome_data" TEXT,
  "conflict_documented" TEXT,
  "failure_notes" TEXT,
  "construction_cost" TEXT,
  "accessible_design_premium" TEXT,
  "funding_sources" TEXT,
  "operational_cost_change" TEXT,
  "remediation_cost" TEXT,
  "roi_data" TEXT,
  "financial_evidence_tier" INTEGER,
  "financial_data_quality" TEXT,
  "evidence_contribution" TEXT,
  "part13_status" TEXT,
  "sources" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("case_study_id"),
  FOREIGN KEY ("slug") REFERENCES "base_slugs"("slug"),
  CHECK (evidence_quality_tier IS NULL
                                        OR evidence_quality_tier BETWEEN 1 AND 3),
  CHECK (cost_data_quality IS NULL OR cost_data_quality IN
                     ('VERIFIED','PROVISIONAL','GREY')),
  CHECK (harm_finding IN (0,1)),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) <= 1)
);
INSERT INTO "render_case_studies__065" ("case_study_id", "slug", "title", "building_type", "location", "architect", "year", "setting", "participant_description", "evidence_quality_tier", "cost_data", "cost_data_quality", "part_section", "limitations", "harm_finding", "status", "notes", "created_at", "created_by_session", "updated_at", "updated_by_session", "design_intent", "outcome_data", "conflict_documented", "failure_notes", "construction_cost", "accessible_design_premium", "funding_sources", "operational_cost_change", "remediation_cost", "roi_data", "financial_evidence_tier", "financial_data_quality", "evidence_contribution", "part13_status", "sources") SELECT "case_study_id", "slug", "title", "building_type", "location", "architect", "year", "setting", "population_description", "evidence_quality_tier", "cost_data", "cost_data_quality", "part_section", "limitations", "harm_finding", "status", "notes", "created_at", "created_by_session", "updated_at", "updated_by_session", "design_intent", "outcome_data", "conflict_documented", "failure_notes", "construction_cost", "accessible_design_premium", "funding_sources", "operational_cost_change", "remediation_cost", "roi_data", "financial_evidence_tier", "financial_data_quality", "evidence_contribution", "part13_status", "sources" FROM "render_case_studies";
DROP TABLE "render_case_studies";
ALTER TABLE "render_case_studies__065" RENAME TO "render_case_studies";
CREATE INDEX "ix_cs_harm" ON "render_case_studies"(harm_finding);
CREATE INDEX "ix_cs_slug" ON "render_case_studies"(slug);

CREATE TABLE "render_case_study_taxonomy_links__065" (
  "case_study_id" TEXT NOT NULL,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("case_study_id"),
  FOREIGN KEY ("case_study_id") REFERENCES "render_case_studies"("case_study_id"),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "render_case_study_taxonomy_links__065" ("case_study_id", "identity_code") SELECT "case_study_id", "population_code" FROM "render_case_study_taxonomy_links";
DROP TABLE "render_case_study_taxonomy_links";
ALTER TABLE "render_case_study_taxonomy_links__065" RENAME TO "render_case_study_taxonomy_links";
CREATE UNIQUE INDEX "ux_render_case_study_taxonomy_links" ON "render_case_study_taxonomy_links" ("case_study_id", "taxonomy_code");

CREATE TABLE "synthesis_citation_taxonomy_links__065" (
  "citation_id" TEXT NOT NULL,
  "note" TEXT,
  "created_at" TEXT,
  "created_by_session" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("citation_id"),
  FOREIGN KEY ("citation_id") REFERENCES "synthesis_citations"("citation_id"),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "synthesis_citation_taxonomy_links__065" ("citation_id", "note", "created_at", "created_by_session", "identity_code") SELECT "citation_id", "note", "created_at", "created_by_session", "population_code" FROM "synthesis_citation_taxonomy_links";
DROP TABLE "synthesis_citation_taxonomy_links";
ALTER TABLE "synthesis_citation_taxonomy_links__065" RENAME TO "synthesis_citation_taxonomy_links";
CREATE INDEX "idx_cpl_pop" ON "synthesis_citation_taxonomy_links"(taxonomy_code);
CREATE UNIQUE INDEX "ux_synthesis_citation_taxonomy_links" ON "synthesis_citation_taxonomy_links" ("citation_id", "taxonomy_code");

CREATE TABLE "render_economics_taxonomy_links__065" (
  "entry_id" TEXT NOT NULL,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("entry_id"),
  FOREIGN KEY ("entry_id") REFERENCES "render_economics_entries"("entry_id"),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "render_economics_taxonomy_links__065" ("entry_id", "identity_code") SELECT "entry_id", "population_code" FROM "render_economics_taxonomy_links";
DROP TABLE "render_economics_taxonomy_links";
ALTER TABLE "render_economics_taxonomy_links__065" RENAME TO "render_economics_taxonomy_links";
CREATE UNIQUE INDEX "ux_render_economics_taxonomy_links" ON "render_economics_taxonomy_links" ("entry_id", "taxonomy_code");

CREATE TABLE "judgment_match_grades__065" (
  "match_id" TEXT,
  "source_ref" TEXT NOT NULL,
  "study_group" TEXT,
  "sample_size" INTEGER,
  "match_grade" TEXT NOT NULL,
  "mismatch_note" TEXT,
  "created_at" TEXT NOT NULL,
  "created_by_session" TEXT NOT NULL,
  "ref_id" TEXT,
  "gap_id" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("match_id"),
  FOREIGN KEY ("gap_id") REFERENCES "research_gaps"("gap_id"),
  FOREIGN KEY ("ref_id") REFERENCES "evidence_items"("ref_id"),
  CHECK (match_grade IN ('EXACT','PARTIAL','PROXY','MISMATCH')),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "judgment_match_grades__065" ("match_id", "source_ref", "study_group", "sample_size", "match_grade", "mismatch_note", "created_at", "created_by_session", "ref_id", "gap_id", "identity_code") SELECT "match_id", "source_ref", "study_population", "sample_size", "match_grade", "mismatch_note", "created_at", "created_by_session", "ref_id", "gap_id", "target_population" FROM "judgment_match_grades";
DROP TABLE "judgment_match_grades";
ALTER TABLE "judgment_match_grades__065" RENAME TO "judgment_match_grades";
CREATE INDEX "idx_epm_gap" ON "judgment_match_grades"(gap_id);
CREATE INDEX "idx_epm_ref" ON "judgment_match_grades"(ref_id);

CREATE TABLE "judgment_item_taxonomy_links__065" (
  "extraction_id" INTEGER NOT NULL,
  "note" TEXT,
  "created_at" TEXT,
  "created_by_session" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("extraction_id"),
  FOREIGN KEY ("extraction_id") REFERENCES "judgment_items"("extraction_id"),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "judgment_item_taxonomy_links__065" ("extraction_id", "note", "created_at", "created_by_session", "identity_code") SELECT "extraction_id", "note", "created_at", "created_by_session", "population_code" FROM "judgment_item_taxonomy_links";
DROP TABLE "judgment_item_taxonomy_links";
ALTER TABLE "judgment_item_taxonomy_links__065" RENAME TO "judgment_item_taxonomy_links";
CREATE INDEX "idx_epl_pop" ON "judgment_item_taxonomy_links"(taxonomy_code);
CREATE UNIQUE INDEX "ux_judgment_item_taxonomy_links" ON "judgment_item_taxonomy_links" ("extraction_id", "taxonomy_code");

CREATE TABLE "base_item_taxonomy_elaborations__065" (
  "elab_id" INTEGER,
  "item_code" TEXT NOT NULL,
  "variant_distinction" TEXT,
  "spec_variant_a" TEXT,
  "spec_variant_b" TEXT,
  "evidence_ref_id" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "created_by_session" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("elab_id"),
  FOREIGN KEY ("evidence_ref_id") REFERENCES "evidence_items"("ref_id"),
  FOREIGN KEY ("item_code") REFERENCES "render_provisions"("item_code"),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "base_item_taxonomy_elaborations__065" ("elab_id", "item_code", "variant_distinction", "spec_variant_a", "spec_variant_b", "evidence_ref_id", "notes", "created_at", "created_by_session", "identity_code") SELECT "elab_id", "item_code", "variant_distinction", "spec_variant_a", "spec_variant_b", "evidence_ref_id", "notes", "created_at", "created_by_session", "population_code" FROM "base_item_taxonomy_elaborations";
DROP TABLE "base_item_taxonomy_elaborations";
ALTER TABLE "base_item_taxonomy_elaborations__065" RENAME TO "base_item_taxonomy_elaborations";
CREATE INDEX "idx_ipe_item" ON "base_item_taxonomy_elaborations"(item_code);
CREATE UNIQUE INDEX "uq_base_item_taxonomy_elaborations_0" ON "base_item_taxonomy_elaborations" ("item_code", "taxonomy_code", "variant_distinction");

CREATE TABLE "specification_probe_taxonomy_links__065" (
  "probe_id" TEXT NOT NULL,
  "note" TEXT,
  "created_at" TEXT,
  "created_by_session" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("probe_id"),
  FOREIGN KEY ("probe_id") REFERENCES "specification_value_probes"("probe_id"),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "specification_probe_taxonomy_links__065" ("probe_id", "note", "created_at", "created_by_session", "identity_code") SELECT "probe_id", "note", "created_at", "created_by_session", "population_code" FROM "specification_probe_taxonomy_links";
DROP TABLE "specification_probe_taxonomy_links";
ALTER TABLE "specification_probe_taxonomy_links__065" RENAME TO "specification_probe_taxonomy_links";
CREATE INDEX "idx_ppl_pop" ON "specification_probe_taxonomy_links"(taxonomy_code);
CREATE UNIQUE INDEX "ux_specification_probe_taxonomy_links" ON "specification_probe_taxonomy_links" ("probe_id", "taxonomy_code");

CREATE TABLE "synthesis_citations__065" (
  "citation_id" TEXT,
  "reasoning_doc_slug" TEXT NOT NULL,
  "parameter" TEXT NOT NULL,
  "jurisdiction" TEXT,
  "claim_type" TEXT NOT NULL,
  "claimed_value" TEXT,
  "claimed_unit" TEXT,
  "claim_text" TEXT,
  "source_ref_id" TEXT NOT NULL,
  "source_section" TEXT,
  "value_match" TEXT,
  "claim_match" TEXT,
  "verified_at" TEXT NOT NULL,
  "verified_by_session" TEXT NOT NULL,
  "paywall_purchase_candidate" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT,
  "setting" TEXT,
  "locator_scheme" TEXT,
  "loc_division" TEXT,
  "loc_part" TEXT,
  "loc_section" TEXT,
  "loc_subsection" TEXT,
  "loc_paragraph" TEXT,
  "loc_clause" TEXT,
  "loc_subclause" TEXT,
  "loc_division_end" TEXT,
  "loc_part_end" TEXT,
  "loc_section_end" TEXT,
  "loc_subsection_end" TEXT,
  "loc_paragraph_end" TEXT,
  "loc_clause_end" TEXT,
  "loc_subclause_end" TEXT,
  "loc_note" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("citation_id"),
  FOREIGN KEY ("reasoning_doc_slug") REFERENCES "base_slugs"("slug"),
  FOREIGN KEY ("source_ref_id") REFERENCES "evidence_items"("ref_id"),
  CHECK (claim_type IN (
        'numerical_spec','jurisdiction_value','qualitative','definitional'
    )),
  CHECK (value_match IN (
        'EXACT','WITHIN-TOLERANCE','DIFFERENT','NOT-FOUND','PAYWALL','SUPERSEDED'
    )),
  CHECK (claim_match IN (
        'SUPPORTED','PARTIAL','NOT-FOUND','PAYWALL','CONTRADICTED'
    )),
  CHECK (paywall_purchase_candidate IN (0,1)),
  CHECK ((claim_type IN ('numerical_spec','jurisdiction_value') AND claimed_value IS NOT NULL AND value_match IS NOT NULL) OR
      (claim_type IN ('qualitative','definitional') AND claim_text IS NOT NULL AND claim_match IS NOT NULL)),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) <= 1)
);
INSERT INTO "synthesis_citations__065" ("citation_id", "reasoning_doc_slug", "parameter", "jurisdiction", "claim_type", "claimed_value", "claimed_unit", "claim_text", "source_ref_id", "source_section", "value_match", "claim_match", "verified_at", "verified_by_session", "paywall_purchase_candidate", "notes", "setting", "locator_scheme", "loc_division", "loc_part", "loc_section", "loc_subsection", "loc_paragraph", "loc_clause", "loc_subclause", "loc_division_end", "loc_part_end", "loc_section_end", "loc_subsection_end", "loc_paragraph_end", "loc_clause_end", "loc_subclause_end", "loc_note") SELECT "citation_id", "reasoning_doc_slug", "parameter", "jurisdiction", "claim_type", "claimed_value", "claimed_unit", "claim_text", "source_ref_id", "source_section", "value_match", "claim_match", "verified_at", "verified_by_session", "paywall_purchase_candidate", "notes", "setting", "locator_scheme", "loc_division", "loc_part", "loc_section", "loc_subsection", "loc_paragraph", "loc_clause", "loc_subclause", "loc_division_end", "loc_part_end", "loc_section_end", "loc_subsection_end", "loc_paragraph_end", "loc_clause_end", "loc_subclause_end", "loc_note" FROM "synthesis_citations";
DROP TABLE "synthesis_citations";
ALTER TABLE "synthesis_citations__065" RENAME TO "synthesis_citations";
CREATE INDEX "idx_rdc_claim_type"  ON "synthesis_citations"(claim_type);
CREATE INDEX "idx_rdc_paywall"     ON "synthesis_citations"(paywall_purchase_candidate) WHERE paywall_purchase_candidate = 1;
CREATE INDEX "idx_rdc_ref"         ON "synthesis_citations"(source_ref_id);
CREATE INDEX "idx_rdc_slug_param"  ON "synthesis_citations"(reasoning_doc_slug, parameter);
CREATE INDEX "ix_rdc_locator" ON "synthesis_citations" (loc_section, loc_clause);

CREATE TABLE "judgment_items__065" (
  "extraction_id" INTEGER,
  "ref_id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "parameter" TEXT NOT NULL,
  "parameter_canonical" TEXT,
  "jurisdiction" TEXT,
  "claim_type" TEXT NOT NULL,
  "claimed_value" TEXT,
  "claimed_unit" TEXT,
  "claim_text" TEXT,
  "source_section" TEXT,
  "extraction_method" TEXT NOT NULL,
  "extraction_status" TEXT NOT NULL DEFAULT 'preliminary',
  "promoted_to_rdc_id" TEXT,
  "notes" TEXT,
  "created_at" TEXT NOT NULL,
  "created_by_session" TEXT,
  "updated_at" TEXT NOT NULL,
  "updated_by_session" TEXT,
  "setting" TEXT,
  "root_id" TEXT,
  "root_type" TEXT,
  "root_ref_id" TEXT,
  "echo_of" TEXT,
  "measurement_paradigm" TEXT,
  "device_class" TEXT,
  "root_group_note" TEXT,
  "file_anchor" TEXT,
  "root_classification_basis" TEXT,
  "contested" INTEGER NOT NULL DEFAULT 0,
  "item_code" TEXT,
  "locator_scheme" TEXT,
  "loc_division" TEXT,
  "loc_part" TEXT,
  "loc_section" TEXT,
  "loc_subsection" TEXT,
  "loc_paragraph" TEXT,
  "loc_clause" TEXT,
  "loc_subclause" TEXT,
  "loc_division_end" TEXT,
  "loc_part_end" TEXT,
  "loc_section_end" TEXT,
  "loc_subsection_end" TEXT,
  "loc_paragraph_end" TEXT,
  "loc_clause_end" TEXT,
  "loc_subclause_end" TEXT,
  "loc_note" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("extraction_id"),
  FOREIGN KEY ("item_code") REFERENCES "render_provisions"("item_code"),
  FOREIGN KEY ("promoted_to_rdc_id") REFERENCES "synthesis_citations"("citation_id"),
  FOREIGN KEY ("ref_id") REFERENCES "evidence_items"("ref_id"),
  FOREIGN KEY ("root_ref_id") REFERENCES "evidence_items"("ref_id"),
  FOREIGN KEY ("slug") REFERENCES "base_slugs"("slug"),
  CHECK (claim_type IN ('numerical','range','qualitative','framework','absent')),
  CHECK (extraction_method IN ('skim','full-read','re-read','auto-mined')),
  CHECK (extraction_status IN ('preliminary','reviewed','verified','contradicted','absent-confirmed')),
  CHECK (root_type IN (
            'measurement_primary', 'participatory_finding',
            'committee_assertion', 'derived_calculation', 'untraced')),
  CHECK (measurement_paradigm IN (
            'swept_path_dynamic', 'static_turning_circle', 'static_clearance',
            'anthropometric_percentile', 'instrumented_physical_measurement',
            'route_metric', 'field_observation', 'participatory_spatial',
            'stated_unmeasured')),
  CHECK (device_class IN (
            'manual_self_propelled', 'manual_attendant', 'power_chair', 'scooter',
            'bariatric_manual', 'bariatric_power', 'walker_rollator',
            'mixed', 'not_device_scoped')),
  CHECK (contested IN (0, 1)),
  CHECK ((claim_type =  'absent' AND claimed_value IS NULL) OR
    (claim_type <> 'absent' AND claimed_value IS NOT NULL)),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) <= 1)
);
INSERT INTO "judgment_items__065" ("extraction_id", "ref_id", "slug", "parameter", "parameter_canonical", "jurisdiction", "claim_type", "claimed_value", "claimed_unit", "claim_text", "source_section", "extraction_method", "extraction_status", "promoted_to_rdc_id", "notes", "created_at", "created_by_session", "updated_at", "updated_by_session", "setting", "root_id", "root_type", "root_ref_id", "echo_of", "measurement_paradigm", "device_class", "root_group_note", "file_anchor", "root_classification_basis", "contested", "item_code", "locator_scheme", "loc_division", "loc_part", "loc_section", "loc_subsection", "loc_paragraph", "loc_clause", "loc_subclause", "loc_division_end", "loc_part_end", "loc_section_end", "loc_subsection_end", "loc_paragraph_end", "loc_clause_end", "loc_subclause_end", "loc_note") SELECT "extraction_id", "ref_id", "slug", "parameter", "parameter_canonical", "jurisdiction", "claim_type", "claimed_value", "claimed_unit", "claim_text", "source_section", "extraction_method", "extraction_status", "promoted_to_rdc_id", "notes", "created_at", "created_by_session", "updated_at", "updated_by_session", "setting", "root_id", "root_type", "root_ref_id", "echo_of", "measurement_paradigm", "device_class", "root_population_note", "file_anchor", "root_classification_basis", "contested", "item_code", "locator_scheme", "loc_division", "loc_part", "loc_section", "loc_subsection", "loc_paragraph", "loc_clause", "loc_subclause", "loc_division_end", "loc_part_end", "loc_section_end", "loc_subsection_end", "loc_paragraph_end", "loc_clause_end", "loc_subclause_end", "loc_note" FROM "judgment_items";
DROP TABLE "judgment_items";
ALTER TABLE "judgment_items__065" RENAME TO "judgment_items";
CREATE INDEX "idx_sve_item" ON "judgment_items"(item_code);
CREATE INDEX "idx_sve_ref"        ON "judgment_items"(ref_id);
CREATE INDEX "idx_sve_slug_param" ON "judgment_items"(slug, parameter_canonical);
CREATE INDEX "idx_sve_status"     ON "judgment_items"(extraction_status);
CREATE INDEX "ix_sve_locator" ON "judgment_items" (loc_section, loc_clause);

CREATE TABLE "specification_value_probes__065" (
  "probe_id" TEXT,
  "walk_id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "item_code" TEXT NOT NULL,
  "spec_value_origin" REAL NOT NULL,
  "spec_unit" TEXT NOT NULL,
  "direction" TEXT NOT NULL,
  "claim_type" TEXT NOT NULL,
  "step_index" INTEGER NOT NULL,
  "phase" TEXT NOT NULL,
  "step_value" REAL NOT NULL,
  "step_value_unit" TEXT NOT NULL,
  "search_query" TEXT,
  "search_query_alt" TEXT,
  "passes_strict" INTEGER,
  "ref_id" TEXT,
  "notes" TEXT,
  "created_at" TEXT NOT NULL,
  "created_by_session" TEXT NOT NULL,
  "setting" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("probe_id"),
  FOREIGN KEY ("item_code") REFERENCES "render_provisions"("item_code"),
  FOREIGN KEY ("ref_id") REFERENCES "evidence_items"("ref_id"),
  FOREIGN KEY ("slug") REFERENCES "base_slugs"("slug"),
  CHECK (direction IN ('up','down')),
  CHECK (claim_type IN (
                            'minimum','maximum','target','range_low','range_high'
                        )),
  CHECK (phase IN (
                            'outer-pass-1st','outer-pass-2nd','outer-stop',
                            'refinement-pass-1st','refinement-pass-2nd','refinement-stop',
                            'final'
                        )),
  CHECK (passes_strict IN (0,1)),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) <= 1)
);
INSERT INTO "specification_value_probes__065" ("probe_id", "walk_id", "slug", "item_code", "spec_value_origin", "spec_unit", "direction", "claim_type", "step_index", "phase", "step_value", "step_value_unit", "search_query", "search_query_alt", "passes_strict", "ref_id", "notes", "created_at", "created_by_session", "setting") SELECT "probe_id", "walk_id", "slug", "item_code", "spec_value_origin", "spec_unit", "direction", "claim_type", "step_index", "phase", "step_value", "step_value_unit", "search_query", "search_query_alt", "passes_strict", "ref_id", "notes", "created_at", "created_by_session", "setting" FROM "specification_value_probes";
DROP TABLE "specification_value_probes";
ALTER TABLE "specification_value_probes__065" RENAME TO "specification_value_probes";
CREATE INDEX "idx_svp_item_phase" ON "specification_value_probes"(item_code, phase);
CREATE INDEX "idx_svp_ref"        ON "specification_value_probes"(ref_id);
CREATE INDEX "idx_svp_slug_item"  ON "specification_value_probes"(slug, item_code);
CREATE INDEX "idx_svp_walk"       ON "specification_value_probes"(walk_id, step_index);

CREATE TABLE "specification_items__065" (
  "specification_id" INTEGER,
  "item_code" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "design_scale" TEXT,
  "convergence_id" INTEGER,
  "confidence_dimensions_present" TEXT,
  "confidence_dimensions_absent" TEXT,
  "confidence_synthesis_basis" TEXT,
  "gap_register_id" TEXT,
  "not_applicable_rationale" TEXT,
  "tier_basis" TEXT,
  "governing_refs" TEXT,
  "rule_version" TEXT,
  "derivation_sha" TEXT,
  "code_floor_only" INTEGER NOT NULL DEFAULT 0,
  "value_min" REAL,
  "value_max" REAL,
  "value_unit" TEXT,
  "falsification_condition" TEXT,
  "has_unverified_sources" INTEGER NOT NULL DEFAULT 0,
  "all_sources_disqualified" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT,
  "created_by_session" TEXT,
  "updated_at" TEXT,
  "updated_by_session" TEXT,
  "regulatory_stratum_only" INTEGER NOT NULL DEFAULT 0,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  PRIMARY KEY ("specification_id"),
  FOREIGN KEY ("convergence_id") REFERENCES "synthesis_convergence"("convergence_id"),
  FOREIGN KEY ("gap_register_id") REFERENCES "research_gaps"("gap_id"),
  FOREIGN KEY ("item_code") REFERENCES "render_provisions"("item_code"),
  CHECK (state IN ('stated', 'provisional',
                                                    'pending', 'not_applicable')),
  CHECK (design_scale IN ('universal', 'population', 'person')),
  CHECK (governing_refs IS NULL OR json_valid(governing_refs)),
  CHECK (code_floor_only IN (0, 1)),
  CHECK (has_unverified_sources IN (0, 1)),
  CHECK (all_sources_disqualified IN (0, 1)),
  CHECK (regulatory_stratum_only IN (0, 1)),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "specification_items__065" ("specification_id", "item_code", "state", "design_scale", "convergence_id", "confidence_dimensions_present", "confidence_dimensions_absent", "confidence_synthesis_basis", "gap_register_id", "not_applicable_rationale", "tier_basis", "governing_refs", "rule_version", "derivation_sha", "code_floor_only", "value_min", "value_max", "value_unit", "falsification_condition", "has_unverified_sources", "all_sources_disqualified", "created_at", "created_by_session", "updated_at", "updated_by_session", "regulatory_stratum_only", "identity_code") SELECT "specification_id", "item_code", "state", "design_scale", "convergence_id", "confidence_dimensions_present", "confidence_dimensions_absent", "confidence_synthesis_basis", "gap_register_id", "not_applicable_rationale", "tier_basis", "governing_refs", "rule_version", "derivation_sha", "code_floor_only", "value_min", "value_max", "value_unit", "falsification_condition", "has_unverified_sources", "all_sources_disqualified", "created_at", "created_by_session", "updated_at", "updated_by_session", "regulatory_stratum_only", "population_code" FROM "specification_items";
DROP TABLE "specification_items";
ALTER TABLE "specification_items__065" RENAME TO "specification_items";
CREATE INDEX "idx_specifications_item"   ON "specification_items"(item_code);
CREATE INDEX "idx_specifications_pop"    ON "specification_items"(taxonomy_code);
CREATE INDEX "idx_specifications_state"  ON "specification_items"(state);
CREATE UNIQUE INDEX "uq_specification_items_0" ON "specification_items" ("item_code", "taxonomy_code");

-- 5b. item_population_links + item_axis_links model the SAME relation.
--     Adding icf_code to one would make item-to-ICF expressible twice.
--     530 rows, one lens each. rationale_ref dropped: 0 of 372 populated.
--     Both CHECK vocabularies are carried; neither is reconciled here,
--     because reconciling applicability with strength_band is a content
--     judgement and this is a rename.
CREATE TABLE "base_item_taxonomy_links" (
  "item_code" TEXT NOT NULL,
  "subtype" TEXT NOT NULL DEFAULT '',
  "applicability" TEXT,
  "strength_band" TEXT,
  "use_mode" TEXT,
  "mechanism_note" TEXT,
  "source" TEXT,
  "created_at" TEXT,
  "created_by_session" TEXT,
  "identity_code" TEXT REFERENCES "base_taxonomy_identity"("code"),
  "icf_code" TEXT REFERENCES "base_taxonomy_icf"("code"),
  "needs_code" TEXT REFERENCES "base_taxonomy_needs"("code"),
  "medical_code" TEXT REFERENCES "base_taxonomy_medical"("code"),
  "taxonomy_code" TEXT GENERATED ALWAYS AS (COALESCE("identity_code","icf_code","needs_code","medical_code")) STORED,
  FOREIGN KEY ("item_code") REFERENCES "render_provisions"("item_code"),
  CHECK (applicability IN (
                        'applies', 'applies_strictly', 'applies_loosely',
                        'context_dependent', 'does_not_apply'
                      )),
  CHECK (strength_band IN ('full','partial','weak')),
  CHECK (use_mode IN ('independent','assisted','collective') OR use_mode IS NULL),
  CHECK ((identity_code IS NOT NULL) + (icf_code IS NOT NULL)
       + (needs_code IS NOT NULL) + (medical_code IS NOT NULL) = 1)
);
INSERT INTO "base_item_taxonomy_links" ("item_code","subtype","applicability","created_at","created_by_session","identity_code") SELECT "item_code", COALESCE("subtype",''), "applicability", "created_at","created_by_session","population_code" FROM "item_population_links";
INSERT INTO "base_item_taxonomy_links" ("item_code","subtype","strength_band","use_mode","mechanism_note","source","created_at","created_by_session","icf_code") SELECT "item_code", '', "strength_band","use_mode","mechanism_note","source", "created_at","created_by_session","axis_code" FROM "item_axis_links";
DROP TABLE "item_population_links";
DROP TABLE "item_axis_links";
CREATE UNIQUE INDEX "ux_base_item_taxonomy_links" ON "base_item_taxonomy_links" ("item_code","taxonomy_code","subtype");
CREATE INDEX "idx_base_item_taxonomy_links_item" ON "base_item_taxonomy_links" ("item_code");
CREATE INDEX "idx_base_item_taxonomy_links_code" ON "base_item_taxonomy_links" ("taxonomy_code");
-- item_axis_links keyed UNIQUE(item_code, axis_code) with no subtype, so
-- the union key above is one column WIDER and therefore weaker for ICF
-- rows. A partial index restores the original constraint exactly.
CREATE UNIQUE INDEX "uq_base_item_taxonomy_links_icf" ON "base_item_taxonomy_links" ("item_code","icf_code") WHERE "icf_code" IS NOT NULL;

-- 6. term_item_links.population: 0 of 147 populated. Rebuilt to drop it
--    rather than carrying a proven-dead column into a fresh table.
CREATE TABLE "base_term_item_links__065" (
  "term_id" TEXT NOT NULL,
  "item_code" TEXT NOT NULL,
  "notes" TEXT,
  "created_at" TEXT NOT NULL,
  "created_by_session" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "updated_by_session" TEXT NOT NULL,
  PRIMARY KEY ("term_id", "item_code"),
  FOREIGN KEY ("item_code") REFERENCES "render_provisions"("item_code"),
  FOREIGN KEY ("term_id") REFERENCES "base_terms"("term_id")
);
INSERT INTO "base_term_item_links__065" ("term_id", "item_code", "notes", "created_at", "created_by_session", "updated_at", "updated_by_session") SELECT "term_id", "item_code", "notes", "created_at", "created_by_session", "updated_at", "updated_by_session" FROM "base_term_item_links";
DROP TABLE "base_term_item_links";
ALTER TABLE "base_term_item_links__065" RENAME TO "base_term_item_links";
CREATE INDEX "idx_til_item"    ON "base_term_item_links"(item_code);

-- 7. recreate the 11 views with every reference re-pointed.
CREATE VIEW v_best_practice AS
    SELECT *,
           CASE
               WHEN regulatory_stratum_only = 1 THEN 'weak'
               ELSE 'anchored'
           END AS strength_band
    FROM "specification_items"
    WHERE state IN ('stated', 'provisional')
      AND code_floor_only = 0;
CREATE VIEW v_code_floor_only AS
    SELECT ecs.*, jv.jurisdiction, jv.standard_name,
           jv.value_numeric AS code_value, jv.unit AS code_unit
    FROM "specification_items" ecs
    LEFT JOIN "research_code_leads" jv ON jv.item_code = ecs.item_code
    WHERE ecs.code_floor_only = 1;
CREATE VIEW v_divergence AS
    SELECT ecs.*, ca.status AS convergence_status, ca.rationale AS convergence_rationale,
           ca.synthesis_approach AS convergence_synthesis_approach
    FROM "specification_items" ecs
    JOIN "synthesis_convergence" ca ON ca.convergence_id = ecs.convergence_id
    WHERE ca.status = 'divergent';
CREATE VIEW v_item_extractions AS
SELECT
    i.item_code,
    i.name                      AS item_name,
    i.category                  AS item_category,
    sve.extraction_id,
    sve.slug,
    sve.parameter,
    sve.parameter_canonical,
    jtl.taxonomy_code AS taxonomy_code,
    sve.jurisdiction,
    sve.claim_type,
    sve.claimed_value,
    sve.claimed_unit,
    sve.extraction_status,
    sve.extraction_method,
    sve.root_id,
    sve.root_type,
    sve.root_ref_id,
    sve.contested,
    sve.ref_id,
    es.tier                     AS source_tier,
    es.verification_status,
    sve.promoted_to_rdc_id
FROM "render_provisions" i
JOIN "judgment_items" sve ON sve.item_code = i.item_code
LEFT JOIN "judgment_item_taxonomy_links" jtl ON jtl.extraction_id = sve.extraction_id
LEFT JOIN "evidence_items" es     ON es.ref_id     = sve.ref_id;
CREATE VIEW v_item_provenance AS
SELECT
    i.item_code,
    i.name                      AS item_name,
    i.category                  AS item_category,
    ecs.specification_id,
    ecs.taxonomy_code,
    ecs.state                   AS cell_state,
    ecs.tier_basis,
    ecs.regulatory_stratum_only,
    csl.role                    AS source_role,
    es.ref_id,
    es.pub_title,
    -- POINTER, NOT COPY (migration 063). Was `es.author_display`, a writer-retired
    -- tombstone reading NULL. The authors have one home, evidence_source_authors, and
    -- v_evidence_authors renders it.
    va.author_display,
    es.pub_year,
    es.tier                     AS source_tier,
    es.evidence_type,
    es.verification_status,
    es.jurisdiction
FROM "render_provisions" i
JOIN "specification_items" ecs ON ecs.item_code = i.item_code
JOIN "specification_source_links"   csl ON csl.specification_id   = ecs.specification_id
JOIN "evidence_items"    es  ON es.ref_id     = csl.ref_id
LEFT JOIN v_evidence_authors va ON va.ref_id = es.ref_id;
CREATE VIEW v_pending AS
    SELECT ecs.*, g.description AS gap_description, g.category AS gap_category,
           g.priority AS gap_priority
    FROM "specification_items" ecs
    JOIN "research_gaps" g ON g.gap_id = ecs.gap_register_id
    WHERE ecs.state = 'pending';
CREATE VIEW v_pmp_latest_walk AS
SELECT
    item_code,
    slug,
    walk_id,
    MAX(created_at) AS walk_completed_at,
    SUM(CASE WHEN phase IN (
            'outer-pass-1st','outer-pass-2nd',
            'refinement-pass-1st','refinement-pass-2nd'
        ) THEN 1 ELSE 0 END) AS supported_steps,
    SUM(CASE WHEN phase IN (
            'outer-stop','refinement-stop'
        ) THEN 1 ELSE 0 END) AS terminator_steps
FROM "specification_value_probes"
GROUP BY item_code, slug, walk_id;
CREATE VIEW v_root_id_conflicts AS
    SELECT 'ref_id_has_multiple_root_ids' AS conflict_type,
           root_ref_id AS conflict_key,
           COUNT(DISTINCT root_id) AS distinct_count
    FROM "judgment_items"
    WHERE root_ref_id IS NOT NULL AND root_id IS NOT NULL
    GROUP BY root_ref_id HAVING COUNT(DISTINCT root_id) > 1
    UNION ALL
    SELECT 'root_id_spans_multiple_ref_ids' AS conflict_type,
           root_id AS conflict_key,
           COUNT(DISTINCT root_ref_id) AS distinct_count
    FROM "judgment_items"
    WHERE root_ref_id IS NOT NULL AND root_id IS NOT NULL
    GROUP BY root_id HAVING COUNT(DISTINCT root_ref_id) > 1;
CREATE VIEW v_source_reach_all AS
SELECT
    es.ref_id,
    es.pub_title,
    es.tier                     AS source_tier,
    es.verification_status,
    CASE WHEN ecs.specification_id IS NULL THEN 0 ELSE 1 END AS reaches,
    ecs.specification_id,
    ecs.item_code,
    i.name                      AS item_name,
    ecs.taxonomy_code,
    ecs.state                   AS cell_state,
    (SELECT GROUP_CONCAT(ssl.slug, '; ')
       FROM "evidence_slug_links" ssl
      WHERE ssl.ref_id = es.ref_id)  AS admitted_under_slugs
FROM "evidence_items" es
LEFT JOIN "specification_source_links"   csl ON csl.ref_id  = es.ref_id
LEFT JOIN "specification_items" ecs ON ecs.specification_id = csl.specification_id
LEFT JOIN "render_provisions" i                 ON i.item_code = ecs.item_code;
CREATE VIEW v_unregistered_roots AS
    SELECT sve.extraction_id, sve.slug, sve.parameter, sve.root_id
    FROM "judgment_items" sve
    WHERE sve.root_id IS NOT NULL
      AND sve.root_ref_id IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM "evidence_roots" err
          WHERE err.root_id = sve.root_id);
CREATE VIEW v_value_independence AS
    SELECT COALESCE(parameter_canonical, parameter) AS parameter,
           jtl.taxonomy_code,
           COUNT(DISTINCT COALESCE(root_ref_id, root_id)) AS independent_root_count
    FROM "judgment_items" sve
    LEFT JOIN "judgment_item_taxonomy_links" jtl ON jtl.extraction_id = sve.extraction_id
    WHERE root_type IN ('measurement_primary', 'participatory_finding',
                        'derived_calculation')
      AND (root_ref_id IS NOT NULL
           OR root_id IN (SELECT root_id FROM "evidence_roots"))
    GROUP BY COALESCE(parameter_canonical, parameter), jtl.taxonomy_code;

PRAGMA user_version = 65;
