#!/usr/bin/env python3
"""
scripts/emit_data_migration.py — create a properly-named data-migration file.

Per GAP-290 resolution. The migration system (scripts/migrate_db.py) requires
data migrations to be named:

    scripts/migrations/data_{YYYYMMDDHHMMSS}_{session-slug}.sql

This script generates one for you. Two concurrent sessions will produce files
with different timestamps and can both land cleanly on `main`.

Usage:

    # Pipe SQL from stdin
    cat my_changes.sql | python3 scripts/emit_data_migration.py \\
        --session session_2026-05-11g-citation-mining.md \\
        --summary "add 14 evidence_sources from REF-00710 backward mining"

    # Read from a file
    python3 scripts/emit_data_migration.py \\
        --session session_2026-05-11g-citation-mining.md \\
        --summary "cleanup orphan source_slug_links rows" \\
        --input cleanup.sql

    # Output path printed to stdout; the file is committed by you afterward.

The SQL body is wrapped in a single transaction (BEGIN ... COMMIT) so partial
failure rolls back. A frontmatter header with metadata is prepended.

Validation:
  - Refuses if the resulting filename would already exist (timestamp collision —
    rare, sleep 1s and retry)
  - Refuses if the SQL is empty
  - Warns if the SQL contains DROP / TRUNCATE / DELETE without WHERE
"""

import argparse
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

MIGRATIONS_DIR = Path(__file__).parent / "migrations"

RISKY_PATTERNS = [
    (re.compile(r"\bDROP\s+TABLE\b", re.I), "DROP TABLE"),
    (re.compile(r"\bTRUNCATE\b", re.I), "TRUNCATE"),
    (re.compile(r"\bDELETE\s+FROM\s+\w+\s*;", re.I), "DELETE without WHERE clause"),
    (re.compile(r"\bUPDATE\s+\w+\s+SET\s+[^;]+;", re.I), "UPDATE — check WHERE clause"),
]


def slugify_session(session: str) -> str:
    """Convert 'session_2026-05-11g-citation-mining.md' → '2026-05-11g-citation-mining'."""
    s = session
    if s.endswith(".md"):
        s = s[:-3]
    if s.startswith("session_"):
        s = s[len("session_"):]
    # Lowercase, alphanumeric and dash only
    s = re.sub(r"[^a-z0-9-]", "-", s.lower())
    s = re.sub(r"-+", "-", s).strip("-")
    return s


def main():
    p = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    p.add_argument("--session", required=True, help="Session filename, e.g. session_2026-05-11g-citation-mining.md")
    p.add_argument("--summary", required=True, help="One-line description for the frontmatter header")
    p.add_argument("--input", help="Read SQL from this path (default: stdin)")
    p.add_argument("--output-dir", default=str(MIGRATIONS_DIR))
    p.add_argument("--no-transaction", action="store_true",
                   help="Skip wrapping body in BEGIN/COMMIT (use only if the SQL contains its own transactions)")
    p.add_argument("--force-timestamp", help="Override timestamp (advanced; for tests only)")
    args = p.parse_args()

    if args.input:
        with open(args.input) as f:
            sql = f.read()
    else:
        sql = sys.stdin.read()

    sql = sql.strip()
    if not sql:
        print("ERROR: empty SQL body", file=sys.stderr)
        sys.exit(1)

    # Risky-pattern warnings
    warnings = []
    for pat, label in RISKY_PATTERNS:
        if pat.search(sql):
            warnings.append(label)
    if warnings:
        for w in warnings:
            print(f"  WARNING: detected risky pattern — {w}", file=sys.stderr)

    if args.force_timestamp:
        ts = args.force_timestamp
    else:
        ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    slug = slugify_session(args.session)
    filename = f"data_{ts}_{slug}.sql"
    out_path = Path(args.output_dir) / filename

    # Retry on collision (extremely rare — same session emitting two migrations in same second)
    retries = 0
    while out_path.exists() and retries < 5:
        time.sleep(1)
        ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        filename = f"data_{ts}_{slug}.sql"
        out_path = Path(args.output_dir) / filename
        retries += 1
    if out_path.exists():
        print(f"ERROR: filename collision unresolvable after {retries} retries: {out_path}", file=sys.stderr)
        sys.exit(1)

    iso = datetime.now(timezone.utc).isoformat(timespec='seconds')
    header = f"""-- {filename}
-- Data migration generated by scripts/emit_data_migration.py
-- Session:    {args.session}
-- Generated:  {iso}
-- Summary:    {args.summary}
--
-- This file is forward-only and immutable once committed. If a correction is
-- needed, emit a NEW data migration that compensates — do not edit this file.

"""
    body = sql if args.no_transaction else f"BEGIN TRANSACTION;\n\n{sql}\n\nCOMMIT;\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + body)
    print(str(out_path))


if __name__ == "__main__":
    main()
