import os, subprocess
SCR='/tmp/claude-0/-home-user-guidebook/5b214a57-ade4-5889-9a78-ce2de4360478/scratchpad'
S='session_2026-10-01-research-batch-23'
def run(args):
    r=subprocess.run(['python3','scripts/db.py']+args,env=dict(os.environ,GUIDEBOOK_DB_PATH=SCR+'/batch23.db'),capture_output=True,text=True)
    o=(r.stdout+r.stderr).strip().splitlines()
    print(args[2],args[4],args[6][:28],'->',r.returncode,' | '.join(o[-4:-1])[:150],flush=True)
A=[
 (82,'root_ref_id','REF-01031',"ADVERSARIAL-PASS REPAIR (F3/F11). Re-rooted to the OFFICIAL text, REF-01031 (law.go.kr flDownload PDF retrieved after the pass; item 12 reads identically to this mirror). CORRECTION of this row's note: it said the official host was unreachable; the law.go.kr page resets the connection but the flDownload endpoint serves the Annex. REF-01019 stays as the record of the mirror first retrieved."),
 (83,'root_ref_id','REF-01031',"ADVERSARIAL-PASS REPAIR (F11). Re-rooted to the official text, REF-01031. CORRECTION: the note above read the verb 완화할 수 있다 as 'a permission and not a 비고 recommendation'. The Annex's own 비고 (official PDF p. 22) says items phrased '…할 수 있다' are 권장사항 (recommendations) and this clause is so phrased; whether the 비고 was written to cover a relaxation permission is not stated. That reading is WITHDRAWN as an override of the source's own convention; the verb's status is left open (see REF-01031's relaxation row)."),
 (95,'root_ref_id','REF-01032',"ADVERSARIAL-PASS REPAIR (F7/F12). Re-rooted to the Diário da República ORIGINAL, REF-01032 (retrieved after the pass; text identical). CORRECTIONS: (1) the note called Portugal's missing JurisdictionCode an 'owner decision'; the record shows it PENDING, not decided (sessions/session_2026-09-28-research-batch-22-selection.md section 3, 'Left to the owner'; references/project-standards.md 2026-09-28 ruling treats the class as blocked, not licensed). (2) Currency of Anexo 2.5 is NOT established: PGDL lists DL 136/2014, DL 125/2017, DL 95/2019 and DL 10/2024 as amending decrees; this row rests on the 2006 text."),
 (96,'root_ref_id','REF-01032',"ADVERSARIAL-PASS REPAIR (F7/F12). Re-rooted to the DR original REF-01032; same two corrections as extraction 95 (jurisdiction gap is pending not decided; Anexo 2.5 currency unestablished)."),
 (97,'root_ref_id','REF-01032',"ADVERSARIAL-PASS REPAIR (F7/F12). Re-rooted to the DR original REF-01032; same two corrections as extraction 95 (jurisdiction gap is pending not decided; Anexo 2.5 currency unestablished)."),
 (100,'comparator','<=',"ADVERSARIAL-PASS CORRECTION (F5/F6). The note above said the retrieved BOE text does not set a 6% maximum. IT DOES: art. 5.2 g) of Orden TMA/851/2021 reads 'La pendiente longitudinal máxima será del 6%' for the accessible pedestrian itinerary -- a ROUTE/street rule (GAP-033 scope), not the ramp rule of art. 14, and not extracted here. The web-search summary was route-scoped, not false. Also: the retrieved artefact is a BOE consolidation ('Última actualización publicada el 03/09/2026', 'sin valor oficial') that flags Real Decreto 707/2026 as altering arts. 32 and 47 from 2027-01-02; it carries no such flag at art. 14."),
 (102,'extraction_method','full-read',"ADVERSARIAL-PASS CORRECTION (F5). The inference above, that 'límite que marca la ley' is the 6% ramp-definition threshold of art. 14.1, is WITHDRAWN. Orden VIV/561/2010 art. 5.2 h) separately sets 'La pendiente longitudinal máxima será del 6%' for the accessible pedestrian itinerary, which is the limit a reader of 'calles en pendiente' would reach for. The row stays a street-slope finding."),
 (101,'root_type','untraced',"ADVERSARIAL-PASS REPAIR (F13). The 10%/8% tiers trace to Orden VIV/561/2010 art. 14.1 b), which was retrieved but NOT admitted (derogated 2022-01-02): the root is not held in this corpus, so 'untraced' (batch-19 precedent), not a self-rooted committee assertion. (v_value_independence ignores committee_assertion and untraced rows alike; this keeps the typed column consistent with the note.)"),
 (87,'root_type','untraced',"ADVERSARIAL-PASS REPAIR (F13). IPLO restates Bbl art. 4.30's 1:16 tier; the legal text of that row was not retrieved (wetten.overheid.nl, inview.nl failed), so the root is not held in this corpus: 'untraced'."),
 (88,'root_type','untraced',"ADVERSARIAL-PASS REPAIR (F13). IPLO restates Bbl art. 4.30's 1:20 tier; the legal text of that row was not retrieved, so the root is not held in this corpus: 'untraced'."),
 (99,'comparator','<=',"ADVERSARIAL-PASS CORRECTION (F15). The sentence 'Run lengths are measured in horizontal projection, per section' is drawn from the Ministry's non-regulatory COMMENTS, which this row says are not extracted; it is withdrawn from the row. Also: the articulado is the 14 junio 2022 text (RD 450/2022) and the 15 julio 2024 date is the comments version (PDF p. 1: 'Articulado: 14 junio 2022 / Comentarios: 15 julio 2024'), so the source's pub_year 2024 is the comments edition."),
]
for eid,field,val,reason in A:
    run(['amend-extraction','--extraction-id',str(eid),'--field',field,'--value',val,'--reason',reason,'--session',S])
